### ISSUE TITLE
SimplePie::sort_items() should sort NULL values to the end of the array instead of the beginning.

### ISSUE THREAD

**Issue by rmccue** [simplepie/simplepie#10]
_Originally reported by Ryan Parman as [issue 34](http://bugs.simplepie.org/issues/show/34)_

SimplePie::sort_items() uses PHP's basic usort() function, and that if one of the comparative values is null (which, I believe, is what get_date('U') returns with a non-existent or invalid date stamp), usort() will simply not sort the value, leaving it at the beginning of the returned array. This tends to cause quite a bit of confusion for users, so we should add additional logic that checks the value of get_date() before comparison, and if it is null (or similar), move that item to the end of the array.

**Comment by szabacsik** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  andras.szabacsik@gmail.com
    Domain szabacsik.hu has exceeded the max emails per hour (60/50 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:35063 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by hardcube.23net.hu with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dPMGw-003iIu-N0
	for andras@szabacsik.com; Mon, 26 Jun 2017 07:09:15 +0200
Date: Sun, 25 Jun 2017 22:08:33 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1498453713;
	bh=1EXvK7Cm1aomU0bxauzYx6w/qyGuUyGa5+sqcIZIGqY=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=iVwq+yQ9QVMylE/+RJUZs3E9kp2/24lLIYjyboQ/uxb0OwbXkmVrDjZIaHmHEIUe9
	 gTwN4tdliisobFJ2PxZQJZHHmwW+UF75J+yBvqA+Sg/OuOQYsXIJajVyciUr+K3R65
	 +ImaAkSfpiQP2toBWbI6RRAdP2mSIHVx1yPmJgH0=
