### ISSUE TITLE
Limit the cache size (auto-cleanup)

### ISSUE THREAD

**Issue by youlichika** [simplepie/simplepie#100]
I subscribed many rss feeds from many rss source(50+) I just want to show one rss item from each rss source, but the size of cache folder is already over 15MB. I opened one cache with dreamweaver, I noticed the cache stored all the rss items from each rss source, and it caused 'Maximum execution time of 30 seconds' in simpleoie.inc... I always refresh 3 or 4 times, then show the whole home page. 
How to limit the cache size? and avoid the 'Maximum execution time of 30 seconds'? 
Thanks.

**Comment by ifsnop** [comment]
Fixed in 9bc11041c087333b97ef3c66237b95a1a9a56a81.
