### ISSUE TITLE
Cache status methods

### ISSUE THREAD

**Issue by rmccue** [simplepie/simplepie#12]
_Originally reported by Ryan Parman as [issue 37](http://bugs.simplepie.org/issues/show/37)_

We've gotten many requests over the years from people who want to know more about the status of their cache. I threw together an add-on for SP 1.0 that broke for 1.1. I'd like to propose adding a few methods for 1.2.
- `$feed->get_cache()` would return some sort of reference to the cache object.
- `$feed->get_cache()->get_exists()` would be a boolean response. True if cache exists for this feed (DB or FS)
- `$feed->get_cache()->is_fresh()` would be a boolean response. True if cache exists for this feed. Should we allow values for "Yes, it's fresh", "No, it's expired", and that in-between "It's expired but the most recent fetch failed so we're re-using the expired cache"?
- `$feed->get_cache()->get_filename()` would return either the FS filename or a DB identifer (or whatever the most useful data is for this).
- `$feed->get_cache()->get_timestamp()` would return the Unix timestamp for when the cache was created/refreshed (i.e. whenever the cache decides is the "start").
- `$feed->get_cache()->get_time_remaining()` would return the number of seconds until the cache expires.

I'm open to other ideas, as well as best ways to implement this or even if users would find it useful.

**Comment by szabacsik** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  andras.szabacsik@gmail.com
    Domain szabacsik.hu has exceeded the max emails per hour (59/50 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:35689 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by hardcube.23net.hu with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dPMGr-003iI7-8b
	for andras@szabacsik.com; Mon, 26 Jun 2017 07:09:09 +0200
Date: Sun, 25 Jun 2017 22:08:28 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1498453708;
	bh=7TaD6hUCKQEtBNrEYBlocfPMEH8Pd25CgOqC4RrB5dQ=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=JPVDC12mowFpRJBLBsqd2Ic0mh07387CHexpYIySzJ64ZANl2D5kTZoIL/5QkOKG4
	 zUNjhFGK4sVCTqvLKUwuy3soIxBoMkwaiewfx/GaYKL6mMEzEPkmt72mDg2Aewv3+I
	 6AzXAV0EhxKe6UUl0NZXWiv5+1QCkVwIJUXXcQtQ=
