### ISSUE TITLE
Make it easier to add to, remove from, replace, or disable element and attribute stripping.

### ISSUE THREAD

**Issue by rmccue** [simplepie/simplepie#13]
_Originally reported by Ryan Parman as [issue 41](http://bugs.simplepie.org/issues/show/41)_

Currently, SimplePie::strip_htmltags() and SimplePie::strip_attributes() contain a default set of elements/attributes (referred to simply as "elements" from here forward) to strip. To replace the list, you simply pass in a new array of elements, and to disable you pass in a boolean false.

But there are also times when people want to take the existing default list, and either add new elements to it, or remove elements from it. There are samples of code posted to http://simplepie.org/wiki/reference/simplepie/strip_htmltags but this could definitely be made easier by integrating support into SimplePie::strip_htmltags() and SimplePie::strip_attributes() themselves.

We could add a second parameter to these methods where a value of zero (default) equates to "replace" (i.e. passing in a new array or a boolean false replaces existing settings). A value of 1 (or any other positive integer) would be equivalent to "add to", and a value of -1 (or any other negative integer) would be equivalent to "remove from".

In the end, people who want to keep the default list of HTML elements to strip but want to remove object, param, and embed from the strip-list could do this:

$feed->set_htmltags(array('object', 'param', 'embed'), -1);

Alternatively, we could go with keywords like "add", "replace" (default), and "remove". Thoughts?

**Comment by Frenzie** [comment]
I think of "replace" more like:

1. We have attribute `x`.
2. We "replace" the value of attribute `x` with some sanitized version of attribute `x`, e.g., `class="bla"` to `class="prefix--bla"` so it never clashes with your own styles.

To replace in the sense of a completely different set of elements/attributes to be stripped I'd say just pass in an array.

**Comment by szabacsik** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  andras.szabacsik@gmail.com
    Domain szabacsik.hu has exceeded the max emails per hour (58/50 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:33213 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by hardcube.23net.hu with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dPMGm-003iGo-PA
	for andras@szabacsik.com; Mon, 26 Jun 2017 07:09:05 +0200
Date: Sun, 25 Jun 2017 22:08:23 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1498453703;
	bh=vg+1Dr+McQmadOOp9tKTkQweBr7n3WbaAg6hztRIaEU=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=LIMkhCTpQomYEICmrGYK435wBIyFiraRurpdibTNZQSR3lDKD9MB6UNM4VmZIH9U+
	 7dawQHcEF+Re3VTAMxHLvW0tsUmxUEkI2xFsKOwFn8X9RqnCgkFdvulM535Q8uHZj/
	 hU8bLGk3eNw+lfD3Uj9EBEffY0ZIfhXiCmvQBV6k=
