### ISSUE TITLE
Break methods like init() and sanitize() into smaller sub-methods

### ISSUE THREAD

**Issue by rmccue** [simplepie/simplepie#15]
_Originally reported by Ryan Parman as [issue 52](http://bugs.simplepie.org/issues/show/52)_

This has not yet been properly evaluated, so nothing stated here is a definitive "we need to do this", but it would likely be helpful for people extending SimplePie to be able to override smaller chunks of large methods (such as `init()` and `sanitize()`) without having to re-write the entire thing.

An example of this is for those who want to add custom favicon sniffing code. At the moment it is very difficult to add functionality like this without overriding the entire `sanitize()` method. If this were broken into smaller sub-methods, such a task would likely be easier.

**Comment by szabacsik** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  andras.szabacsik@gmail.com
    Domain szabacsik.hu has exceeded the max emails per hour (57/50 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:60014 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by hardcube.23net.hu with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dPMGa-003iFZ-IR
	for andras@szabacsik.com; Mon, 26 Jun 2017 07:08:52 +0200
Date: Sun, 25 Jun 2017 22:08:11 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1498453691;
	bh=6KWDlPCrdQgCrtQpFrIGjGZ5ag9peb2sSXmybdkKn5k=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=annaWWynphaTZW+J2bj/FV8al6bF2mYiaYitRi++lxVeo+7DhOAxe9CiigKiXHmge
	 mpkEPAsRt5BfNNAZ4Ze7sTWEEVlmoaAstI6qrsjpZO7Zr94YYBPRCPKEG/uEW3zu8Z
	 rdWOVkR6G1XaewUSCH6/P0WJBh9eOJW1PT5tEEeA=
