### ISSUE TITLE
Debug Mode

### ISSUE THREAD

**Issue by rmccue** [simplepie/simplepie#16]
_Originally reported by Ryan Parman as [issue 53](http://bugs.simplepie.org/issues/show/53)_

We've talked about this before, but there should be some sort of debug mode that — when enabled — can give us useful information for debugging issues.
This debug info might include:

```
* PHP version
* SimplePie/Plugin version
* Versions of installed extensions
* Database type and version
* Error stack trace
* Expected cache location and whether it exists and is writable (file system caching only)
* Other stuff?
```

**Comment by szabacsik** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  andras.szabacsik@gmail.com
    Domain szabacsik.hu has exceeded the max emails per hour (56/50 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:11119)
	by hardcube.23net.hu with esmtps (TLSv1:DHE-RSA-AES128-SHA:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-d5b6-andras=szabacsik.com@sgmail.github.com>)
	id 1dPMGY-003iEz-Uh
	for andras@szabacsik.com; Mon, 26 Jun 2017 07:08:51 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=bExBn2c83aHsXU+kKk+KE58bDcU=; b=jDz3BQ8dUUhM+1PI
	fzbRNYxlVctwgpwoS3OhtY+qDBNz/x89oEZPHEtE+AUM8M66hGmLx30xNwafqBn8
	q0vyOzSsHtWuyrBCjXh2aci0Jo7sJYVmJcfx4WNXHA4ErmR3W5tdhIdT7GF8PRCz
	gteQJQF/KT0OpPYTK//oGCb2aGs=
Received: by filter0806p1mdw1.sendgrid.net with SMTP id filter0806p1mdw1-8387-595096B8-A
        2017-06-26 05:08:08.192092502 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id LnjmcBBwQVCH7s31OcmIkQ
	for <andras@szabacsik.com>; Mon, 26 Jun 2017 05:08:08.151 +0000 (UTC)
Date: Sun, 25 Jun 2017 22:08:08 -0700
