### ISSUE TITLE
provide an option to set the curl option SSL_VERIFYPEER to false

### ISSUE THREAD

**Issue by natepixel** [simplepie/simplepie#165]
It seems like curl often has spotty support for recognizing valid certificates. As a result, using simplepie to grab certain feeds (such as the GitHub commit feed) fails with certificate warnings. If you add a line like this to the __construct method of SimplePie_FIle, the problem goes away:

curl_setopt($fp, CURLOPT_SSL_VERIFYPEER, false);

Making a blanket change in file.php probably isn't ideal. What would be great, however, would be an option to set SSL_VERIFYPEER to false .. something like this:

$simplepie = new SimplePie;
$simplepie->set_curlopt_ssl_verifypeer(false);

**Comment by Alkarex** [comment]
See https://github.com/simplepie/simplepie/pull/407
