### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by rmccue** [simplepie/simplepie#19]
_Originally reported by Proxy Pete as [issue 84](http://bugs.simplepie.org/issues/show/84)_

The following diff adds proxy support (based up http://simplepie.org/support/viewtopic.php?id=1133) but for 1.1.1

**Comment by szabacsik** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  andras.szabacsik@gmail.com
    Domain szabacsik.hu has exceeded the max emails per hour (55/50 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:34756)
	by hardcube.23net.hu with esmtps (TLSv1:DHE-RSA-AES128-SHA:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-d5b6-andras=szabacsik.com@sgmail.github.com>)
	id 1dPMGS-003iB5-6O
	for andras@szabacsik.com; Mon, 26 Jun 2017 07:08:44 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=l6EtD3i25XqUnIPqVP20cEj3xvY=; b=g6afhaFg17hEvegx
	GXgYslYjexPWirPDT+y9rNOXpJgAfVuaTMS6YNckLYUuAzihGz06IOQ79PnZZagn
	C4AmC/5oS6oBxLWAmxuxMIkJbEqqUFu6OUskCZ5I5HAaNC8IjjWC41THJQtJniul
	xGZrLYvlYeJgX1H1+PSziApyw8g=
Received: by filter0977p1mdw1.sendgrid.net with SMTP id filter0977p1mdw1-25966-595096B1-9
        2017-06-26 05:08:01.313450636 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id m4-RjdBJSvSb38T6aggrLw
	for <andras@szabacsik.com>; Mon, 26 Jun 2017 05:08:01.298 +0000 (UTC)
Date: Sun, 25 Jun 2017 22:08:01 -0700
