### ISSUE TITLE
SimplePie::subscribe_url() should follow permanent redirects

### ISSUE THREAD

**Issue by rmccue** [simplepie/simplepie#2]
_Originally reported by Ryan Parman as [issue 8](http://bugs.simplepie.org/issues/show/8)_

This is complicated because we mustn't cache temporary redirects, meaning it needs large changes in our HTTP client.

**Comment by jtojnar** [comment]
Why was this closed? We encountered this issue in selfoss too: https://github.com/SSilence/selfoss/pull/1124

It can be fixed rather simply:

```patch
--- a/library/SimplePie.php
+++ b/library/SimplePie.php
@@ -1712,8 +1712,8 @@
 					}
 					$cache = $this->registry->call('Cache', 'get_handler', array($this->cache_location, call_user_func($this->cache_name_function, $file->url), 'spc'));
 				}
-				$this->feed_url = $file->url;
 			}
+			$this->feed_url = $file->url;
 			$locate = null;
 		}
 
```

**Comment by jtojnar** [comment]
Here is MVE:

```
$feed = new \SimplePie();
$feed->set_feed_url('http://google.de/alerts/feeds/18120933104492874959/12861401000818240705');
$feed->enable_cache(false);
$feed->init();
$feedUrl = $feed->subscribe_url();
var_dump($feedUrl);
```

**Comment by skyzyx** [comment]
It was closed because the issue had been open since 2009 with no movement. We decided not to kid ourselves about it ever happening.

If it’s important to you, please provide a PR _with tests_ to show that it actually does what it intends to do, and doesn’t break other functionality.

**Comment by jtojnar** [comment]
Done #627
