### ISSUE TITLE
Allow the XML parser to be more lax 

### ISSUE THREAD

**Issue by rmccue** [simplepie/simplepie#21]
_Originally reported by Anonymous as [issue 92](http://bugs.simplepie.org/issues/show/92)_

Some feeds contain white space at the beginning of the feed, and on PHP 4.4.9 on Debian etch, this is correctly flagged as malformed XML. Likewise, the parser chokes in the presence of otherwise harmless control characters - quite correctly, given the XML specs.

PHP 5 on MacOS X 10.5 parses these feeds, skipping over the offending characters.

This code (a subclass of SimplePie_Parser) fixes it, even it has to steal some code from the superclass to get past the BOMs:

```
class CleanerParser extends SimplePie_Parser {

function parse(&$data, $encoding) {
}

// Remove illegal control chars - leave only 0x09, 0x0A, 0x0D    

    $txt = ereg_replace("[\x01-\x08]|\x0B|\x0C|[\x0E-\x1F]", "", $txt); 
}

// Strip BOM:

// UTF-32 Big Endian BOM

if (substr($data, 0, 4) === "\x00\x00\xFE\xFF")
{

    $data = substr($data, 4);

}

// UTF-32 Little Endian BOM

elseif (substr($data, 0, 4) === "\xFF\xFE\x00\x00")
{

    $data = substr($data, 4);

}

// UTF-16 Big Endian BOM

elseif (substr($data, 0, 2) === "\xFE\xFF")
{

    $data = substr($data, 2);

}

// UTF-16 Little Endian BOM

elseif (substr($data, 0, 2) === "\xFF\xFE")
{

    $data = substr($data, 2);

}

// UTF-8 BOM

elseif (substr($data, 0, 3) === "\xEF\xBB\xBF")
{

    $data = substr($data, 3);

}

// Remove white space (empty lines, etc.) before the first XML decl.

$data = trim($data);

return SimplePie_Parser::parse($data, $encoding);
```

**Comment by samwilson** [comment]
I am getting the leading-space issue with current stable SimplePie on PHP 5.6.10 for e.g. this feed http://fremantleanglican.com/feed/

**Comment by szabacsik** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  andras.szabacsik@gmail.com
    Domain szabacsik.hu has exceeded the max emails per hour (54/50 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o8.sgmail.github.com ([167.89.101.199]:50779)
	by hardcube.23net.hu with esmtps (TLSv1:DHE-RSA-AES128-SHA:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-d5b6-andras=szabacsik.com@sgmail.github.com>)
	id 1dPMGK-003hsc-OO
	for andras@szabacsik.com; Mon, 26 Jun 2017 07:08:37 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=v6J63szUv688HrAVmzG1EmxXfG0=; b=Duhd3ADrE9z9453P
	6UTfZm1LAflF7ppAfYVclc0LCcijk2n5JtBnjv+mjCvglCyMoz9XbwqWOoWV0GW3
	ORLyPutYSL+K5B9DjiEcnagNbmqqE/rPR4zi1/tHldh9fztMAofSlp+f/e1j/FrE
	Mml/0UYv3eOO2AQDR7DAg+SfK4A=
Received: by filter0972p1mdw1.sendgrid.net with SMTP id filter0972p1mdw1-15239-595096AA-17
        2017-06-26 05:07:54.252858746 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id r9paZszqTaSic6nGEFmnJQ
	for <andras@szabacsik.com>; Mon, 26 Jun 2017 05:07:54.210 +0000 (UTC)
Date: Sun, 25 Jun 2017 22:07:54 -0700
