### ISSUE TITLE
SimplePie_Misc cannot be overriden

### ISSUE THREAD

**Issue by rmccue** [simplepie/simplepie#22]
_Originally reported by Ryan McCue as [issue 98](http://bugs.simplepie.org/issues/show/98)_

Branching this from #50:
SimplePie needs a way to override the SimplePie_Misc class, by way of something like set_misc_class()

**Comment by szabacsik** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  andras.szabacsik@gmail.com
    Domain szabacsik.hu has exceeded the max emails per hour (53/50 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:2388)
	by hardcube.23net.hu with esmtps (TLSv1:DHE-RSA-AES128-SHA:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-d5b6-andras=szabacsik.com@sgmail.github.com>)
	id 1dPMGF-003hru-8h
	for andras@szabacsik.com; Mon, 26 Jun 2017 07:08:31 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=faIQs/C6yJPD8VXAV9MfAkfMIlg=; b=YQd3EPRSBqJtJrUr
	ZeeLCvQUyVTRj7n6bLagNMroSq4y5KhJ3HS0LQhV18NTtHv6N/uaLz+WsBj8M/OA
	QVlFKGOwfnUHI8PlCAegv35uekWYwZ5M3scn84898I71b1szxKaqUQEVNumFmPVK
	i3TauwJDwkbw2Jel3kqIlg5AdvY=
Received: by filter0500p1mdw1.sendgrid.net with SMTP id filter0500p1mdw1-8715-595096A4-1B
        2017-06-26 05:07:48.423900888 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id _8LPg84SQjyRKYAcERd9jg
	for <andras@szabacsik.com>; Mon, 26 Jun 2017 05:07:48.429 +0000 (UTC)
Date: Sun, 25 Jun 2017 22:07:48 -0700
