### ISSUE TITLE
PHP Fatal error:  Class 'SimplePie_Cache_DB' not found

### ISSUE THREAD

**Issue by marcelometal** [simplepie/simplepie#231]
Hi,

the bug below happens because library/SimplePie/Cache/DB.php should be included first then library/SimplePie/Cache/MySQL.php in SimplePie.compiled.php

PHP Fatal error:  Class 'SimplePie_Cache_DB' not found in /home/metal/debian/simplepie/SimplePie.compiled.php on line 11857
PHP Stack trace:
PHP   1. {main}() /root/simplepie/test-1.3.0.php:0
PHP   2. include_once() /root/simplepie/test-1.3.0.php:2

**Comment by ifsnop** [comment]
Merged in https://github.com/simplepie/simplepie/commit/6f76136cc0d531d985e1439f7915b985f4bb9087
