### ISSUE TITLE
Check CRC of gzip streams

### ISSUE THREAD

**Issue by rmccue** [simplepie/simplepie#24]
_Originally reported by Anonymous as [issue 111](http://bugs.simplepie.org/issues/show/111)_

The CRC of gzip streams is currently ignored (as of r1022) to get the decoder to work.

http://bugs.php.net/bug.php?id=45028 may be relevant.

**Comment by szabacsik** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  andras.szabacsik@gmail.com
    Domain szabacsik.hu has exceeded the max emails per hour (52/50 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:20196)
	by hardcube.23net.hu with esmtps (TLSv1:DHE-RSA-AES128-SHA:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-d5b6-andras=szabacsik.com@sgmail.github.com>)
	id 1dPMGB-003hrD-O0
	for andras@szabacsik.com; Mon, 26 Jun 2017 07:08:28 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=jFhB2GDZLSMgjuDS9K6U2cY9Umc=; b=Pe17XIu0oU1+IYP1
	sQqnAcwa5Tv/Nrcp8iWycNswTls5/4nHK4qnXv3XEcm18VLfUb5OLm5vHUt1OK/V
	QSXy0QDIurMvJ24el4vNIV2oglbbuEnCtiwyzPV7VEBfFr1vVD59EhEmmBkaX1tU
	4nSErPbGPipRjv/pGMXPMvUFkuA=
Received: by filter0823p1mdw1.sendgrid.net with SMTP id filter0823p1mdw1-1001-5950969F-4A
        2017-06-26 05:07:44.002159167 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id kknw_8XFTlinHYaFklhKNQ
	for <andras@szabacsik.com>; Mon, 26 Jun 2017 05:07:43.933 +0000 (UTC)
Date: Sun, 25 Jun 2017 22:07:43 -0700
