### ISSUE TITLE
Mismatched tags in valid RSS feed

### ISSUE THREAD

**Issue by AJ** [simplepie/simplepie#247]
When trying to parse the RSS feed for Forbes.com, I get the following error:

PHP Notice: This XML document is invalid, likely due to invalid characters. XML error: Mismatched tag at line 41, column 8 in .../simplepie/library/SimplePie.php on line 1374

The feed contents are located at: 
https://gist.github.com/2603430c40441987baf9

I've run the contents of the feed through an online XML validator which validates it fine. So I'm not sure what the issue is.

**Comment by AJ** [comment]
I noticed that you've closed all of my previously reported bugs without a comment (and presumably a fix). Should we consider the project suspended/abandoned?

**Comment by skyzyx** [comment]
No. I simply closed out issues that were either ancient, didn't have a PR, or have a low probability of ever being realistically added to SimplePie 1.x. If it hasn't moved in 5 years, it's not likely to move. ☹️ 

Shared hosting providers suck, and oftentimes the UTF-8 decoding has issues no matter what we do. Your best bet is to use a real web server from AWS or Google Cloud where you can configure the machine yourself.

I am presently working on a rewrite from scratch, and am adding your test feed to the list of things to write tests for.

Sorry. 😬

**Comment by skyzyx** [comment]
https://github.com/simplepie/simplepie-ng/commit/167edad41f66632cdba9cda9f02f3ef1a97aaed0
