### ISSUE TITLE
Growing memory consumption on get_links (including fix!)

### ISSUE THREAD

**Issue by h2ooooooo** [simplepie/simplepie#260]
Problem question and fix on this SO post:

http://stackoverflow.com/questions/14337179/why-am-i-getting-memory-leaks-in-simplepie-when-using-item-get-permalink/

**Comment by talgalili** [comment]
I believe this issue is now resolved, and should be closed. See:

https://github.com/simplepie/simplepie/commits/master/library/SimplePie/IRI.php
