### ISSUE TITLE
Support for the RSS TTL element

### ISSUE THREAD

**Issue by rmccue** [simplepie/simplepie#27]
_Originally reported by Anonymous as [issue 114](http://bugs.simplepie.org/issues/show/114)_

See: http://cyber.law.harvard.edu/rss/rss.html#ltttlgtSubelementOfLtchannelgt

**Comment by szabacsik** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  andras.szabacsik@gmail.com
    Domain szabacsik.hu has exceeded the max emails per hour (51/50 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:8425)
	by hardcube.23net.hu with esmtps (TLSv1:DHE-RSA-AES128-SHA:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-d5b6-andras=szabacsik.com@sgmail.github.com>)
	id 1dPMFu-003hpi-OY
	for andras@szabacsik.com; Mon, 26 Jun 2017 07:08:11 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=xk/ntMEvuzWSn7BXIBGEvqxvzhc=; b=UGLnXT+vyx4kp1Q9
	nLBi36sdFtM+hUggU01KU6qzPG7zI8rCuGG7A4kozrgVkDNyyiXRLWrXeQU3OfvE
	AD4s4EpVvNIVuif4ZGE6L9c59SigJ0crSn2THVaWU2TEfgY5Ul56XoiGn7U6JJcS
	+tn4q+0ACIEIh3Uqp52hHyiy2/Y=
Received: by filter0920p1mdw1.sendgrid.net with SMTP id filter0920p1mdw1-2718-59509690-17
        2017-06-26 05:07:28.17560653 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id mbRXpU7jTJWi2VNJ46iUTQ
	for <andras@szabacsik.com>; Mon, 26 Jun 2017 05:07:28.134 +0000 (UTC)
Date: Sun, 25 Jun 2017 22:07:28 -0700
