### ISSUE TITLE
SimplePIe RSS Reader NOT working with WordPress Feeds

### ISSUE THREAD

**Issue by gteigland** [simplepie/simplepie#282]
odd but I've tried multiple wordpress feeds and my Simple Pie won't read it but other feeds do (i.e. MPR, ESPN ).  Here's the error I receive on this page:

Warning: simplexml_load_file() [function.simplexml-load-file]: http://blog.bairservices.com/feed/:1: parser error : Document is empty in /home/bairse5/public_html/rssbox/simplepie/RSSLoader.php on line 9

Also I looked in wordpresses wp-feed.php to see if there was an issue that doesn't play well with simplepie but didnt' find any but here's the code.

?php
/**
- Redirects to the default feed
- This file is deprecated and only exists for backwards compatibility
  *
- @package WordPress
  */

require( './wp-load.php' );
wp_redirect( get_bloginfo( get_default_feed() . '_url' ), 301 );

?>

Any help would be appreciated!

**Comment by jackbrownn93** [comment]
I have tried to fix this but I am having the same issue " This feed does not validate.

`Server returned HTTP Error 304: Not Modified `
I have also attached here a screenshot.

`line 1, column 0: XML parsing error: <unknown>:1:0: no element found`
I have previously did changes and it was working well but suddenly the feed not opening. Can someone please review the site [Mesheble.com](https://mesheble.com/) and let me know the possible solution?

Also I am validating it on validator and getting the same error Feed Validator Results: [https://mesheble.com/feed/[^]](https://mesheble.com/feed/)

I have also attached a screenshot <img>https://imgur.com/a/ws2GypP</img>
