### ISSUE TITLE
error on import db.sql

### ISSUE THREAD

**Issue by newtosimplepie** [simplepie/simplepie#285]
Hi there,

To set up db caching in mysql, i've tried to import the supplied db.sql into mysql. However, I received the following error:

-----------------------------------------------------------------
SQL query:

CREATE UNIQUE INDEX id ON cache_data(
id
);

MySQL said: Documentation
#1170 - BLOB/TEXT column 'id' used in key specification without a key length 
-----------------------------------------------------------------

I looked up the database structure and it has 4 fields: id, items, data, mtime. It looks like it has imported successfully, but I'm not sure. Anyone can help? 

Thanks!

ps. the actual goal of my whole exercise is to use simplepie to dump feeds in a database (i'm taking a look at the cache db to see which fields I'll need). From there I'll post the items on my webpage. I'm not much of an expert, but so far I feel it will work :)

**Comment by ifsnop** [comment]
There are now comments that explain which sql should be used in what database. Fixed in commit 189c582207b8a5ff7c23535f8a693ef131fc3b00.

Also, the Mysql cache code creates the tables, so there is no need to type anything.
