### ISSUE TITLE
Simple pie page not available issue

### ISSUE THREAD

**Issue by ghost** [simplepie/simplepie#296]
When running simplepie then some feeds comes but then it goes to web page unavailable

**Comment by szabacsik** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  andras.szabacsik@gmail.com
    Domain szabacsik.hu has exceeded the max emails per hour (57/50 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:29791)
	by hardcube.23net.hu with esmtps (TLSv1:DHE-RSA-AES128-SHA:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-d5b6-andras=szabacsik.com@sgmail.github.com>)
	id 1dPM7K-003e1d-48
	for andras@szabacsik.com; Mon, 26 Jun 2017 06:59:18 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=bjIv/GfVf+MXDIf0UVY61V8+Mcc=; b=ievJO/eo6owqRwQT
	bN02a23F8FpvMM/SgRJFrMhhT6GZADJZ2MGnPrLCexitlc6g2EtQ3UAc+MIe9fPX
	QcUUMNRiVFJMEdpEw4xvyaCA7bjaX5wPuQ0MAfYybusbQNb9QShzeKKx/9BbLMhX
	zk1A4Aj6wOtOQzo/K2Q8MSzybXk=
Received: by filter0913p1mdw1.sendgrid.net with SMTP id filter0913p1mdw1-7313-5950947B-26
        2017-06-26 04:58:35.473899217 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id zDmM0nX-Sp60vM4VS_WIZg
	for <andras@szabacsik.com>; Mon, 26 Jun 2017 04:58:35.431 +0000 (UTC)
Date: Sun, 25 Jun 2017 21:58:35 -0700
