### ISSUE TITLE
SimplePie 1.3.1 - get_all_discovered_feeds() returns an object instead of an array

### ISSUE THREAD

**Issue by dloader** [simplepie/simplepie#297]
There are actually 2 problems identified in this issue.  Let me know if you want me to open another issue.

Using SimplePie 1.3.1 to autodiscover  using URL http://www.nypost.com/Rss

set_stupidly_fast(True)
enable_cache(False)
set_autodiscovery_level(SIMPLEPIE_LOCATOR_ALL)
set_max_checked_feeds(200)

SimplePie->init() does not return False;
SimplePie->error is empty;

SimplePie->get_all_discovered_feeds() returns a single SimplePie_File object rather than an array of SimpePile_File objects.  It appears that the SimplePie_Locator find method is changing "all_discovered_feeds" from an array to an object.

The second possible problem is that it appears that SimplePie is stopping discovery after finding the first feed URL.  That page contains many links to valid feeds.

While looking through the SimplePie code, there is a regex in the Locator get_links() function - 
      preg_match('/^(http(s)|feed)?$/i', $parsed['scheme'])
that should be
      preg_match('/^(http(|s)|feed)?$/i', $parsed['scheme'])
to correctly handle both http and https.  This is a problem but it is not causing the behavior I'm seeing.

**Comment by szabacsik** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  andras.szabacsik@gmail.com
    Domain szabacsik.hu has exceeded the max emails per hour (56/50 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:34374 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by hardcube.23net.hu with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dPM7E-003e11-8O
	for andras@szabacsik.com; Mon, 26 Jun 2017 06:59:12 +0200
Date: Sun, 25 Jun 2017 21:58:31 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1498453111;
	bh=fM+bLiAjG2LUc+CPy6Ebuy6JdnzDV1sK/AqZeYnYNtk=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Cs5yZMiMWiQO70b0Szplpv6iKwrFgIgGKi5nmSpMO+qtdIkYn3s+h3seALBVj7UZe
	 PBbcALNTIllSAejAmzX9ynDzeLifXRAEVUwFO4OeI6RCMu6WkSqhSEgUqTsILWFOp0
	 Fqodl350vjyAhzZNoXRm/A70CHS1F+J0h3Hs5QL8=
