### ISSUE TITLE
get_image_link()

### ISSUE THREAD

**Issue by drocks13** [simplepie/simplepie#299]
It appears that get_image_link() or any of the get_image do not work in the latest version. They appear to return nothing. I even tried the example at http://simplepie.org/wiki/reference/simplepie/get_image_url and it returns nothing-

$feed = new SimplePie();
$feed->set_feed_url('http://simplepie.org/blog/feed/');
$feed->init();
$feed->handle_content_type();

echo '<a href="' . $feed->get_image_link() . '" title="' . $feed->get_image_title() . '">';
echo '<img src="' . $feed->get_image_url() . '" width="' . $feed->get_image_width() . '" height="' . $feed->get_image_height() . '" />';
echo '</a>';

Different rss urls and different rss feed providers e.g. blogger, wordpress, etc.

None appear to return anything.

**Comment by szabacsik** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  andras.szabacsik@gmail.com
    Domain szabacsik.hu has exceeded the max emails per hour (55/50 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:33512 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by hardcube.23net.hu with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dPM77-003e0m-J9
	for andras@szabacsik.com; Mon, 26 Jun 2017 06:59:05 +0200
Date: Sun, 25 Jun 2017 21:58:24 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1498453104;
	bh=mFAs40plzL6gquLamKudE2Ynvx0sK6aqg/joj4vBncE=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=IuO9DiBwoWQlxZuvTk8MYK0/BB8Ia7uRSmSY23e1WJCgDhKiZ17OMt8N6hqVYe9LW
	 BTeQnLCmXa5ARuHw5FtbmoBiPpqOGeA2vaXhduchJguJ6dHfTjZG+rVYgBpq9B59b/
	 E71i7zyHuYSyCcB4MUDckCG4MiIEtsgRmCDlJ7vA=
