### ISSUE TITLE
$feed->set_output_encoding('UTF-8') doesn't affect $item->get_content();

### ISSUE THREAD

**Issue by Ali-007** [simplepie/simplepie#304]
I'm using this great class for part of my client website. I found out that when I set UTF-8 output encoding, feed item's contents doesn't take affect.

I've tested on some Persian language feeds, but all of them had this issue.
It seems that only $item->get_content() have this bug and $item->get_title() works fine.

Here is a RSS link in Persian language for your reference: http://feeds.narenji.ir/narenji

You can use SimplePie sample for set_output_encoding() and see It's real output by viewing source code of page for both RSS feed and parsed one. The first is UTF-8 encoded, but SimplePie output is HTML encoded (Just for $item->set_output_encoding().)

For example, This is RSS content and expected UTF-8 encoded output string:
این کنسول بازی را به یاد می آورید؟
But here is the SimplePie output:
&#1575;&#1740;&#1606; &#1705;&#1606;&#1587;&#1608;&#1604; &#1576;&#1575;&#1586;&#1740; &#1585;&#1575; &#1576;&#1607; &#1740;&#1575;&#1583; &#1605;&#1740; &#1570;&#1608;&#1585;&#1740;&#1583;&#1567;

You can see that page's size dramatically increases by 3x times of UTf-8 encoded data, also, there is no way to save & search data in database..
Is there a way to fix this issue in an standard way and not using html_entity_decode()?
Client's website is in final steps to be published and I can't ask for more time from them.

Any help can be great.

Regards,
Ali H.

**Comment by mohammadzzz** [comment]
I have the same problem and can't find my answer ....

**Comment by mohammadzzz** [comment]
actually, after some digging, found this ....maybe help u

after getting your content, do this:
`$content = html_entity_decode($item->get_content(), ENT_QUOTES, 'UTF-8');`
it fixed my problem....may help others as well

**Comment by szabacsik** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  andras.szabacsik@gmail.com
    Domain szabacsik.hu has exceeded the max emails per hour (54/50 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:62976)
	by hardcube.23net.hu with esmtps (TLSv1:DHE-RSA-AES128-SHA:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-d5b6-andras=szabacsik.com@sgmail.github.com>)
	id 1dPM74-003e0K-1K
	for andras@szabacsik.com; Mon, 26 Jun 2017 06:59:02 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=A4eyMjXOjf9imlTiE8OYL/Pwm1A=; b=IEOq94JVvSy/wXbF
	FM6OneSNvg4mygNJitant8wDCbhH/2zzH1xuAljTQum+J/p4yy+aZUUKCb2i5mXy
	uhTp26B63nbmcHbxR5C1dBWJVARt7R1B+kvchOLywx6oPgOKx4/FFKn6a8Mi2kzG
	KFK3GiRYGEN2iyTkKBGpEdkdIrU=
Received: by filter0591p1mdw1.sendgrid.net with SMTP id filter0591p1mdw1-27022-5950946B-4
        2017-06-26 04:58:19.060885784 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id scwxQAmVTMSTiDLoisQRow
	for <andras@szabacsik.com>; Mon, 26 Jun 2017 04:58:19.003 +0000 (UTC)
Date: Sun, 25 Jun 2017 21:58:18 -0700
