### ISSUE TITLE
SimplePie->strip_htmltags() throws a huge error if even one description/content is empty

### ISSUE THREAD

**Issue by CyanPrime** [simplepie/simplepie#305]
So I'm getting the error 

Catchable fatal error: Argument 1 passed to DOMNode::replaceChild() must be an instance of DOMNode, null given, called in mysite.com/simplepie_1.3.1.mini.php on line 1059 and defined in mysite.com/simplepie_1.3.1.mini.php on line 12439

When I try to run my page, and I've figured out that it's due to a post on the feed of one of the websites it's pulling from with no text, just a image (It's a tumblr post). I could do a check of like "if description/content equals null: don't do anything. Else: replace html tags." but there is no way to get/check items in the feed before init()ing the feed.  So the fix I propose is a simple if statement in the sript_htmltags() method saying "if this post's content/description are empty don't do anything."

Thank you for your time.

**Comment by szabacsik** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  andras.szabacsik@gmail.com
    Domain szabacsik.hu has exceeded the max emails per hour (53/50 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:3900)
	by hardcube.23net.hu with esmtps (TLSv1:DHE-RSA-AES128-SHA:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-d5b6-andras=szabacsik.com@sgmail.github.com>)
	id 1dPM6s-003dyn-5J
	for andras@szabacsik.com; Mon, 26 Jun 2017 06:58:50 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=S8eUzh+K7CCu3y+o6sPgktoZvJs=; b=Htj91UZ24c36BuAI
	Vjklzw/Tbl1qk0QQregw0lrq9HQ+7MMyDFdAbg1eAG2KvGgIahpO238SLrW4ELSv
	WpVBg4KTi/0d3palU8LlaN9IaehFcQHHSF78iWQSgq7nmGCV/bX8xaqDRJhDCH4l
	ymMjLfnf/rMX7XzzY2HNeuq6aFw=
Received: by filter0539p1mdw1.sendgrid.net with SMTP id filter0539p1mdw1-25225-5950945F-C
        2017-06-26 04:58:07.344386925 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id _piqa4s8SuGFsTi_cGroeg
	for <andras@szabacsik.com>; Mon, 26 Jun 2017 04:58:07.348 +0000 (UTC)
Date: Sun, 25 Jun 2017 21:58:07 -0700
