### ISSUE TITLE
set_image_handler() will cause Fatal Error "Cannot use object of type DOMElement as array"

### ISSUE THREAD

**Issue by CBeerta** [simplepie/simplepie#307]
Using `set_image_handler('image', 'i');` to Set an Image Url results in a Fatal error:

```
PHP Fatal error:  Cannot use object of type DOMElement as array in /home/claus/www/Bliss/php/vendor/simplepie/simplepie/library/SimplePie/Sanitize.php on line 317
PHP Stack trace:
PHP   1. {main}() /home/claus/www/Bliss/php/simplepie_test.php:0
PHP   2. SimplePie_Item->get_content() /home/claus/www/Bliss/php/simplepie_test.php:13
PHP   3. SimplePie_Item->sanitize() /home/claus/www/Bliss/php/vendor/simplepie/simplepie/library/SimplePie/Item.php:390
PHP   4. SimplePie->sanitize() /home/claus/www/Bliss/php/vendor/simplepie/simplepie/library/SimplePie/Item.php:182
PHP   5. SimplePie_Sanitize->sanitize() /home/claus/www/Bliss/php/vendor/simplepie/simplepie/library/SimplePie.php:1978
```

Here is some example code: 

```
<?php
require_once 'vendor/simplepie/simplepie/autoloader.php';

$feed = new SimplePie();
$feed->set_cache_location('data/cache');
$feed->set_image_handler('image', 'i');

$feed->set_feed_url('https://github.com/simplepie.atom');
$feed->init();
$feed->handle_content_type();

foreach ($feed->get_items() as $feed_item) {
    print $feed_item->get_content();
}
```

**Comment by szabacsik** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  andras.szabacsik@gmail.com
    Domain szabacsik.hu has exceeded the max emails per hour (51/50 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:19739)
	by hardcube.23net.hu with esmtps (TLSv1:DHE-RSA-AES128-SHA:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-d5b6-andras=szabacsik.com@sgmail.github.com>)
	id 1dPM6C-003dYc-0A
	for andras@szabacsik.com; Mon, 26 Jun 2017 06:58:08 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=jchKMf58pEUhT5Yk8E2RkEcG0BQ=; b=fe7ZWoNQAEzBUcHI
	F1o99k6OjHO5FZPnOZIF6X4nxY/yUxf2tN3MGvQlNFs7oAIt8AzsImVJlBPQ923M
	gTXYPU+D2uBiPxu+OEJHZw4rkEVc8/uJUJ4QRRlHoycdSc1oVVl/MXtSqsy1K/C/
	zpLUpbtyCjryFRPiEjvYAd2eH7U=
Received: by filter0957p1mdw1.sendgrid.net with SMTP id filter0957p1mdw1-8243-59509435-F
        2017-06-26 04:57:25.549622064 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id xpZq5mZFTxuUZOORQlhzEg
	for <andras@szabacsik.com>; Mon, 26 Jun 2017 04:57:25.529 +0000 (UTC)
Date: Sun, 25 Jun 2017 21:57:25 -0700
