### ISSUE TITLE
Issue with feed item URLs

### ISSUE THREAD

**Issue by jgalea** [simplepie/simplepie#317]
I'm encountering an issue with SimplePie, and am wondering if you have a solution for this.

The issue we are encountering is related to feed item URLs.
Consider the below code:

$feed = new SimplePie();
$feed->set_feed_url( $feed_url );
$feed->init();
$feed->get_items()

Up calling $feed->get_items(), the items in the array returned have their URLs stripped of their query strings.
For instance, the URL 'http://somesite.com/some/path?some=query&more=query', is truncated to become 'http://somesite.com/some/path'.

Can this truncation be avoided so that the feed items retain their original, full URL ?

We have check the pct_encoding in the set_query() function (IRI.php) as pointed out by various other users, and it should accept query string characters, such as '?','&' and '='.

We are using WordPress SimplePie v1.3.1

**Comment by EvanHerman** [comment]
This is still an issue that I am facing.
