### ISSUE TITLE
 Class 'SimplePie_Cache_DB' not found

### ISSUE THREAD

**Issue by jinwyp** [simplepie/simplepie#323]
same issue  https://github.com/simplepie/simplepie/issues/231

still have this problem on 1.4-dev   on PHP 5.4.16

Message:

Class 'SimplePie_Cache_DB' not found

Location:

C:\work\github\laravel3\bundles\rssparser\libraries\simplepie\simplepie.php on line 9513

**Comment by ifsnop** [comment]
Merged in https://github.com/simplepie/simplepie/commit/6f76136cc0d531d985e1439f7915b985f4bb9087
