### ISSUE TITLE
get_source() returns null

### ISSUE THREAD

**Issue by iko3** [simplepie/simplepie#333]
I'm trying to get a source for my RSS item but simplePie returns Null when I'm calling get_source() on my item.

**Comment by jordan314** [comment]
I had this issue too. If the format is
````<source>Article Source</source>````
then get_source() returns "Article Source", but if the format is
````<source url="http://www.example.com">Article Source</source>````
then get_source returns null. I ended up using https://github.com/dg/rss-php instead.
