### ISSUE TITLE
Autodiscovery doesn't autodiscover

### ISSUE THREAD

**Issue by loyalj** [simplepie/simplepie#336]
Using this simple sample file: http://terraform.in/target/  I am trying to autodiscover a feed held inside an <a> tag.  According to this document (referenced from the simple pie docs)  

http://web.archive.org/web/20110607232437/http://diveintomark.org/archives/2002/08/15/ultraliberal_rss_locator

According to this points 3, 4, 5 should probably find the link.  Yet.. nothing.  

Only having a valid RSS at the link, or using the LINK rel tags will an RSS feed be discovered.  What gives?

**Comment by mblaney** [comment]
hi @loyalj that link 404's now, please reopen if you still have a problem
