### ISSUE TITLE
Unable to parse a feed with a questionmark (?) in the feed URL, no errors or hints given

### ISSUE THREAD

**Issue by nekohayo** [simplepie/simplepie#341]
Hi there,
I spent a fair amount of time trying to figure out why pointing simpleparser's demo/samples at Planet Pitivi didn't work... then I realized it works if pointed at Planet GNOME.

So this doesn't work (get_items() will get you just "Array", and nothing will happen in the foreach loop):

```
$feed->set_feed_url("http://www.pitivi.org/planet/?type=atom10");
```

But this does:

```
$feed->set_feed_url("https://planet.gnome.org/atom.xml");
```

**Comment by mblaney** [comment]
@nekohayo this appears to be fixed now. Please try with the latest version of SimplePie.
