### ISSUE TITLE
You are ignoring rel="self"

### ISSUE THREAD

**Issue by zharben** [simplepie/simplepie#349]
In the last several hours, our website has received about 6000 requests to the same page from someone using your RSS reader.

It appears the reader is ignoring the rel="self" attribute that we include on some RSS items.

To address the problem, we are blocking your user agent.  

You should fix this - it makes you look like a DDoS tool!!!

**Comment by plaidfluff** [comment]
This might not be a problem with SimplePie itself, but with a program making use of SimplePie and doing something incorrectly. SimplePie is just a library.

Unfortunately, it sounds like whomever wrote the software didn't bother to override the user-agent.
