### ISSUE TITLE
Use PHP 5.3's new DateTime::createFromFormat method to parse date

### ISSUE THREAD

**Issue by rmccue** [simplepie/simplepie#35]
_Originally reported by Anonymous as [issue 141](http://bugs.simplepie.org/issues/show/141)_

PHP 5.3 included a new, interesting method in the DateTime class: createFromFormat
Basically, it does the exact opposite of date(): given a string and a format, it returns the timestamp.
I believe this method is much faster than the actual SimplePie_Parse_Date class, and could be use instead of it if the server is running 5.3+.

**Comment by szabacsik** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  andras.szabacsik@gmail.com
    Domain szabacsik.hu has exceeded the max emails per hour (50/50 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:14660)
	by hardcube.23net.hu with esmtps (TLSv1:DHE-RSA-AES128-SHA:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-d5b6-andras=szabacsik.com@sgmail.github.com>)
	id 1dPMFo-003hpC-Nv
	for andras@szabacsik.com; Mon, 26 Jun 2017 07:08:05 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=7L48q/HS89Vgb1sm5/7dTYiaClM=; b=f4Yld2/B/kZF47od
	egn9/jenbozXGMblufsHrgf2IrNs3fTGsQ4NA0c7lBNFXFoIZNtGcai+eeIm5Tf0
	di6u3hfzTq5HeNGWnwNMV3fRJPKaZd/hMFYJBEXNU6fjVxixbywypt/rRIPB0fg9
	TZK7RUvcnYp7DUzx2gFPDPQnJZA=
Received: by filter1152p1mdw1.sendgrid.net with SMTP id filter1152p1mdw1-11331-5950968A-7
        2017-06-26 05:07:22.231397406 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id 5yH82G_PTummaNCherTf1w
	for <andras@szabacsik.com>; Mon, 26 Jun 2017 05:07:22.238 +0000 (UTC)
Date: Sun, 25 Jun 2017 22:07:22 -0700
