### ISSUE TITLE
Simplepie : Facebook titles are displayed with escape codes

### ISSUE THREAD

**Issue by MReynaud** [simplepie/simplepie#350]
Hi all,

I used Simplepie 1.3.1 on my website, I need to display a newsfeed from a facebook page in french language, and all the accentuated characters are escaped.
I tried my RSS feed on the Simplepie test page and it behaved the same way: 
The RSS used is : 
http://www.facebook.com/feeds/page.php?format=atom10&id=160190057366256
, so you'll be able to see what I mean (at second and third titles in the feed) does anyone have an idea of some corrections (css modifying the title?,,,) I could implement to work it around?
Thanks

**Comment by Alkarex** [comment]
https://github.com/simplepie/simplepie/pull/400

**Comment by mblaney** [comment]
hi @MReynaud I couldn't access that link to test. Please try the latest version of SimplePie and reopen if there's still a problem.
