### ISSUE TITLE
Can't read NYTimes feed

### ISSUE THREAD

**Issue by hallcp276** [simplepie/simplepie#355]
I can't get this feed to load in Simplepie, but it works fine in magpie. I tried the force_feed() option but got:

This XML document is invalid, likely due to invalid characters. XML error: SYSTEM or PUBLIC, the URI is missing at line 1, column 48

I can't see anything wrong with this feed, and it works fine in Outlook and Firefox.

Does anyone have any ideas?

Thanks,

**Comment by ifsnop** [comment]
Working ok in latest SimplePie version c78d40100758a39cb2a634a4db66b4557699b845. Maybe there was a forbidden character in rss feed?
