### ISSUE TITLE
Strip ASCII control codes (I don't know how to do a pull request)

### ISSUE THREAD

**Issue by jeffmikels** [simplepie/simplepie#370]
At line 1294, I added the following code because some of my feeds (from feedburner) had \x05 in them:

                // added by Jeff Mikels to remove stupid control codes from invalid XML feeds
                for ($jeff_control_code = 0; $jeff_control_code < 32; $jeff_control_code++)
                {
                        if ($jeff_control_code == 10 || $jeff_control_code == 13) continue;
                        $this->raw_data = str_replace(chr($jeff_control_code),'',$this->raw_data);
                }

**Comment by mblaney** [comment]
hi @jeffmikels please check if this is still a problem in the latest version of SimplePie.
