### ISSUE TITLE
Unable to add feed: A feed could not be found

### ISSUE THREAD

**Issue by monreal** [simplepie/simplepie#373]
I am trying to add the feed [1] to ownCloud news, which is using simplepie under the hood. The feed is detected in Firefox, but it does not work in the simplepie demo [2], either:

---
A feed could not be found at http://maniacsvault.net/feed.rss
---

[1] http://maniacsvault.net/feed.rss
[2] http://simplepie.org/demo/?feed=http%3A%2F%2Fmaniacsvault.net%2Ffeed.rss

**Comment by Alkarex** [comment]
https://github.com/simplepie/simplepie/pull/396

**Comment by ifsnop** [comment]
Merged and fixed in https://github.com/simplepie/simplepie/commit/8b6f1e1f4881cf3e096a339c357ca563dfe7f74a
