### ISSUE TITLE
UTF-8 Error with Temple RSS URL (Simplepie Demo doesn't work either)

### ISSUE THREAD

**Issue by mkaply** [simplepie/simplepie#375]
We're getting the "data could not be converted to UTF-8" error with this URL:

http://www.owlsports.com/rss.aspx

It also doesn't work on the demo:

http://simplepie.org/demo/?feed=http%3A%2F%2Fwww.owlsports.com%2Frss.aspx

I'm at a loss as to exactly what the problem is...

**Comment by mblaney** [comment]
hi @mkaply this feed appears to be working now. Please try with the latest version.

**Comment by mkaply** [comment]
Looks good to me.
