### ISSUE TITLE
will upgrading make google calendar for joomla 1.5x work again?

### ISSUE THREAD

**Issue by LWAA** [simplepie/simplepie#384]
I have two websites that still use Joomla 1.5x and Calendar component for showing upcoming events - they're now broken with the attached error on the modules and blank calendars
![screen shot 2014-11-27 at 27 nov 08 20 02 am](https://cloud.githubusercontent.com/assets/1640445/5217434/489d9966-760e-11e4-97e6-c284447975f2.jpg)
Will upgrading SimplePie fix this? The Calendar component is no longer available and they only offer a 2.5+ option, so I really want to keep using this if I can (clients are non profits and can't afford to pay anyone to upgrade them to Joomla 2.5+)

**Comment by mblaney** [comment]
please reopen if you still have a problem
