### ISSUE TITLE
New release / tag ?

### ISSUE THREAD

**Issue by j0k3r** [simplepie/simplepie#390]
The last tag was on 2012, it would be cool if you can tag a new release :)

**Comment by Ilyes512** [comment]
+1

**Comment by talgalili** [comment]
+1

**Comment by Narno** [comment]
:+1:

**Comment by awjudd** [comment]
:+1:

**Comment by danpoltawski** [comment]
+1

**Comment by mmcdole** [comment]
Why have there been no new releases?

**Comment by samwilson** [comment]
+1

**Comment by j0k3r** [comment]
ping @rmccue

**Comment by mblaney** [comment]
A question for someone who's done this before.... what's the process of putting out say a 1.3.1 tag when all the file headers have version 1.4-dev written in them?

**Comment by j0k3r** [comment]
Just remove that useless `@version` header from each file?
And update the version in the few one that left in:

- library/SimplePie.php
- compatibility_test/sp_compatibility_test.php

**Comment by mblaney** [comment]
ok I think there's been enough improvements to warrant a 1.4 version, so I think I'll just remove the -dev (and remove @version from most files to decrease maintenance). chime in if you have an opinion on the matter.

**Comment by ifsnop** [comment]
It is time for a new version!

**Comment by j0k3r** [comment]
If you plan to release 1.4 maybe you should first release a 1.4.0-beta0 because there are a lot of changes since October 2012. So let some users test 1.4.0 beta before release it.

**Comment by mblaney** [comment]
1.4-beta is now available, I'll release 1.4 in a couple of weeks. Please let me know if you have any feedback before then.

**Comment by j0k3r** [comment]
Just tested on 4 projects and no regression at all. :+1:
