### ISSUE TITLE
Invalid characters in dc:creator

### ISSUE THREAD

**Issue by Rasmis** [simplepie/simplepie#392]
##### Problem
Recently an increasing number of feeds are using *invalid characters* in the **dc:creator** tag. Specifically when the author has a non-English name, e.g. Stéphanie. Somewhere in the creation of the feed, a poorly written app translates this to `<dc:creator>St&eacute;phanie</dc:creator>`.

Unfortunately this renders the entire XML document invalid, and SimplePie can't handle it, before the **one** post with **one** invalid tag is pushed from the feed.

##### Proposed solution
I know the problem is caused by a third party using bad software, but could we not make a fall-back for SimplePie, where it tries to `html_entities_decode()` the contents of the guilty tag, before collapsing?

Has anybody tried a quick-fix? E.g. stripping tags from feeds, before serving them to SimplePie?

##### Error code
`This XML document () is invalid, likely due to invalid characters. XML error: not well-formed (invalid token)`

##### To replicate
Try parsing http://feeds.feedburner.com/Ikeahacker

**Comment by Alkarex** [comment]
Could you please give a try to https://github.com/simplepie/simplepie/pull/400 ?

**Comment by mblaney** [comment]
hi @Rasmis this looks ok to me now, please try again with the latest version.
