### ISSUE TITLE
Error HTTP/406

### ISSUE THREAD

**Issue by samdolt** [simplepie/simplepie#393]
http://fablab-neuch.ch/feed/atom/ don't work with simplepie:

![picture](https://cloud.githubusercontent.com/assets/6305913/6604121/b1224b52-c826-11e4-9ead-cb6757af14f4.png)
![freshrss](https://cloud.githubusercontent.com/assets/6305913/6604239/7010b896-c827-11e4-8db4-feb7453003b1.png)

But this is a valid Atom 1.0 feed:
http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Ffablab-neuch.ch%2Ffeed%2Fatom%2F

**Comment by samdolt** [comment]
This server block SimplePie user agent.

**Comment by niol** [comment]
For better error reporting, I've been using the following patch for a while.

```diff
--- a/libs/SimplePie.php
+++ b/libs/SimplePie.php
@@ -6844,6 +6844,7 @@ class SimplePie_File
                                curl_setopt($fp, CURLOPT_URL, $url);
                                curl_setopt($fp, CURLOPT_HEADER, 1);
                                curl_setopt($fp, CURLOPT_RETURNTRANSFER, 1);
+                               curl_setopt($fp, CURLOPT_FAILONERROR, 1);
                                curl_setopt($fp, CURLOPT_TIMEOUT, $timeout);
                                curl_setopt($fp, CURLOPT_CONNECTTIMEOUT, $timeout);
                                curl_setopt($fp, CURLOPT_REFERER, $url);

```
