### ISSUE TITLE
FEATURE REQUEST: curl option CURLOPT_SSL_VERIFYPEER

### ISSUE THREAD

**Issue by JoeB99** [simplepie/simplepie#405]
Can you please add a config option for CURLOPT_SSL_VERIFYPEER ?

In File.php, on line Line 101 i've had to add:

curl_setopt($fp, CURLOPT_SSL_VERIFYPEER, false);

In-order to get the class to work with my feed.

**Comment by Alkarex** [comment]
See https://github.com/simplepie/simplepie/pull/407

**Comment by ifsnop** [comment]
Closed in #407, as Alkarex said.
