### ISSUE TITLE
support for http authentication

### ISSUE THREAD

**Issue by johnbabu** [simplepie/simplepie#409]
Some website are having http authentication. Feed from that urls are not showing up with simplepie.
For example to fetch the feeds from that url via curl request the cmd will be 
'curl "http://<username>:<password>@www.testdomain.com/blog/feed/"'

If we try the same url as feed url in simplepie the results are empty. Is there any fix available for this?

**Comment by mblaney** [comment]
hi @johnbabu this should work please re-open if you're still having problems.
