### ISSUE TITLE
MySQL cache

### ISSUE THREAD

**Issue by mit686** [simplepie/simplepie#413]
MAMP PHP Version 5.6.7

Getting error:

Warning: substr() expects parameter 1 to be string, array given in XXX/simplepie/library/SimplePie/Cache/MySQL.php on line 102

Notice: Array to string conversion in XXX/simplepie/library/SimplePie/Cache/MySQL.php on line 106

Warning: PDO::__construct() expects parameter 2 to be string, array given in XXX/simplepie/library/SimplePie/Cache/MySQL.php on line 106

Fatal error: Call to a member function query() on null in XXX/simplepie/library/SimplePie/Cache/MySQL.php on line 116

Anybody can help?

**Comment by rayjun** [comment]
I get the problem too!!!

**Comment by borjasanes** [comment]
I solved it with $feed->enable_cache(false);

**Comment by ifsnop** [comment]
This is probably caused by a wrong set_cache_location string. See http://simplepie.org/wiki/1.3/caching for details. Check that you are using the following construction:

~~~
$feed->set_cache_location('mysql://username:password@hostname:port/database');
~~~
