### ISSUE TITLE
Feed being a .RSS file issue

### ISSUE THREAD

**Issue by Organizer** [simplepie/simplepie#414]
I've a basic set-up with SP pulling feeds and inserting into MySQL which all works fine. However one of my feeds are an .RSS which in a browser downloads the .RSS file (which contains an RSS feed). Does not SP support this as I'm not getting it to process that?

http://www.gamestar.de/rss/gamestar.rss

**Comment by Organizer** [comment]
Got it working by using force read, though as I'm reading an array of feeds it means all of them I guess is using that value which is maybe not the best solution. This seems to validate so is there a way to tweak the core to accept the the .RSS feed without using force?

**Comment by mblaney** [comment]
Hi @Organizer this should work now, please update your version of SimplePie and try again.
