### ISSUE TITLE
SimplePie_Item::get_content() not working on a particular feed

### ISSUE THREAD

**Issue by plaidfluff** [simplepie/simplepie#417]
Hi, I'm one of the current maintainers of [Feed-On-Feeds](https://github.com/plaidfluff/Feed-on-Feeds), which uses SimplePie for its feed parsing.  A user has recently reported an issue with feed parsing which seems to originate in SimplePie.

On the feed for [The Right Coast](http://rightcoast.typepad.com/rightcoast/) (as retrieved at http://rightcoast.typepad.com/rightcoast/index.rdf), SimplePie 1.3.1 is unable to return any content using `get_content()`. I'm at a loss for what's going on here --- the other methods on `SimplePie_Item` are working fine.  This feed uses `<content:encoded>` as opposed to the more common (if incorrect) `<description>` but as far as I can tell it should be working fine, as all the namespace declarations seem to match what SimplePie expects and so on, and I don't see any tags on this feed which would be overriding the request for `<content:encoded>`.

Related issue: https://github.com/plaidfluff/Feed-on-Feeds/issues/6#issuecomment-139818948

Related code: https://github.com/plaidfluff/Feed-on-Feeds/blob/d2c50295b709399abf82c2aef4649e43703c2602/fof-main.php#L977

Thanks!

**Comment by mblaney** [comment]
hi @plaidfluff please try this again with the latest version of SimplePie, it appears to be working now.

**Comment by plaidfluff** [comment]
I just tried upgrading to the latest SimplePie (master branch), and `$item->get_content()` is still not working on the stated feed.

**Comment by mblaney** [comment]
@plaidfluff it worked for me, can you provide an error message?

**Comment by plaidfluff** [comment]
There's no error message, `get_content()` is still just returning an empty string.

**Comment by plaidfluff** [comment]
Ah, never mind, I had forgotten to update `autoloader.php` and that seems to have somehow affected this. Weird. Oh well! Anyway now other stuff is breaking post-update but it looks like this bug is closed and I just have to upgrade some FoF code again (sigh).

Thanks!
