### ISSUE TITLE
problem with rss that have <media:content

### ISSUE THREAD

**Issue by mr-shady** [simplepie/simplepie#421]
when i try to read an RSS that have  <media:content on it, simplepie doesn't work and just returns an empty array. some samples of rss that don't work:

http://www.irna.ir//fa/rss.aspx?kind=32
http://www.irna.ir//fa/rss.aspx?kind=20  
http://www.irna.ir//fa/rss.aspx?kind=212  
any body can help me with this ?
same question in stackoverflow : https://stackoverflow.com/questions/33638764/simplepie-doesnt-work-when-rss-contains-mediacontent

another question right now i'm using spimlepie 1.3.1 but  is it save to use simplepie 1.4-dev ?

**Comment by mblaney** [comment]
hi @mr-shady all those feeds work with SimplePie you just need to remove the double slash from the paths, ie: http://www.irna.ir/fa/rss.aspx?kind=32

**Comment by mblaney** [comment]
actually it works as is: http://simplepie.org/demo/?feed=http%3A%2F%2Fwww.irna.ir%2F%2Ffa%2Frss.aspx%3Fkind%3D32
