### ISSUE TITLE
Feed not comming

### ISSUE THREAD

**Issue by chetansatasiya** [simplepie/simplepie#428]
Hi Team,

I am trying to fetch RSS from http://www.brusselstimes.com/rss-feed/itemlist/?format=feed&type=rss but I am not able to get the RSS.

I have checked in W3C validator and the feed URL is valid. 

https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.brusselstimes.com%2Frss-feed%2Fitemlist%2F%3Fformat%3Dfeed%26type%3Drss

Can you please help me to fetch the RSS from this URL?

**Comment by mblaney** [comment]
Hi @chetansatasiya this should work now. Please update to the latest version of SimplePie and try again.

**Comment by chetansatasiya** [comment]
Hi @mblaney I am trying to access SimplePie feed using WordPress. But still I am not able to get the RSS. I have also checked with your demo. But still in demo feed not coming. Please check with below URL.

http://simplepie.org/demo/?feed=http%3A%2F%2Fwww.brusselstimes.com%2Frss-feed%2Fitemlist%2F%3Fformat%3Dfeed%26type%3Drss

So, you can get better idea about this. I hope you come up with proper solutions.

Thanks in Advance :)

**Comment by mblaney** [comment]
@chetansatasiya this feed works with the latest version of SimplePie. I don't have access to the website to update the demo, and the version in WordPress would not have changed yet.

**Comment by chetansatasiya** [comment]
@mblaney I have downloaded the latest version of SimplePie and the version is 1.3 but still I am not able to fetch the RSS.

It's giving me this error: This XML document is invalid, likely due to invalid characters. XML error: Mismatched tag at line 40, column 14

I have checked the XML document and it's showing me RSS XML is valid. https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.brusselstimes.com%2Frss-feed%3Fformat%3Dfeed%26type%3Drss

Can you please check again from your side? 

This is the feed URL which I have to fetch the RSS: http://www.brusselstimes.com/rss-feed?format=feed&type=rss

I hope you come up with my solution.

Thanks in advance.

**Comment by mblaney** [comment]
@chetansatasiya did you use this link to download the latest version?
https://github.com/simplepie/simplepie/archive/master.zip
