### ISSUE TITLE
Parser is truncating argument after equal sign in query string of links

### ISSUE THREAD

**Issue by zeroKFE** [simplepie/simplepie#430]
I have a bit of an odd one for you guys here.  I tried to sort through the parsing code in SimplePie_Item::get_links myself, but to no avail.

I have only been able to replicate the problem on the specific customer RSS feed that generated the request for me.  Other feeds with similar URL patterns are parsed as expected.  It's possible there is some oddly encoded or hidden characters in the feed or something screwing with the parsing, but if so, I didn't see it.

The feed in question is: 

http://www.simplifyingthemarket.com/feed/?a=165521-d3219c2d0d8853f91226b49c1982886c

It contains item tags like the following:

```
<item>
		<title>Put Your Housing Cost To Work For You!</title>
		<link>http://www.simplifyingthemarket.com/2016/03/07/put-your-housing-cost-to-work-for-you/?a=165521-d3219c2d0d8853f91226b49c1982886c</link>
		<comments>http://www.simplifyingthemarket.com/2016/03/07/put-your-housing-cost-to-work-for-you/#comments</comments>
		<pubDate>Mon, 07 Mar 2016 11:00:34 +0000</pubDate>
		<dc:creator><![CDATA[simplify]]></dc:creator>
				<category><![CDATA[First Time Home Buyers]]></category>
		<category><![CDATA[For Buyers]]></category>
		<category><![CDATA[Interest Rates]]></category>
		<category><![CDATA[Move-Up Buyers]]></category>
		<category><![CDATA[Pricing]]></category>
...
etc
```

The parser pulls the link tag out like this:

`http://www.simplifyingthemarket.com/2016/03/07/put-your-housing-cost-to-work-for-you/?a=`

missing the very important argument after the equal sign in the query string.

**Comment by ifsnop** [comment]
After testing, SimplePie is working correctly. First link I'm getting:
~~~
http://www.simplifyingthemarket.com/en/2016/03/15/gap-between-homeowners-appraisers-opinions-widen/?a=
165521-d3219c2d0d8853f91226b49c1982886c
~~~
Could you provide another example?

But I have to change the user agent string that curl uses, because site is blocking SimplePie.
~~~
$feed->set_curl_options(
                array(CURLOPT_USERAGENT => "")
        );
~~~

**Comment by mblaney** [comment]
I had a look at this before all the recent updates, it didn't work then but I've just tried it again and can also see that it's working now.
