### ISSUE TITLE
cache not working on Linux OS

### ISSUE THREAD

**Issue by advoloastra** [simplepie/simplepie#438]
I am using SimplePie 1.3.1, Build 20121030175403 on multiple versions of Linux (Centos7, Ubuntu 14.05 and Amazon Linux AMI (Centos)). The cache folder never populates and I have given it full (777) permissions. I have no problems when I run it in a LAMP stack on Windows.

**Comment by mblaney** [comment]
@advoloastra what's the error message?

**Comment by advoloastra** [comment]
@mblaney there is no error message. I never see any files in the cache folder on a linux machine.

**Comment by mblaney** [comment]
@advoloastra if there's no error message then you need to work out why $cache->save() isn't being called. There are lots of reasons why that might be the case.

**Comment by CharlesWiltgen** [comment]
(Newbie question: Can this be closed, then?)

**Comment by mblaney** [comment]
Hi @CharlesWiltgen sure, I'll close this and @advoloastra can re-open if they have any more to add. Thanks for your offer to help with SimplePie!
