### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by JanPetterMG** [simplepie/simplepie#443]
Is PHP 7 support realistic?
http://php.net/supported-versions.php

There is currently 4 errors, 3 of them most likely due to the same port-number bug...
https://travis-ci.org/simplepie/simplepie 

---

_The coding standards used are way outdated, and with files counting 3.000+ lines, isn't making the job of fixing it easier either. Normally I'm trying to contribute instead of posting issues, but that's not realistic in this case... sorry!_

_**2.0:** Start the refactoring process, update the standards, replace old bunks of code with external maintained repositories, less code, fewer bugs, better support. Then it would be easier for everyone, also it will making sure this repository doesn't get out of date! Because who are using php 5.3 today??_

**Comment by shaildyp** [comment]
PHP7 works for me but the the encoding parser keeps failing. I have both mbstring & iconv available.

`PHP Notice: The data could not be converted to UTF-8. You MUST have either the iconv or mbstring extension installed. Upgrading to PHP 5.x (which includes iconv) is highly recommended.`

**Comment by idealley** [comment]
it also works for me with php 7 on vagrant/homestead

**Comment by thinkingmedia** [comment]
I'm going to be running it on 7. If I see anything that needs fixing. I'll make a PR for it.

**Comment by JanPetterMG** [comment]
Is backwards compatibility required at all cost? (there was an unspecified comment about this before 1.4 was released).
Is a ``2.0-dev`` branch possible?

3 of the issues are probably due to bugs in the [SimplePie_IRI class](https://github.com/simplepie/simplepie/blob/master/library/SimplePie/IRI.php). `1262 lines (1182 sloc)  28.1 KB`

I _might_ rewrite it, but then it has to be from scratch !!! The current class is very complex, are using outdated standards, and could be simplified a lot.

For example, the `replace_invalid_with_pct_encoding()` function with it's 275 lines, can be replaced with just 2 lines, still doing the exact same job... Solution: ``preg_replace`` + ``array`` + ``rawurlencode``

**Comment by mblaney** [comment]
I think keeping backwards compatibility was suggested because SimplePie is included in Wordpress. It should be kept unless there's a really good reason not too, if that ever happens I would be open to a 2.0-dev branch, maintained in parallel.

**Comment by JanPetterMG** [comment]
@shaildyp I also get that error, but on PHP 5.6.20, even if I have ``UConverter``, ``iconv`` and ``mbstring`` installed, so it can't be PHP 7 specific...

If I'll set the encoding to UTF-8 in cases where the HTTP header isn't specifying any encoding (as fallback), the error shows up rather frequently.
If I'll skip ``set_input_encoding`` in such cases, the error disappears, and the feed is parsed successfully.

[set_input_encoding](http://simplepie.org/wiki/reference/simplepie/set_input_encoding) documentation:
> The character encoding to use instead of allowing SimplePie to auto-detect it.

**Comment by skyzyx** [comment]
The canonical answer is that @rmccue is a developer on WordPress, and was the maintainer of SimplePie for a number of years after @gsnedders and I got burned out. For him, it was important that SimplePie 1.x maintain backwards compatibility.

If SimplePie 1.x adheres to semantic versioning (which came around after I retired from SimplePie), then we should maintain backwards compatibility in the API (even if we drop older PHP versions). Having said that, I think that it's OK to do a 2.0 fork of the SimplePie codebase which breaks compatibility in order to fix some things, but we should be responsible about messaging BC breaks.

**Comment by jhabdas** [comment]
> I think keeping backwards compatibility was suggested because SimplePie is included in Wordpress.

WordPress themselves now suggest to use PHP 7.0 or better. Sure some old sites use it. They can also use an older version of SimplePie - that's WP Core teams choice.

**Comment by alexlopezit** [comment]
I have recently upgraded from PHP 5 to 7.1 and had a problem with SimplePie not working, so I came across this issue, I also found that I was missing the xml parser module, so I leave this here in case it happens to someone else.

`sudo apt-get install php-xml`

This fixed it for me.

**Comment by johngrant4est** [comment]
I have two identical scripts, one running on PHP 7.1, the other on PHP 7.2. Former works, latter doesn't. No output in terms of errors, curl -v retrieves the URI ok, I have all the required PHP libraries installed.
Any thoughts, or ideas on how I can debug ?

**Comment by danwie** [comment]
I updated to PHP 7 yesterday and have the same problem as @johngrant4est above. No output in terms of errors, curl -v retrieves the URI ok. curl_exec() also retrieves the URI.

phpinfo() says nothing about php-xml. Is this this module required? If yes, why isn't there any error if module is not available?

**Comment by dnagyelek** [comment]
SimplePie is using the PHP XML module, so you have to have it.
For PHP 7.2/Ubuntu use:
sudo apt install php7.2-xml

**Comment by mblaney** [comment]
SimplePie has been working with PHP 7 for a while now thanks to a number of patches that have been merged.
