### ISSUE TITLE
One Wordpress blog not recognized

### ISSUE THREAD

**Issue by JorisDebonnet** [simplepie/simplepie#446]
SimplePie works fine for my English and Dutch blog, but not for the French one. Can't figure out why! I updated to version 1.4, but that did not make a difference. `(new SimplePie($url))->get_items()` returns an empty array.

https://overfunkytime.wordpress.com/feed/  <== works (nl)
https://aboutfunkytime.wordpress.com/feed/  <== works (en)
https://surfunkytime.wordpress.com/feed/  <= does not work (fr)

Those feeds look like they have exactly the same format. What might be causing the issue?

**Comment by mblaney** [comment]
@JorisDebonnet if you turn on all errors you will see this notice: Invalid character at line 199, column 31

**Comment by JorisDebonnet** [comment]
Ahh, I did not know about the error function... Thank you! 

I wouldn't have expected a character in a CDATA block to cause any issues, but that's exactly what happened. An old post from 2012 contained several weird characters for some reason. I guess WordPress should have filtered them out for the RSS feed. Or even never saved them at all, but it might be an old corruption in their DB.
