### ISSUE TITLE
Simplepie in Laravel 5

### ISSUE THREAD

**Issue by ken3d06** [simplepie/simplepie#447]
I am using laravel 5, I did composer require simplepie/simplepie

but i am getting a Class 'App\Http\Controllers\SimplePie' not found

I assume I am supposed to add it  in the app/config providers and aliases as well,
what exactly should I add.

**Comment by droplister** [comment]
Add "use SimplePie" before your class on the controller:

```

use SimplePie;

class FeedController extends Controller
{
        $feed = new SimplePie();
}

```

**Comment by ken3d06** [comment]
Thanks a million
