### ISSUE TITLE
SimplePie doesn't work on a specific feed

### ISSUE THREAD

**Issue by stoto34** [simplepie/simplepie#448]
Hi,

I'm using SimplePie to check many feeds but I found an error for one of them : http://www.sports.fr//fr/cmc/football/rss.xml

When I try to check it, I have this error : **cURL error 6: Couldn't resolve host 'http'**

But the feed is online and he seems to work (no error). I try to debug SimplePie library and I found something weird when I var_dump data in fix_protocol function (Misc class, line 197) :+1: 

url = http://www.sports.fr//fr/cmc/football/rss.xml
url = **http//?#**

Why I get this second url ? Is there an issue ?

Thank you,
Syl

**Comment by ifsnop** [comment]
Could you try changing the double / with only one? Looks like a malformed
url.

**Comment by stoto34** [comment]
Thank you for your quick answer but I already did it before to post here. Unfortunately, it didn't work : both url are good. Another idea ? :disappointed:

**Comment by JanPetterMG** [comment]
[Works just fine in the v1.3 demo](http://simplepie.org/demo/?feed=http%3A%2F%2Fwww.sports.fr%2F%2Ffr%2Fcmc%2Ffootball%2Frss.xml)
May this be an v1.4 issue?

What PHP version are you running? I know the [SimplePie_IRI](https://github.com/simplepie/simplepie/blob/master/library/SimplePie/IRI.php) class has issues with PHP 7, might this be another one?

**Comment by mblaney** [comment]
works fine in 1.4 too, but only without the extra slash. @stoto34 what version of SimplePie are you using? What is the error message you see with the correct url?

**Comment by stoto34** [comment]
Hi :)

I use SimplePie 1.4. My version of PHP is : 5.4
I maybe found something in "is_valid" function in IRI.php. When I comment this part : 

**substr($this->ipath, 0, 2) === '//'**

The feed is good. I would like know what is the purpose of this test ?

Thank you,
Syl

**Comment by mblaney** [comment]
It's implementing the spec. see: https://tools.ietf.org/html/rfc3986#section-3.3

**Comment by phluid61** [comment]
@mblaney which part of the spec? The relevant parts I can see are:

      URI         = scheme ":" hier-part [ "?" query ] [ "#" fragment ]

      hier-part   = "//" authority path-abempty  ; << this one
                  / path-absolute
                  / path-rootless
                  / path-empty

      authority   = [ userinfo "@" ] host [ ":" port ]

      path-abempty  = *( "/" segment )

      segment       = *pchar

(and [RFC 7230](https://tools.ietf.org/html/rfc7230#section-2.7)):

     http-URI = "http:" "//" authority path-abempty [ "?" query ]
                [ "#" fragment ]

... which means that `http://www.sports.fr//fr/cmc/football/rss.xml` is a valid URI, even with a blank first path segment.

Is this the bit you're enforcing?

> If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//").

If so, that's not relevant here, because the URI in question **does** contain an authority component; and in fact it's impossible for a HTTP URI not to.

**Comment by mblaney** [comment]
interesting, looks like you're right @phluid61. I didn't write the code, but obviously whoever did has read the line you've quoted the same way. thanks for looking into it!

**Comment by mblaney** [comment]
fixed
