### ISSUE TITLE
strpos offset error

### ISSUE THREAD

**Issue by albertleao** [simplepie/simplepie#449]
I have simplepie running on a cron job and I'm getting error reports everytime it runs with the following error:

`Severity: Warning --> strpos(): Offset not contained in string var/www/vendor/simplepie/simplepie/library/SimplePie.php 1616`

I am using composer and pulling from dev-master

**Comment by mblaney** [comment]
thanks will look into it (and realise it's not the first time this has been mentioned).

**Comment by ffelixarkusnexus** [comment]
$file->body is coming with less than 7 characters. The first offset used for the check is 0 + 7. Anything less than 7 characters will throw this warning, including an empty string.

**Comment by desveladisimo** [comment]
$file->body is coming with less than 7 characters. The first offset used for the check is 0 + 7. Anything less than 7 characters will throw this warning, including an empty string.

**Comment by mblaney** [comment]
yes I've fixed it and will add it to 1.4.1

**Comment by mblaney** [comment]
fixed
