### ISSUE TITLE
Error: invalid XML, likely due to invalid characters.

### ISSUE THREAD

**Issue by jlemm45** [simplepie/simplepie#451]
I'm using the 1.4.1 release and keep getting this error for any feed I try to parse. I even tried the demo and still get this error for all the demo feeds.

is invalid XML, likely due to invalid characters. XML error: Not well-formed (invalid token) at line 1, column 1

After switching back to 1.3.1 I have no issues.

**Comment by mblaney** [comment]
@jlemm45 I've seen this recently when I set force_feed to true, and the file is actually html. Can't say much more about it because it does depend on how your using SimplePie.

**Comment by MrIntimement** [comment]
I've got same error with some feed.
There are some Ascii character like EOT or STX in my feed. 
Force_feed don't work on it.

**Comment by thinkingmedia** [comment]
@jlemm45 Can you post a sample feed or a link to one.
