### ISSUE TITLE
SimplePie demo cannot render my feed

### ISSUE THREAD

**Issue by yusufhgmail** [simplepie/simplepie#452]
I enter www.magrowth.com/sv/feed into the SimplePie demo but it says feed is not found: http://simplepie.org/demo/?feed=www.magrowth.com%2Fsv%2Ffeed

I've tested multiple other feed readers and they all work, so my conclusion is that SimplePie must be doing something differently hence a SimplePie problem.

Here are some of the other RSS readers I've tested and they all work:
Feedbucket: http://www.feedbucket.com/?src=http%3A%2F%2Fwww.magrowth.com%2Fsv%2Ffeed
Chrome extension "RSS Feed Reader" - screenshot: https://goo.gl/E5ayQq
Feedly: https://feedly.com/i/spotlight/www.magrowth.com/sv/feed
Digg: http://digg.com/reader/feed/http%3A%2F%2Fwww.magrowth.com%2Fsv%2Ffeed%2F

**Comment by mblaney** [comment]
@yusufhgmail you're blocking the SimplePie user agent. Try it with:     $feed->set_curl_options(array(CURLOPT_USERAGENT => ""));

**Comment by yusufhgmail** [comment]
@mblaney thanks for your response. I'm not sure what is blocking that and where that script would go - is this something you can help me with or how can I find out?

**Comment by mblaney** [comment]
@yusufhgmail it would go after wherever you call: $feed = new SimplePie();

**Comment by yusufhgmail** [comment]
@mblaney sorry if I'm being dumb, but are you saying that I need to change something on my website back-end? I'm asking because I haven't done anything special to block SimplePie - I'm just using a normal wordpress site with a theme that I purchased.

**Comment by mblaney** [comment]
@yusufhgmail that's ok, but yes you need to get someone to look at your web server setup.
