### ISSUE TITLE
"gzinflate(): data error" introduced in 1.4.2

### ISSUE THREAD

**Issue by dhilowitz** [simplepie/simplepie#454]
Code:

        $feed = new \SimplePie();
        $feed->set_cache_location(storage_path('simplepie_cache'));
        $feed->enable_cache(false);
        $feed->set_feed_url('http://www.inthedc.com/wp/feed/podcast/');
        $feed->force_feed(true);
        $feed->force_fsockopen(true);
        $feed->handle_content_type();
        $feed->init();

Produces:

    #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'gzinflate(): da...', '/mnt/www/myapp...', 337, Array)
    #1 /mnt/www/myapp/vendor/simplepie/simplepie/library/SimplePie/gzdecode.php(337): gzinflate('?UKn?0?????-???...')
    #2 /mnt/www/myapp/vendor/simplepie/simplepie/library/SimplePie/File.php(249): SimplePie_gzdecode->parse()
    #3 [internal function]: SimplePie_File->__construct('http://feeds.so...', 10, 5, Array, 'SimplePie/1.4.1...', true, Array)
    #4 /mnt/www/myapp/vendor/simplepie/simplepie/library/SimplePie/Registry.php(183): ReflectionClass->newInstanceArgs(Array)
    #5 /mnt/www/myapp/vendor/simplepie/simplepie/library/SimplePie.php(1596): SimplePie_Registry->create('File', Array)
    #6 /mnt/www/myapp/vendor/simplepie/simplepie/library/SimplePie.php(1368): SimplePie->fetch_data(false)
    #7 /mnt/www/myapp/app/Jobs/CrawlFeed.php(51): SimplePie->init()

----

When I roll back to 1.4, the error goes away.

**Comment by mblaney** [comment]
thanks @dhilowitz, turned out to be this recent change: https://github.com/simplepie/simplepie/pull/445/files#diff-e59a4cebfc88bc3c35cfc7157fc45f2fR230

**Comment by jonmunson** [comment]
I get a similar error"
`PHP Warning:  gzinflate(): data error in /simplepie/simplepie/library/SimplePie/gzdecode.php on line 337`

**Comment by mblaney** [comment]
this has been fixed by #455
