### ISSUE TITLE
Support for UConverter

### ISSUE THREAD

**Issue by JanPetterMG** [simplepie/simplepie#464]
(PHP 5.5.0, PHP 7, PECL >= 3.0.0a1)
http://php.net/manual/en/class.uconverter.php

`UConverter`, an alternative to `iconv` and `mbstring`

There isn't much documentation at PHP.net at the moment, but I can ensure you that this is working like a charm:

Object oriented style

``` php
$uConverter = new \UConverter($toEncoding, $fromEncoding);
$converted = $uConverter->convert($string);
```

http://php.net/manual/en/uconverter.convert.php

Procedural style

``` php
$converted = \UConverter::transcode($string, $toEncoding, $fromEncoding);
```

http://php.net/manual/en/uconverter.transcode.php

**Comment by CharlesWiltgen** [comment]
I'm looking for places where I might be able to contribute, @JanPetterMG — can you let me know what issues this fixes or what it makes nicer? (Thanks!)

**Comment by JanPetterMG** [comment]
@CharlesWiltgen This is a low-priority feature request, that doesn't really fix any open issues.
It's a great alternative to `iconv` and `mbstring` for character encoding conversions. Simplepie currently requires at least one of those two to be functional.

On many systems, `iconv` isn't installed/enabled by default, witch leaves us with a limited set of supported encodings. By also utilizing `UConverter` (where available), we _might_ be able to squeeze out a few more encodings, and raise the number of feeds Simplepie is able to parse.

_An easy thing to implement, unfortunately I haven't had the time to fix it yet [it's too low prioritized on my to-do list]..._
