### ISSUE TITLE
Yahoo Weather AddOn does not work anymore

### ISSUE THREAD

**Issue by Zodiac1978** [simplepie/simplepie#465]
http://simplepie.org/wiki/addons/yahoo_weather

I think the output from the new YQL API is slightly different:
https://www.igorkromin.net/index.php/2016/04/14/yahoo-returns-its-weather-api-to-public-access-switches-to-yql-for-query/

**Comment by skyzyx** [comment]
This was a demo that was written almost 10 years ago. Feel free to rewrite it for newer YQL.
