### ISSUE TITLE
Empty feeds: The data could not be converted to UTF-8.

### ISSUE THREAD

**Issue by JanPetterMG** [simplepie/simplepie#466]
I have 823 empty feeds, witch gives me the following error:

> The data could not be converted to UTF-8. You MUST have either the iconv or mbstring extension installed. Upgrading to PHP 5.x (which includes iconv) is highly recommended.

By empty feed I mean an empty body, along with an HTTP header...
The W3C validator gives this error for most, if not all of them:

> XML parsing error: <unknown>:1:0: no element found

The Simplepie demo:

> A feed could not be found

or

> The data could not be converted to UTF-8
#### Relevant setup data:
- Simplepie 1.4.2
- PHP 5.6
- mbstring
- iconv
- UConverter
#### Some randomly selected feeds:
- http://www.juntadeandalucia.es/medioambiente/site/aplica/rss/servlet/RssServlet?canal=avisos
- http://www.lifespy.com/feed/
- http://www.oomphonline.com/rss/catalog/new/store_id/1/
- http://www.purlbee.com/the-purl-bee/atom.xml
- http://www.pennyandaggie.com/feed.php
#### The solution

Check the content length, and give the "empty feed" warning, before checking the HTTP header for whatever content type it is...
It looks like it's returning the "empty feed" warning only if the content is XML, and "Could not be converted to UTF-8" if anyhting else...
#### I also have two other questions:
- ~~Is it possible to change the error message above?~~
  - ~~Remove `Upgrade to PHP 5.x` - SimplePie already requires PHP 5.3, so this is completely irrelevant~~ #467
  - ~~Warn about missing mbstring or iconv, only if the specific extension isn't detected.~~ #467
- Is the Simplepie demo still running v1.3 ??

**Comment by mblaney** [comment]
Checking the content length sounds like a good idea @JanPetterMG.

I recently got access to the website, so updating the demo to the latest version is on my list of things to do.
