### ISSUE TITLE
Simple Pie version 1.4.2 still marked as 1.4.1

### ISSUE THREAD

**Issue by abgreeve** [simplepie/simplepie#472]
The simple pie class file (library/SimplePie.php) still reads as 1.4.1. Both the doc block @version and the constant (SIMPLEPIE_VERSION) should be changed. This is a trivial issue, but I am recording it as it is messing with our processes with our software (https://tracker.moodle.org/browse/MDL-56001).

**Comment by mblaney** [comment]
ah, sorry about that. I'll fix it now, let me know if you want a new release.

**Comment by danpoltawski** [comment]
If a new version is incoming we'll take that - but no worries if it creates extra work, thanks for looking after simplepie :)
