### ISSUE TITLE
Segmentation fault on init()

### ISSUE THREAD

**Issue by JanPetterMG** [simplepie/simplepie#476]
Once I trigger `init()`, I get an segmentation fault on https://www.theguardian.com/uk/culture/rss
`[core:notice] [pid 10768] AH00052: child pid 2957 exit signal Segmentation fault (11)`

It doesn't matter if im using `set_raw_data()` or `set_feed_url`, it's returning segmentation fault every single time (tried a few houndred times already).

**I'm NOT able to re-produce this using the code below isolated, but when inserted onto my script, it fails as the only one in my db of 1.1M feeds..**. That cannot be an coincidence right?

```php
$feed = new SimplePie();
$feed->set_feed_url('https://www.theguardian.com/uk/culture/rss');
$feed->init();
// Segmentation fault
```

Simplepie 1.4.1
PHP 5.6.24-0+deb8u1

Any ideas?

**Comment by thinkingmedia** [comment]
I think a segmentation fault produced by an out of memory error in PHP. It's not a coding fault.

You have to increase available memory in php.ini or via the command line.

**Comment by JanPetterMG** [comment]
@thinkingmedia Already tried that (both in config and using ini_set).
I'm normally running on 128M, but I've tried different values up to 2048M, without any difference.
I've also created an isolated script, fetching the same data, for every item, witch shows 19MB peak memory usage... The raw data of the feed itself is about 1,06MB

**Comment by thinkingmedia** [comment]
I can your code sample fine. (Win10 + PHP 7.0.10)

The error is hard to debug. You can try to disable PHP modules to see if one of them is the offender, or you could try changing your PHP version. There is no one solution for this.

Is this running under Apache? or just on the CLI?

**Comment by JanPetterMG** [comment]
It's running on CLI, but I've debugged using Apache webserver too.
Reproducing, I know, isolated it runs fine, but not "in production".

Disabling modules, I think I'll try that. Thanks!

**Comment by JanPetterMG** [comment]
I don't understand why this feed, or what really caused the segmentation fault, but this code caused the problem:
```php
$dbh = new \PDO("...", $user, $pass, [\PDO::ATTR_PERSISTENT => true]);
$feed = new SimplePie();
$feed->set_feed_url('https://www.theguardian.com/uk/culture/rss');
$feed->init();
// Segmentation fault
```
By running the above code isolated, it was failing, but once I changed `PDO::ATTR_PERSISTENT` to `false`, everything worked out...

**Comment by thinkingmedia** [comment]
Seriously, that is very strange.

Are you using MySQL? and was the above inside a loop?

**Comment by JanPetterMG** [comment]
Yes, I was using mysql (mariadb 10.1.17), and it was originally inside a loop. Each loop lasted for 60 sek, and there was multiple loops running in parallel (a new loop every 15 sek or so). There's also a "worker" system in place, making sure feeds isn't looped multiple times at once.

I was running tests on the production server, with the exact code as shown in my previous comment (only dsn\user\pass was stripped out). Same credentials, same everything.

There was **no queries in the test** either, so I don't understand it at all...
For the record, that specific feed was resulting in segmentation errors for 3 days, before it was solved.

I cannot explain why it happen, but I can live with PDO::ATTR_PERSISTENT disabled, no problem...
