### ISSUE TITLE
simplepie.org/downloads/ still shows 1.3.1 as latest

### ISSUE THREAD

**Issue by photodude** [simplepie/simplepie#479]
The simplepie website downloads page http://simplepie.org/downloads/ still shows 1.3.1 as the latest release and not the current 1.4.2 release. 

![simplepie](https://cloud.githubusercontent.com/assets/10253980/20013082/790e189a-a277-11e6-941d-d6580ac10f0c.PNG)

This has created a little confusion for some projects about what the current stable release is.

**Comment by skyzyx** [comment]
@rmccue had facilitated getting this hosting and source code moved over to the WordPress team. He would be the best contact for finding out how to start making updates.

**Comment by mblaney** [comment]
I've got access to the current site, so will try bump this up the priority list.

**Comment by mblaney** [comment]
I've changed the link at the top of each page from 1.3.1 to 1.4.2, and made some changes to the downloads page. Hope that helps!

**Comment by photodude** [comment]
Thank you @mblaney,
I hope someday the downloads page and notice on the top of the pages can be automated so that it always tracks with the releases.

This issue can probably be closed now.

**Comment by skyzyx** [comment]
Just wanted to say that most of the code for the website was written in 2005 and hasn't changed much since then. Please don't judge 11-years-ago me. ;)

**Comment by mblaney** [comment]
haha thanks for writing it in the first place @skyzyx!
