### ISSUE TITLE
Hosted compiled version is out of date

### ISSUE THREAD

**Issue by Sigafoos** [simplepie/simplepie#482]
The bug fixed in #231 has not been fixed on http://dev.simplepie.org/SimplePie.compiled.php

(cloning the repo and compiling it myself did fix the issue)

**Comment by mblaney** [comment]
I removed the link to the compiled version from the downloads page, don't really want to maintain that for people. Let me know if there are still links to it I should remove.

**Comment by Sigafoos** [comment]
@mblaney it's referenced in the readme:

> If you'd like a single monolithic file, you can run php build/compile.php to generate SimplePie.compiled.php, or grab a copy from dev.simplepie.org (this is kept up-to-date with the latest code from Git).

**Comment by mblaney** [comment]
thanks I've removed it in #486
