### ISSUE TITLE
Parse/convert Json to an readable format

### ISSUE THREAD

**Issue by JanPetterMG** [simplepie/simplepie#483]
Hi guys, I just found a bunch of RSS feeds that has stopped working (webpage issues). The format has changed to Json.

Does anyone know a way to convert RSS-like Json feeds to Atom/RSS so that they can be parsed using Simplepie with success? _(without starting from scratch)_

How much work is it to add an Json->RSS converter ~~officially~~ in Simplepie?
_The conversion process could eg. be triggered for `Content-type`: `application/json` only._

The feed output looks like this:
```json
{
  "title": "Feed title",
  "link": "http://example.com/feed/",
  "home": "http://example.com/",
  "description": "Some description",
  "updated": "mo, 14 nov 2016 17:50:34 +0100",
  "copyright": "example",
  "category": "Category",
  "items": [
    {
      "title": "Item title",
      "description": "Some description",
      "link": "http://example.com/somepage.html",
      "category": "Item category",
      "pubDate": "su, 06 nov 2016 19:20:01 +0100",
      "updateDate": "su, 06 nov 2016 20:19:08 +0100"
    },
    {
      "title": "Item title 2",
      "description": "Some other description",
      "link": "http://example.com/somepage2.html",
      "category": "Item category",
      "pubDate": "su, 06 nov 2016 16:58:00 +0100",
      "updateDate": "su, 06 nov 2016 16:58:00 +0100"
    }
  ]
}
```
Example url: http://www.itromso.no/video/?widgetName=polarisFeeds&widgetId=10009032&getXmlFeed=true

**Comment by skyzyx** [comment]
Is there a spec? AFAIK, this is not actually RSS.

**Comment by JanPetterMG** [comment]
I know, as I said, this is due to webpages having issues with their publishing systems / rss creators...
Okay, forget everything about official support, but I still want to convert it to an readable format.

Is there a dirty solution? eg. by converting Json->array and then pass that to an existing simplepie class?

_ATM I'm working on a dirty fix, convert it to XML, and then letting simplepie figure out what kind of feed it is, and how to parse it..._

**Comment by skyzyx** [comment]
You can try using [skyzyx/transmogrifier](https://github.com/skyzyx/transmogrifier) to convert an array into an XML document. This might help kick-start your efforts.

Unfortunately, all of SimplePie's components are tightly-coupled, so you may need to do some finagling to inject code which does this. :/

**Comment by JanPetterMG** [comment]
Got it working using an custom Json->Array->SimpleXMLElement->XML converter, triggered when stumbling upon `application/json` content.
It only works for previously RSS feeds (not Atom yet), and not all data are recognized either.

WIP
