### ISSUE TITLE
Youtube video diseapear from feed items with Simplepie

### ISSUE THREAD

**Issue by onigetoc** [simplepie/simplepie#484]
I did a script to grab Youtube video on page url or iframe. but sometime. Youtube video disapear from the feed item.
in this example there's a lot of Youtube videos on the original feed but simplepie ignore them and remove them
RSS Source: http://premium.wpmudev.org/blog/feed/
With Simplepie
http://simplepie.org/demo/?feed=http%3A%2F%2Fpremium.wpmudev.org%2Fblog%2Ffeed%2F

**Comment by mcneely** [comment]
Perhaps the feed has changed but I'm not seeing any Youtube videos in the original feed.

**Comment by onigetoc** [comment]
Hi, obviously the feed have changed :)
