### ISSUE TITLE
Empty tags returning null

### ISSUE THREAD

**Issue by JanPetterMG** [simplepie/simplepie#496]
````
<category><![CDATA[]]></category>
<description><![CDATA[]]></description>
````
````
var_dump($item->get_categories()[0]->get_label()); // string(0) ""
var_dump($item->get_description()); // NULL
````
Until 1.4.3 and #494, the content was handled equally, and the output was the same no matter what tag it originally came from, that's not the case anymore.

Is there any reason for this? If description/content is returning `null` for empty content, why doesn't the others?

Either should all return `null`, or @mblaney should fix the introduced bug, so that it doesn't return null for empty content anymore.
In my opinion, `null` should either be reserved for "non-existing" tags, or be used for all "empty" tags.

This is a generic issue, and applies to most tags, not just `<category>` and `<description>`.

**Comment by skyzyx** [comment]
@mblaney: Are you planning to do any active development here, or are you mostly just merging PRs?

**Comment by mblaney** [comment]
@skyzyx whether functions return null or an empty string is an inconsistency across the code base, but I don't consider it a bug. So no I'm not planning on doing any development in this area.

**Comment by skyzyx** [comment]
Meh. Yeah, sorry about the inconsistency, all. :/
