### ISSUE TITLE
500 error when element not found

### ISSUE THREAD

**Issue by iamdave210** [simplepie/simplepie#499]
I've just been troubleshooting a problem with SimplePie where it crashes when trying to get an element that doesn't exist in an item. I was on version 1.3.1 when I first ran into it and I updated to 1.4.3 but the issue persisted. My code:
```
    foreach (array_reverse($feed->get_items()) as $item){
        $event = [];
        
        $event["title"] = $item->get_title();
        $event['author'] = $item->get_author()->get_email(); //crashes when no author
        $event['category'] = $item->get_category()->get_label();
        $event["link"] = $item->get_permalink();
        $event["description"] = $item->get_description();
        $event["pubdate"] = $item->get_date("D, d M Y H:i:s T");
        $event["dc.date"] = $item->get_gmdate("Y-m-d")."T".$item->get_gmdate("H:i:s")."Z";
        $event["date_timestamp"] = $item->get_gmdate("U");
    }
```
Most of the items in the feed have an &lt;author&gt; element but some don't and when it gets to one that doesn't it crashes with the error "PHP Fatal error:  Call to a member function get_email() on null".

**Comment by abhij89007** [comment]
Add an empty check for 'Author' ? 
`if(!empty($item->get_author())) {
$event['author'] = $item->get_author()->get_email(); //crashes when no author
}
`
