### ISSUE TITLE
`Cache is not writable` error - Laravel

### ISSUE THREAD

**Issue by sentiasa** [simplepie/simplepie#502]
I am trying to use SimplePie with Laravel.
```
$link = "http://www.ntv.com.tr/gundem.rss";
$feed = new SimplePie();
$feed->set_feed_url($link);
$feed->set_cache_location($_SERVER['DOCUMENT_ROOT'] . '/app/cache_files');
$feed->init();
$feed->handle_content_type();

dd($feed->get_items());
```

However, I started getting this error. 

> /home/vagrant/Code/proj/public/app/cache_files is not writeable. Make sure you've set the correct relative or absolute path, and that the location is server-writable.

What should I do while using SimplePie with Laravel? What should I do?

**Comment by skyzyx** [comment]
The answer is to make sure that the file system location is writable by the PHP process.
