### ISSUE TITLE
SimplePie Not Parsing RSS Feed

### ISSUE THREAD

**Issue by kzenman** [simplepie/simplepie#503]
I've been using SimplePie for about 4 yrs now w/Curl...and it's worked great up until 2-6-17.

For the last 12+ hrs I've been trying to narrow down why it won't parse any of craigslists list feeds. I've tried ever possible scenario available. I do get a 200 return with the data, but it includes it with an error.

    is invalid XML, likely due to invalid characters. XML error: Not well-formed (invalid token) at line 1, column 1

Here's the weird thing, it works with fopensocket with no problems.

Here here some of my settings:

    **Ubuntu 14.04

    Apache/Ngnix

    PHP 5.6

    Host: VPS DigitalOcean

    SimplePie v-1.4.3

    $rss = new SimplePie();

    $rss->set_feed_url('http://phoenix.craigslist.org/search/zip?format=rss');

    $rss->useragent= 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.7) Gecko/20070914 Firefox/2.1.0.7';

    $rss->get_item_quantity( 10 );

    $rss->force_feed(true);

    $rss->force_fsockopen(false);

    $rss->set_input_encoding('UTF-8');

    $rss->set_output_encoding('UTF-8');

    $rss->init();

    $rss->handle_content_type();**

Here's the return of the header:

    **HTTP/1.1 200 OK

    Cache-Control: max-age=900, public Last-Modified: Mon, 13 Feb 2017 18:24:12 GMT Date: Mon, 13 Feb 2017 18:24:12 GMT Content-Encoding: gzip Vary: Accept-Encoding Content-Length: 5991 Content-Type: application/rss+xml; charset=utf-8 X-Frame-Options: SAMEORIGIN Server: Apache Expires: Mon, 13 Feb 2017 18:39:12 GMT**

The body is returning with the header information too.

I've done a RSS validate and it didn't have any significant errors.

Also, tried it on a brand new server/same settings and got the same result.

They do work on the demo site simplepie.org/demo...so I'm thinking it has something to do with my server settings.

Any help would be appreciated!

**Comment by kzenman** [comment]
PS ...I think Ive narrowed it down to HTTP Parser.php ...it seems to not be separating the header and body

**Comment by skyzyx** [comment]
Are you using it behind a proxy? Some older proxies add an additional set of HTTP headers to the response, and cURL doesn't calculate it correctly. :/

**Comment by kzenman** [comment]
Hi @skyzyx  yes...and tried it without and get Line 129: cURL error 28: Operation timed out after 9992 milliseconds with 2218 out of 4785 bytes received. 

Here is my cUrl:
				//curl_setopt($fp, CURLOPT_PROXY, $this->proxy);
				//curl_setopt($fp, CURLOPT_PROXYPORT, "3128");
				curl_setopt($fp, CURLOPT_URL, $this->url);
				curl_setopt($fp, CURLOPT_SSL_VERIFYPEER, FALSE);
				curl_setopt($fp, CURLOPT_SSL_VERIFYHOST, FALSE);
				curl_setopt($fp, CURLOPT_HEADER, 1);
				curl_setopt($fp, CURLOPT_RETURNTRANSFER, 1);
				curl_setopt($fp, CURLOPT_FAILONERROR, 0);
				curl_setopt($fp, CURLOPT_TIMEOUT, $timeout);
				curl_setopt($fp, CURLOPT_CONNECTTIMEOUT, $timeout);
				curl_setopt($fp, CURLOPT_REFERER, $url);
				curl_setopt($fp, CURLOPT_USERAGENT, $useragent);
				curl_setopt($fp, CURLOPT_HTTPHEADER, $headers2);

**Comment by kzenman** [comment]
I did get it working by setting $rss->set_timeout(30); And it's taking the full 30 seconds
Which doesn't work for my application because we need to use a proxy and we do 1000s of requests every 5-10mins. 
Ive been using this proxy service for over 1 yr., but I can check with them .

@skyzyx  I don't think that's the case...here is the returned header (notice the cookie).
HTTP/1.1 200 OK
Connection: close
Cache-Control: max-age=900, public
Last-Modified: Tue, 14 Feb 2017 18:44:53 GMT
Date: Tue, 14 Feb 2017 18:44:53 GMT
Content-Encoding: gzip
Vary: Accept-Encoding
Content-Length: 4876
Content-Type: application/rss+xml; charset=utf-8
X-Frame-Options: SAMEORIGIN
Set-Cookie: cl_b=KlKJrOXy5hGuFtGN_3GNqwWqz0M;path=/;domain=.craigslist.org;expires=Fri, 01-Jan-2038 00:00:00 GMT
Server: Apache
Expires: Tue, 14 Feb 2017 18:59:53 GMT

**Comment by kzenman** [comment]
Found it! Now works with older proxies
http://stackoverflow.com/questions/16965530/what-to-do-with-extra-http-header-from-proxy

Thanks @skyzyx  for pointing me in the right direction

I added this on line 158 of FILE.php

					// cURL automatically handles Proxy rewrites, remove the "HTTP/1.0 200 Connection established" string
					$this->headers = explode("\r\n\r\n", $this->headers, $info['redirect_count'] + 1);
					$this->headers = array_pop($this->headers);//$this->headers[0];//
					if (false !== stripos($this->headers, "HTTP/1.0 200 Connection established\r\n\r\n")) {
  $this->headers = str_ireplace("HTTP/1.0 200 Connection established\r\n\r\n", '', $this->headers);
}

**Comment by abhij89007** [comment]
I tried the feed url at demo link, and seems to be working:

http://simplepie.org/demo/?feed=http%3A%2F%2Fphoenix.craigslist.org%2Fsearch%2Fzip%3Fformat%3Drss

**Comment by kzenman** [comment]
Hi @abhij89007 ....I posted the fix 10 days ago. Thanks for looking.
