### ISSUE TITLE
SimplePie 1.3.1 bundled into Wordpress plus documentation issues

### ISSUE THREAD

**Issue by 01i** [simplepie/simplepie#505]
I'm not sure that this is an appropriate place to report this, but I wanted to at least make sure that the SimplePie devs had eyes on this issue.

All of the SimplePie documentation advises that if you want to integrate SimplePie into a wordpress install, you should make use of the "SimplePie Core" wordpress plugin. However, looking into this plugin, it's not been updated on the Wordpress plugin's directory for 9 years, and wordpress have actually included SimplePie as a part of wordpress for some time. This makes the old plugin (and advise to use it) out of date, because the plugin would drop out advising that SimplePie was already installed anyway. 

https://wordpress.org/plugins/simplepie-core/

At this point in time it would make sense to update the description of the plugin on the wordpress directory to point out that it is no longer required as SimplePie is integrated natively, and to update the SimplePie documentation to say the same thing.

However, there is also a problem with this scenario. Yes, Wordpress is bundling SimplePie (making the plugin superfluous), but Wordpress still has version 1.3.1 included in the current codebase (4.7.3). 

https://core.svn.wordpress.org/tags/4.7.3/wp-includes/SimplePie/

There is an assigned ticket open on the Wordpress core tracker, asking for wordpress to be updated to version 1.4, but this ticket has sat awaiting review since it was opened 11 months ago, and is now out of date again with regards to the latest version of SimplePie.

https://core.trac.wordpress.org/ticket/36669

**Comment by 01i** [comment]
A quick related follow up to the comment regarding the documentation. But it would seem that the SimplePie API documentation has not been updated beyond 1.3 either.

**Comment by 01i** [comment]
Additional documentation issues: 

All of the screencasts listed on the "Tips, Tricks, Tutorials, and Screencasts" documentation (with 2 exceptions) are broken links to 404 pages. This includes the screencasts that were hosted on the http://simplepie.org website. The two exceptions are "Quick Tip #16 Super SimplePie!" and "CSS-Tricks: Adding RSS content with SimplePie".

In addition, large portions of the other tutorial links on the same page are broken.

**Comment by skyzyx** [comment]
The documentation you're talking about has (unfortunately) not been updated effectively since early 2010. The honest answer is that none of the documentation which exists today will likely be updated in any useful way. The documentation will need to be rewritten from scratch. :(
