### ISSUE TITLE
Allow custom headers in requests

### ISSUE THREAD

**Issue by diggersworld** [simplepie/simplepie#506]
Hi, I've recently implemented an application which releases an event stream for third-party sites read data from. The event stream may contain sensitive information in places and has therefore been placed behind an authentication layer. The default means for providing this authorisation data is within a request header. However with SimplePie I have not been able to find a way of achieving this.

What I've had to do instead is allow an access token to be provided as a query parameter to the URL where my event feed resides. This isn't ideal for a number of reasons but it will work for the time being.

I'm wondering however if there is such a way to specify a custom header with SimplePie? Or whether this should be considered a feature request.

**Comment by mblaney** [comment]
@diggersworld there isn't a way to specify custom headers in SimplePie, that would be a good addition.

**Comment by skyzyx** [comment]
You should be able to override usage of `SimplePie_File` with a class which extends `SimplePie_File`, then implements the custom behavior you want. You'll need to call `set_file_class()`, IIRC.
