### ISSUE TITLE
Simplepie not finding my Wordpress feed?

### ISSUE THREAD

**Issue by jord84** [simplepie/simplepie#513]
Hoping for some help here,
Simplepie doesn't find my WordPress feed:
[http://simplepie.org/demo/?feed=http%3A%2F%2Ftraveltalesoflife.com%2Ffeed](http://simplepie.org/demo/?feed=http%3A%2F%2Ftraveltalesoflife.com%2Ffeed)

Others can find it fine:
[http://www.feedbucket.com/?src=http%3A%2F%2Ftraveltalesoflife.com%2Ffeed](http://www.feedbucket.com/?src=http%3A%2F%2Ftraveltalesoflife.com%2Ffeed)

And it is a valid feed:
[https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Ftraveltalesoflife.com%2Ffeed](https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Ftraveltalesoflife.com%2Ffeed)

Hopefully someone could provide some insight?

Thanks!
Jordan

**Comment by mblaney** [comment]
Hi @jord84 can you check that your site is not blocking the user agent simplepie uses? I was able to parse your feed by using:  $feed->set_curl_options([CURLOPT_USERAGENT => ""]);
