### ISSUE TITLE
Our Website has been Hacked

### ISSUE THREAD

**Issue by NeilJClarke** [simplepie/simplepie#514]
Hi Support,

Just thought I would let you know that our website has been hacked and their route into the site was via Simplepie! When we downloaded the site to a PC, the antivirus identified the following as malicious.

Items: 
\wp-includes\SimplePie\XML\Declaration\Declaration.php

Filename: backdoor:PHP/WebShell.A

Just thought you should know?

Regards
Neil

**Comment by thinkingmedia** [comment]
@NeilJClarke sorry that you got hacked, but that antivirus tool just located the PHP file that was infected. It doesn't mean that the source code from Simplepie originally came with the virus. At some point in time the file was modified to include the hack.

SimplePie is not a WordPress plug-in so I don't know why it's in your wp-include folder.

Make sure you keep your WordPress installs up to date and keep regular back ups. WordPress is not a secure platform and it will get hacked. So keep regular back ups.

**Comment by mwaterhouse** [comment]
> SimplePie is not a WordPress plug-in so I don't know why it's in your wp-include folder.

Core Wordpress started using SimplePie with Wordpress 2.8 :-)
