### ISSUE TITLE
This XML document is invalid, likely due to invalid characters. XML error: Mismatched tag at line 10, column 8

### ISSUE THREAD

**Issue by zstergios** [simplepie/simplepie#515]
Every FeedBurner link causes the same error!
Examples:
http://feeds.feedburner.com/climatecentral/djOO
http://feeds.feedburner.com/TheTopobaseInsiders

I use custom User_Agent
Please solve this issue!

**Comment by JanPetterMG** [comment]
Both feeds are validated valid, and I'm currently able to parse both in the demo:
http://simplepie.org/demo/?feed=http%3A%2F%2Ffeeds.feedburner.com%2Fclimatecentral%2FdjOO
http://simplepie.org/demo/?feed=http%3A%2F%2Ffeeds.feedburner.com%2FTheTopobaseInsiders
Also, this is not a FeedBurner issue, I'm able to parse a lot of different FeedBurner feeds, so these bugs does apply to specific feeds by specific webpages only.

I'm not able to parse the feeds myself either (might be multiple reasons to that, custom setup).
Anyway it seems to be two main issues:
- Atom 1.0: Namespace-prefix issue
- RSS 2.0: HTML-decoding issue?

Atom: http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Ffeeds.feedburner.com%2FTheTopobaseInsiders
RSS: http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Ffeeds.feedburner.com%2Fclimatecentral%2FdjOO

-----

@mblaney What version is the demo running?
Do you mind posting an quick note about it somewhere at the demo webpage?
```php
echo 'The demo is running Simplepie ' . SIMPLEPIE_VERSION;
```

**Comment by mblaney** [comment]
@JanPetterMG it's running 1.2, I might have a look at updating it to 1.5. It looks like it still gets enough use that it's worth doing that.

**Comment by mblaney** [comment]
I've updated the demo page to use version 1.5 now.

**Comment by zstergios** [comment]
I made an example....the same issue here!
[simplePieExample.php.txt](https://github.com/simplepie/simplepie/files/979507/simplePieExample.php.txt)

Errors:Array
(
    [0] => http://feeds.feedburner.com/climatecentral/djOO is invalid XML, likely due to invalid characters. XML error: Mismatched tag at line 10, column 8
)

**Comment by zstergios** [comment]
I found the issue....!
FeedBurner before some years when it was loaded through browser has displayed HTML and when from feed parser automatically serves XML.
This has been stopped.....

No to able to serve XML, you have to request on on URL.
Just add `?format=xml`
Example:
http://feeds.feedburner.com/climatecentral/djOO?format=xml
