### ISSUE TITLE
Feed not grabbing, although it is getting validated

### ISSUE THREAD

**Issue by sfatfarma** [simplepie/simplepie#516]
I am using SimplePie 1.5 and a found an issue with this feed address: http://feeds.ezinearticles.com/category/Shopping-and-Product-Reviews:Fashion-Style.xml . It validates in the feed validator: https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Ffeeds.ezinearticles.com%2Fcategory%2FShopping-and-Product-Reviews%3AFashion-Style.xml but in SimplePie, it does not grab the feed: http://simplepie.org/demo/?feed=https%3A%2F%2Fvalidator.w3.org%2Ffeed%2Fcheck.cgi%3Furl%3Dhttp%253A%252F%252Ffeeds.ezinearticles.com%252Fcategory%252FShopping-and-Product-Reviews%253AFashion-Style.xml .
I get the following error in code: 

`cURL error 18: transfer closed with 42828 bytes remaining to read for http://feeds.ezinearticles.com/category/Shopping-and-Product-Reviews:Fashion-Style.xml`

I searched the net for similar issues and found some workarounds that suggested using: 
$feed->set_curl_options([CURLOPT_HTTPHEADER => ['Expect:']]); 
or 
$feed->set_curl_options([CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_0]);
but none worked.

Thanks for helping!

**Comment by skyzyx** [comment]
In this case, the cURL message says that the remote server stopped sending the feed (or the connection was open so long that the overall connection timed-out, mid-download).

This is a cURL issue. Resolving.
