### ISSUE TITLE
cURL error 22: The requested URL returned error: 400 Bad Request

### ISSUE THREAD

**Issue by sfatfarma** [simplepie/simplepie#517]
Hello, I found this feed that returns an error with SimplePie. http://simplepie.org/demo/?feed=http%3A%2F%2Fpkmediasharing.com%2Ffeed

It is a valid feed: https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fpkmediasharing.com%2Ffeed

Thank you for your help.

**Comment by sfatfarma** [comment]
Another feed that has the same issue: http://simplepie.org/demo/?feed=https%3A%2F%2Fleaguelane.com%2Ffeed

**Comment by sfatfarma** [comment]
Also, please note that these feeds are working with SimplePie older versions (the one that is built-in in WordPress 4.7)

**Comment by skyzyx** [comment]
This is a cURL error, meaning that the demo server was unable to fetch the feed from its source.

Resolving.

**Comment by pragneshok** [comment]
Reason for this error: Some RSS feed provider block "SimplePie" as user agent request
Solution: You need to remove "SimplePie" from user agent from cURL request.
Code:
File path "/library/SimplePie/File.php", In  that file you can comment user agent on line number 110 [check below commented line]

//curl_setopt($fp, CURLOPT_USERAGENT, $useragent);

**Comment by skyzyx** [comment]
No, don’t go in and start modifying files.

```php
$feed->set_useragent('something else');
```

**Comment by sfatfarma** [comment]
Thank you!
