### ISSUE TITLE
No set_proxy() function in Simplepie 1.5

### ISSUE THREAD

**Issue by vargenau** [simplepie/simplepie#518]
Hi,

I am trying to move code from Simplepie 1.1 to 1.5.

I had done a new SimplePie() with 4 parameters, the fourth one being the proxy.

As I understand, I should create the SimplePie() with no parameters, then call set_feed_url(), set_cache_location() and set_cache_duration().

The problem is, there is no set_proxy() function.

What should I do to set the proxy?

**Comment by abhij89** [comment]
#19

**Comment by Art4** [comment]
This was fixed by #407. @mblaney I think this can be closed.
