### ISSUE TITLE
Is JSON Feed Support planned?

### ISSUE THREAD

**Issue by misel228** [simplepie/simplepie#519]
I'm talking about the freshly released JSON Feed format: https://jsonfeed.org/version/1

(See also slashdot: https://it.slashdot.org/story/17/05/24/1639242/json-feed-announced-as-alternative-to-rss )

Are there any plans to have JSON Feed support in Simplepie?

**Comment by mblaney** [comment]
Hi @misel228 I'm happy to merge it if someone wants to write it.

**Comment by JanPetterMG** [comment]
+1
I think an JSON->RSS/Atom converter is more realistic, but time will show.

I've implemented an custom JSON converter in my Simplepie setup back in november 2016, it's based on data from some random JSON feeds, so I'll obviously have to revise it now.
If there isn't any good converters out there anytime soon, I might share mine (once it's revised).

**Comment by JanPetterMG** [comment]
Here's a JSON to RSS 2.0 converter, it just got out of the oven 4 hours ago...
https://gist.github.com/daveajones/be26f5ca9cb7559d0c33549b53323770

Short guide:
1. Fetch the URL
2. Check the content type, if it's `application/json`, parse it using the above converter. If not, skip this step.
3. Call `$simplepie->set_raw_data($xml);` and `$simplepie->set_input_encoding($encoding);`

**Comment by mblaney** [comment]
that looks great @JanPetterMG :-) going to create a PR?

**Comment by JanPetterMG** [comment]
@mblaney The above works perfectly fine, and doesn't require any changes to the simplepie library. Second, if I'm even going to spend time working on it, it has to be native (witch I don't have time for).

If someone is going to implement this as an converter, it should be an `JSON` to `Atom 1.0` (not `RSS 2.0`). It's just a question about time until someone creates such a converter, so no need to hurry just yet.

-------------------------

Seems to be two JSON formats out there now, the official standard, and a second one from an unknown origin, an RSS look alike (they're not compatible with each other)...

**Comment by wmelton** [comment]
Isn't a JSON to XML converter the wrong direction to be moving? Wouldn't it be more prudent in 2017 to build a consumer that can ingest and process JSON natively?

**Comment by skyzyx** [comment]
Resolving this for now. I have something in the pipeline to address this — built for 2017. :) It is highly unlikely that we'll ever see native JSON Feed support in SimplePie as it exists today.

**Comment by edsu** [comment]
@skyzyx can you say more about why it is unlikely?
