### ISSUE TITLE
Registered sanitizer is not being respected

### ISSUE THREAD

**Issue by fluffy-critter** [simplepie/simplepie#521]
Nothing in the SimplePie initialization or parsing sequence ever actually requests the `Sanitize` class from the registry; the only construction/setting of `$this->sanitize` appears to be in the constructor, where it constructs the default built-in sanitizer.

For example, this has no effect:

    $pie = new SimplePie();
    $pie->get_registry()->register('Sanitize', 'My_Sanitizer_Class');

But this works:

    $pie = new SimplePie();
    $pie->sanitize = new My_Sanitizer_Class();

**Comment by mblaney** [comment]
hi @fluffy-critter I haven't used a different `Sanitize` class but it looks like your first example should work if `My_Sanitizer_Class` is a subclass of the default class?

**Comment by fluffy-critter** [comment]
It doesn't. There's nothing in the SimplePie code that actually makes use of the registry to replace the default sanitizer with the specified one, at least not as of version 1.4.3.

**Comment by mblaney** [comment]
this should do it in `init()`?

`	if (method_exists($this->sanitize, 'set_registry'))
		{
			$this->sanitize->set_registry($this->registry);
		}`

**Comment by fluffy-critter** [comment]
That just propagates the registry itself down to the sanitizer object. It does nothing to replace the sanitizer object with the replacement class.

**Comment by mblaney** [comment]
ah sorry yes you're right @fluffy-critter. it looks like `$this->sanitize = $this->registry->create('Sanitize');` needs to be added above the line I mentioned in init().

**Comment by JanPetterMG** [comment]
Maybe a dumb question, but do we actually need the registry?
How about simplifying where possible? (while still maintaining backwards support).

Personally I think the Simplepie library is too complex. Fixing bugs and adding new functionality is obviously hard as we rarely see bugs being fixed. PHP 7 for example, the build has never passed.

**Comment by skyzyx** [comment]
@JanPetterMG: You're right. SimplePie development started in July 2004 when PHP 4.3 was the new hotness. There is a lot of stripping away and refactoring to be done.

**Comment by mblaney** [comment]
fixed in #532
