### ISSUE TITLE
Please give access to the content type of atom <summary>

### ISSUE THREAD

**Issue by fluffy-critter** [simplepie/simplepie#522]
While rare, there are Atom feeds which provide `<summary type="text">` content, and technically the Atom specification indicates that if the type is unspecified it must default to `text`. (In one particular case, I have contacted a site's implementor about how unfriendly this behavior is in practice and their response was to point to the Atom spec, and I have to say, they aren't *wrong*, and their usage of this obscure feature happens to be a legitimate one.)

So, from a feed reader's perspective, it is important to be able to know whether content is `text` rather than `html` so that line breaks may be respected correctly.

I have been trying to write a custom sanitizer which respects `text` content and either wraps the content element inside a `<pre>` or converts newlines to `<br/>`, but an additional problem is that even when things are explicitly set to `html`, tags are being processed as `SIMPLEPIE_CONSTRUCT_MAYBE_HTML` which then detects whether there are tags or not - and as a result, other Atom tags such as `<title>` also end up with the `SIMPLEPIE_CONSTRUCT_TEXT` flag set afterwards, and there is not enough context to determine what tag is actually being sanitized. If I do a strict match on `$type == SIMPLEPIE_CONSTRUCT_TEXT` it *happens to* work on all the feeds I've spot-checked, but I'm wary of anything that relies on happenstance, especially given the nature of how the content type inference occurs within `SimplePie_Sanitize` (which my sanitizer subclasses from and calls into).

The simplest fix that occurs to me for this issue  is to store the `type` attribute of the `<summary>` tag on the `SimplePie_Item` object and give it an accessor (perhaps `SimplePie_Item::get_content_type` to accompany `SimplePie_Item::get_content` or the like).

I would be fine with implementing this change myself and submitting a pull request on it.

**Comment by mblaney** [comment]
could you describe where the problem is with the current implementation? from a quick glance it looks like it supports `<summary type="text">`.

ie `item->get_description()` passes `$type` to `sanitize` which it gets from atom_*_construct_type.

**Comment by fluffy-critter** [comment]
SimplePie's handling of text content is correct as far as the sanitizer is concerned; the problem is that there's no way for the application that uses it to know that the content type was "text," and thus can't handle it correctly for formatting purposes (for example, converting `\n` to `<br>` or wrapping it in a `<pre>` or  the like).

**Comment by mblaney** [comment]
you could do the same thing as `get_description` and call `get_item_tags` for summary and check `attribs` yourself? It's fine if you want to add `get_content_type` though.

**Comment by fluffy-critter** [comment]
Ah! I think that provides what I need. Thanks!

**Comment by fluffy-critter** [comment]
Yep, managed to use that to provide the functionality I needed.
