### ISSUE TITLE
Author in the form "name <name@email.com" no longer recognized

### ISSUE THREAD

**Issue by flack** [simplepie/simplepie#523]
Until version 1.3.1, SimplePie correctly returned author data if it was given in the form `Author Name <author.name@somedomain.com>`, starting from version 1.4., it will only return `Author Name ` in this case. I've looked through the changelog, and the problem comes from here:

https://github.com/simplepie/simplepie/commit/162a3d3878b755c93820ea672d83b3f6ac866f8f#diff-1c04fa997590b0127d726933eb3bdb1f

i.e. author field now gets treated as HTML and `<author.name@somedomain.com>` is recognized as a tag and thrown away. Is there some way to get the old functionality back?

**Comment by mblaney** [comment]
thanks @flack, you're right that should be plain text. I changed it when adding support for microformats, which allows html for authors. I'll look into fixing it.

**Comment by mblaney** [comment]
this should be fixed now in #531
