### ISSUE TITLE
Require 2FA for those with SimplePie write access

### ISSUE THREAD

**Issue by skyzyx** [simplepie/simplepie#526]
/cc @simplepie/maintainers

I am planning on enabling the requirement that everyone who has write access to the SimplePie organization has 2FA enabled. I know that @mblaney is the new maintainer, having taken over for @rmccue. (Thank you both for giving your time to SimplePie, btw!)

In addition, in order to decrease the attack surface area, I am asking @gsnedders, @ifsnop, and @rmccue if they still need/want write access. If not, then I will cleanup the permissions and make sure that everything is in good shape security-wise.

Please respond ASAP. @rmccue and I already have 2FA enabled.

Thanks, all! :)

**Comment by rmccue** [comment]
I don't really *need* access at all, but to keep the bus factor low, happy to keep it. (I'm not too concerned about the attack surface personally; I have access to other repos which would definitely be bigger targets. 😉)

So, up to you! 👍 on requiring 2FA in any case.

**Comment by mblaney** [comment]
I'm happy to have 2FA enabled @skyzyx. Also thanks for dealing with the backlog of old issues.

...and sorry about whatever just happened with this issue being assigned, some weird key combo took over while I was typing this and started doing it's own thing!

**Comment by gsnedders** [comment]
I'm quite confused, given I certainly enabled 2FA six months ago. Weirrdddd… :\

I don't really need access at all, either.

**Comment by skyzyx** [comment]
Thank you, gentlemen.

I think I'm going to fiddle with the permissions a bit and make sure that things are cleaned-up appropriately. I just don't want anybody to think I don't like them when I take away a permission. 😄 

I'm in US/Pacific (UTC -7), and am getting ready to go to work. I'll adjust the permissions and enable force-2FA this evening. 👍

**Comment by ifsnop** [comment]
Sorry for being late, here it is UTC+2. I will enable 2FA since it was in
my to-do  a list, not just for SimplePie, but for other projects I'm
involved.

--
-- Madrid / Spain

**Comment by skyzyx** [comment]
Yo, @mblaney!

I finally got around to pulling the trigger and required 2FA on all member accounts. You ended up getting removed. Ping me once you've enabled 2FA and I'll add you back.

**Comment by mblaney** [comment]
thanks @skyzyx I've enabled 2FA now.
