### ISSUE TITLE
Clean up the demo examples

### ISSUE THREAD

**Issue by anewuser** [simplepie/simplepie#528]
"BBC Arabic", "BBC Russia", "Windows Vista Blog" and likely other examples from this page are down: https://www.simplepie.org/demo/

**Comment by anewuser** [comment]
@HardeepAsrani @mblaney  You left out a non-linked ".us".

**Comment by mblaney** [comment]
thanks @anewuser I've fixed it on the server, @HardeepAsrani you can file a PR if you like?
