### ISSUE TITLE
Error non numeric on Date.php

### ISSUE THREAD

**Issue by onigetoc** [simplepie/simplepie#534]
If i use php 7.1 there's error on de file Date.php

I modifed this line (694).
$second = round($match[6] + $match[7] / pow(10, strlen($match[7])));
For
`$second = round((int)$match[6] + (int)$match[7] / pow(10, strlen($match[7])));`

If fid this error to add a numeric value

**Comment by dd32** [comment]
Just ran into this, here's a date string, and the `$match` value which triggers the warning:
`2017-03-24T13:35:22+00:00`

`Array (
    [0] => 2017-03-24T13:35:22+00:00
    [1] => 2017
    [2] => 03
    [3] => 24
    [4] => 13
    [5] => 35
    [6] => 22
    [7] =>
    [8] =>
    [9] => +
    [10] => 00
    [11] => 00
)
`

**Comment by bhubbard** [comment]
Any updates on this?

**Comment by onigetoc** [comment]
My simple modification did work, i do not understand your's

**Comment by david-robinson-practiceweb** [comment]
This looks like it was fixed ages ago. See #458
