### ISSUE TITLE
bundled idn/idna_convert.class.php can be replaced with mso/idna-convert

### ISSUE THREAD

**Issue by glensc** [simplepie/simplepie#538]
https://github.com/simplepie/simplepie/blob/1.5/idn/idna_convert.class.php

this class official upstream is:
- packagist: https://packagist.org/packages/mso/idna-convert
- github: https://github.com/phlylabs/idna-convert

if you have any local changes those should be reported first upstream:
- https://github.com/phlylabs/idna-convert/issues
- https://github.com/phlylabs/idna-convert/pulls

**Comment by JanPetterMG** [comment]
Seems like simplepie is using `v0.5.1`
The only change is that `idna_convert()` has been renamed to `__constructor()`. [file diff](https://www.diffnow.com/?report=xuwct)

We should at least be able to update to `v0.5.2`, preferably `v0.9.1`

**Comment by blat** [comment]
This is required for PHP 7.4 support.

With current bundled idna_convert class:
```
PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in vendor/simplepie/simplepie/idn/idna_convert.class.php on line 377
PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in vendor/simplepie/simplepie/idn/idna_convert.class.php on line 393
PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in vendor/simplepie/simplepie/idn/idna_convert.class.php on line 796
PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in vendor/simplepie/simplepie/idn/idna_convert.class.php on line 935
```

**Comment by Art4** [comment]
`Mso\IdnaConvert` is renamed to `Algo26\IdnaConvert` since version 2.0, see https://github.com/algo26-matthias/idna-convert

What do you think about removing the idna folder and suggest `algo26-matthias/idna-convert:^2` in the `composer.json` like it was done with `mf2/mf2`?
