### ISSUE TITLE
get_feed_tags doesn't find SIMPLEPIE_NAMESPACE_ITUNES items

### ISSUE THREAD

**Issue by lostfocus** [simplepie/simplepie#541]
I am trying to get the `itunes:something` tags of this feed: [http://feeds.feedburner.com/nurschnittchen](http://feeds.feedburner.com/nurschnittchen)

My code is:

```PHP
$feed->set_feed_url("http://feeds.rundfunkanstalt.com/nurschnittchen");
$feed->enable_cache();

$feed->init();
$feed->handle_content_type();

$feedimage = $feed->get_feed_tags(SIMPLEPIE_NAMESPACE_ITUNES,'image');
```

And I don't get anything. I've tried it with the other tags as well - subtitle, summary, etc. - and it always returns `null`. Is that a bug or is there something wrong in my code?

**Comment by skyzyx** [comment]
What happens when you `print_r($feedimage)` or `var_dump($feedimage)`?

**Comment by vthunder** [comment]
get_feed_tags returns null.

On a lark I tried get_channel_tags and that *does* work. I don't understand the difference well enough to say if get_feed_tags should work or not.

**Comment by lostfocus** [comment]
Yeah, it works with get_channel_tags - I'm not too sure about the difference and why there are two different functions.

**Comment by Art4** [comment]
@lostfocus Is this still a problem in version 1.8.0 or we close this issue?

**Comment by lostfocus** [comment]
Yes.
I updated the code to:

```
$feed = new \SimplePie\SimplePie();

$feed->set_feed_url("http://feeds.rundfunkanstalt.com/nurschnittchen");
$feed->enable_cache();

$feed->init();
$feed->handle_content_type();

$feedimage = $feed->get_feed_tags(\SimplePie\SimplePie::NAMESPACE_ITUNES,'image');
```

Same problem. I think the main thing is that I still don't quite understand the difference between `get_feed_tags` and `get_channel_tags`
