### ISSUE TITLE
Compiled form / build script absent from newer releases

### ISSUE THREAD

**Issue by nekohayo** [simplepie/simplepie#544]
Simplepie 1.3.x used to provide the "compiled" monolithic version directly as a download on the website, which was quite convenient.

I saw this in README.markdown in the 1.5 tarball today:

> If you'd like a single monolithic file, you can run `php build/compile.php` to generate `SimplePie.compiled.php`.

...except the build dir doesn't exist in the release tarballs, so I thought it didn't exist at all, until I found it in git master. So I would think either the compiled form should also be available as a download on the website, or the build dir should be present in the released tarballs, or the README.markdown file should explain where to get it exactly.

**Comment by fabrijp** [comment]
Yeah. I'm too was wondering if this will come back ?
