### ISSUE TITLE
SimplePie not working for this feed

### ISSUE THREAD

**Issue by abhij89** [simplepie/simplepie#546]
SimplePie not working for this feed: https://www.5losttogether.com/feed/

Feed is valid:
![5losttogether](https://user-images.githubusercontent.com/15982920/31147062-415099e2-a8a6-11e7-90d5-6f336dbdc235.png)

Here is the message i get when importing this particular feed:
![simplepiedemo](https://user-images.githubusercontent.com/15982920/31147102-6ae7b9a2-a8a6-11e7-825a-33009be158b9.png)

Any reason why is this happening? This is happening with one of my user.

**Comment by skyzyx** [comment]
Because the server is misconfigured, and is telling SimplePie that the feed is HTML — which SimplePie doesn’t parse.
