### ISSUE TITLE
Mismatched Tag of Wordpress Generated RSS Feeds

### ISSUE THREAD

**Issue by jeffreyroberts** [simplepie/simplepie#554]
I am getting a ton of errors for what I see as perfectly acceptable RSS Feeds, especially considering WordPress is generating them...

    <atom:link href="https://authenticweb.academy/feed/" rel="self" type="application/rss+xml" />

Results in

    PHP Notice:  is invalid XML, likely due to invalid characters. XML error: Mismatched tag

**Comment by jeffreyroberts** [comment]
More than 20% of my WordPress feeds are failing on this one, just a heads up

**Comment by JanPetterMG** [comment]
Sorry, I'm unable to reproduce this one either, using same code as in https://github.com/simplepie/simplepie/issues/555#issuecomment-340228665.
Commit d5c7b4dffa8811fd21471108126100b6389184ca (latest `dev-master`)

It really looks like you're having some encoding issues, making the feeds invalid...

**Comment by jeffreyroberts** [comment]
Damn, im getting a bunch of these errors on the same line, I will produce a sample application now

**Comment by jeffreyroberts** [comment]
The sample app parsed it properly, so im scratching my head now, im going to go ahead and close these, I apologize for the inconvenience
