### ISSUE TITLE
PSR-4 Autoloading and PSR-1 & PSR-2 code styling

### ISSUE THREAD

**Issue by JefferyHus** [simplepie/simplepie#556]
I work on an MVC application and so I found your library to be better than the Zend one, but the only concern is that there is no PSR-4 implementation, is there any possibility to adapt your library to the PHP Standards Recommendations?

**Comment by skyzyx** [comment]
We presently use PSR-0, but I don’t see any reason we couldn’t adopt PSR-4. Both are Composer-compatible.

Do you have a PR you wanted us to look at?

**Comment by skyzyx** [comment]
Resolving while we wait for a PR.

**Comment by ColonelMoutarde** [comment]
PSR-0 are deprecated. It's PSR-4 instead of.
