### ISSUE TITLE
1.5.1 release?

### ISSUE THREAD

**Issue by trasher** [simplepie/simplepie#558]
Hello,

Could you please consider to release a 1.5.1 with latest bugfixes?

On the GLPI project, we are affected by a bug that has been fixed (and improved since); but we'd prefer not to rely on non official releases...

We plan to release a new GLPI version next week; if we can include a 1.5.1; it would be great! Sorry not to ask before, but I've forget this issue; a user just remind me.

Thanks a lot!

**Comment by mblaney** [comment]
hi @trasher here you go: #559

**Comment by trasher** [comment]
That is great; thank you very much!! :)
