### ISSUE TITLE
Yahoo-based lists no longer accessible

### ISSUE THREAD

**Issue by sophiaphillyqueen** [simplepie/simplepie#560]
I'm posting this issue to GitHub because (due precisely to the problem I'm mentioning itself) there isn't anywhere else for me to bring this issue up.

It appears all the links to the SimplePie discussion lists are broken links.

Are there any plans to fix the access to Yahoo groups ---- and/or migrate the discussion links to somewhere else (such as Google) where things _aren't_ broken?

**Comment by skyzyx** [comment]
The Yahoo group was shut down in 2010. We migrated everything to GitHub in 2009. GitHub issues is the right place to bring things up.

Was there a specific issue you were trying to solve? Or were you just letting us know we have some bit-rot?
