### ISSUE TITLE
Issues with feed

### ISSUE THREAD

**Issue by pepacobos** [simplepie/simplepie#562]
Hi, I have a feed that is validating ok in every feed validator except SimplePie.
The feed is https://www.pepacobos.es/feedpodcast/deceroalacima.xml
and the error I'm getting is: cURL error 22: The requested URL returned error: 400 Bad Request

iTunes is reading it without issues and the same applies to Stitcher. What is wrong with the feed that makes it impossible to read by SimplePie?

Thanks!

**Comment by cgoo4** [comment]
Hi -- I have the same issue.  

**w3.org** reports a valid feed here [https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fthinkr.biz%2Fcategory%2Fr%2Ffeed%2F](url). 

**SimplePie** reports a cURL 22 error here [https://simplepie.org/demo/?feed=https%3A%2F%2Fthinkr.biz%2Fcategory%2Fr%2Ffeed%2F](url).

**Comment by skyzyx** [comment]
@cgoo4: The website is intentionally blocking the "SimplePie" user agent.

```
curl -i https://thinkr.biz/category/r/feed/ -H "User-Agent: SimplePie"
HTTP/2 400 
server: nginx
date: Tue, 05 Dec 2017 01:01:32 GMT
content-type: text/html
content-length: 1393
last-modified: Wed, 25 Jan 2017 13:34:32 GMT
etag: "571-546eb4aef2a00"
host-header: 192fc2e7e50945beb8231a492d6a8024

<html>
<head>
<style type="text/css">
	body{background-color:#f4f9fa}
	.centered{text-align:center}
	.container{border:1px solid #e2e2e2;width:1200px;margin:50px auto}
	.header{height:120px;background-color:#fbfdfd;padding-top:40px;}
	.header h1{font: bold 130% Arial, Helvetica, sans-serif;
color:#5278af;margin:0;padding:0}
	.header h2{font: bold 80% Tahoma, Verdana, sans-serif;
color:#5278af;margin:0;padding:0}
	.line{height:15px;background-color:#eef6f7}
	.error-container{background-color:#fff;font:normal 80% Tahoma, Verdana,
sans-serif;color:#000;text-align:justify;padding:30px}
	.error-container li{padding-bottom:10px}
	.error-container a:link, .error-container a:visited{font:normal 100%
Tahoma, Verdana, sans-serif;color:#5278af;text-decoration:underline}
	.error-container a:hover{color:#5278af;text-decoration:none}
</style>
<title>Access Denied</title>
</head>
<body>
<div class="centered">
	<div class="container">
		<div class="header">
			<h1>The page you are trying to access is restricted due to a security rule.</h1>
	<br>
			<h2>If you believe the security rule is affecting the normal operation of your website, contact your host support team and provide detailed instructions how to recreate this error.
<br>
They will be able to assist you with rectifying the problem and adjusting the security configuration if needed.</h2>
		</div>
	</div>
</div>

</body>
</html>
```

You can use [SimplePie::set_useragent()](https://github.com/simplepie/simplepie/blob/7f832bec90e68e91ae9b852db1ef71de6c0c9f7c/library/SimplePie.php#L1112-L1115) to change the user agent to something without the word "SimplePie" in it.

**Comment by skyzyx** [comment]
@pepacobos: When I add "SimplePie" to the user agent, I get back an _identical_ error message.

```
curl -i https://www.pepacobos.es/feedpodcast/alacima.xml -H "User-Agent: SimplePie"
HTTP/2 400 
server: nginx
date: Tue, 05 Dec 2017 01:04:52 GMT
content-type: text/html
content-length: 1393
last-modified: Wed, 25 Jan 2017 13:34:32 GMT
etag: "571-546eb4aef2a00"
host-header: 192fc2e7e50945beb8231a492d6a8024

<html>
<head>
<style type="text/css">
	body{background-color:#f4f9fa}
	.centered{text-align:center}
	.container{border:1px solid #e2e2e2;width:1200px;margin:50px auto}
	.header{height:120px;background-color:#fbfdfd;padding-top:40px;}
	.header h1{font: bold 130% Arial, Helvetica, sans-serif;
color:#5278af;margin:0;padding:0}
	.header h2{font: bold 80% Tahoma, Verdana, sans-serif;
color:#5278af;margin:0;padding:0}
	.line{height:15px;background-color:#eef6f7}
	.error-container{background-color:#fff;font:normal 80% Tahoma, Verdana,
sans-serif;color:#000;text-align:justify;padding:30px}
	.error-container li{padding-bottom:10px}
	.error-container a:link, .error-container a:visited{font:normal 100%
Tahoma, Verdana, sans-serif;color:#5278af;text-decoration:underline}
	.error-container a:hover{color:#5278af;text-decoration:none}
</style>
<title>Access Denied</title>
</head>
<body>
<div class="centered">
	<div class="container">
		<div class="header">
			<h1>The page you are trying to access is restricted due to a security rule.</h1>
	<br>
			<h2>If you believe the security rule is affecting the normal operation of your website, contact your host support team and provide detailed instructions how to recreate this error.
<br>
They will be able to assist you with rectifying the problem and adjusting the security configuration if needed.</h2>
		</div>
	</div>
</div>

</body>
</html>
```

You can work around it the same way. Both sites appear to be using the same framework, which is (_incorrectly_) blocking it by user agent. Instead, they should _throttle_ requests from the same IP that contain _SimplePie_ in their user agent. But alas.

**Comment by skyzyx** [comment]
They both appear to be WordPress sites. I know that WordPress isn't blocking SimplePie in core, so it must be one of the plugins that is installed. If we can figure out which plugin it is, we can reach out to them.

**Comment by pepacobos** [comment]
@skyzyx my feed is not inside any Wordpress installation.

**Comment by cgoo4** [comment]
@skyzyx Thanks for the feedback.  I've tried systematically deactivating each plugin and re-trying Simple Pie, but I still consistently get the rCurl 22 error message.  Aside from the plugins, it's a straight-forward Wordpress 4.9.1 installation with the twenty-seventeen theme.  Another site is rejecting my feed because it returns a SimplePie error despite being valid on w3.org.

Re set_useragent, where would I go in Wordpress to do that?

**Comment by pepacobos** [comment]
@cgoo4 I am almost sure it is not a WordPress issue, as I said before my feed is not inside a WordPress installation so it shouldn't be related to that.
I am using my feed for a podcast and it is working inside iTunes, Stitcher,... no problema at all. But iVoox (another podcast app) uses SimplePie to verify feeds and is rejecting mine. :(

**Comment by cgoo4** [comment]
**@pepacobos** Yes, I've checked with SiteGround who host my site, and they don't see any issues either with the Wordpress site.

**Comment by pepacobos** [comment]
@cgoo4 that's our issue! We are both with Siteground. There should be something in their server that is preventing our feed to show correctly...

**Comment by cgoo4** [comment]
**@pepacobos** SiteGround TechSupport has now resolved this: "I looked into your case and noticed that a ModSecurity rule is triggered when the SimplePie user agent runs a curl request towards your feed. I disabled it which seems to have resolved the issue as you can check in the screenshot."

**Comment by skyzyx** [comment]
Good, I’m glad you got it worked out. 👌🏼
