### ISSUE TITLE
Feed not importing HTML content from feed items

### ISSUE THREAD

**Issue by sfatfarma** [simplepie/simplepie#568]
Hello,

I use the latest version of SimplePie (1.5), and for a specific feed, it is not importing the feed content correctly.

The feed URL is: http://webkinghost.blogspot.in/feeds/posts/default

When I call $item->get_content() for returned feed list, it returns only the textual content, with no HTML at all.

Thank you for your help.

Regards,
Szabi.

**Comment by skyzyx** [comment]
http://simplepie.org/demo/?feed=http%3A%2F%2Fwebkinghost.blogspot.in%2Ffeeds%2Fposts%2Fdefault

Links are there. Images are there. Line breaks are there.

For security reasons, SimplePie strips out `<iframe>` elements by default. You can use [`SimplePie::strip_htmltags()`](https://github.com/simplepie/simplepie/blob/master/library/SimplePie.php#L1167-L1178) to adjust which tags are stripped.
