### ISSUE TITLE
Lattitude and Longitude Fail regex if no decimals are present

### ISSUE THREAD

**Issue by andrewg211** [simplepie/simplepie#571]
Hi Guys,

Could you change the regex in the SimplePie_Item class so that a lattitude and longitude with no decimals are allowed.

The get_longitude and get_latitude method contain the following regex to validate a lattitude and longitude value:

`((?:-)?[0-9]+(?:\.[0-9]+)) ((?:-)?[0-9]+(?:\.[0-9]+))` 

If it could be changed to this would be great

`((?:-)?[0-9]+(?:\.[0-9]+)*) ((?:-)?[0-9]+(?:\.[0-9]+)*)`

Thanks!!

**Comment by skyzyx** [comment]
Do you have an example of a spec which defines lat/long without decimals?
