### ISSUE TITLE
demo folder dont exists

### ISSUE THREAD

**Issue by yanivz** [simplepie/simplepie#574]
in readme its says to go to "demo" folder but it dont exists there

**Comment by skyzyx** [comment]
https://github.com/simplepie/simplepie/tree/master/demo

**Comment by neralex** [comment]
I have same issue. The folder doesn't exist after downloading the zip directly from github:

As tree I get this result:

idn
library
.travis.yml
autoloader.php
composer.json
db.sql
LICENSE.txt
README.markdown
