### ISSUE TITLE
Ampersand in title containing CDATA and HTML entities is replaced 

### ISSUE THREAD

**Issue by e-dschungel** [simplepie/simplepie#575]
If the title contains CDATA which contains HTML entities like this
`<title><![CDATA[Entertain Jahresr&uuml;ckblick 2017]]></title>`
SimplePie replaces the ampersand with the corresponding HTML entity like this 
`Entertain Jahresr&amp;uuml;ckblick 2017`
which breaks the other HTML entity `&uuml;` Is there something wrong with the feed or is it a bug?

Example feed: http://www.phpman89.de/t_home_10.xml
Versions: PHP 7.2.1 + SimplePie 1.5.1

**Comment by mblaney** [comment]
Hi @e-dschungel SimplePie escapes special characters in RSS titles. It's an ambiguous part of the spec, but that's the way SimplePie has interpreted it for a long time.

**Comment by e-dschungel** [comment]
Hi @mblaney Ok, so what is the recommended way to get a correctly encoded UTF8 title? Running two times `html_entity_decode($title, ENT_COMPAT | ENT_HTML401, "UTF-8"); ` seems a bit odd to me.

**Comment by mblaney** [comment]
@e-dschungel you could leave off the CDATA tags? if everything's encoded already you don't need them.

**Comment by e-dschungel** [comment]
@mblaney Ok, now I got it, the feed is broken. Thanks!
