### ISSUE TITLE
SimplePie - XML_ERR_NAME_REQUIRED at line 1257, column 147

### ISSUE THREAD

**Issue by DonaldLaborde** [simplepie/simplepie#577]
Hi there,
I tried the Simplepie demo on the Simplepie web page with the RSS URL `http://usjf.com/blogs/rss.xml ` and I received the following error : `http://usjf.com/blogs/rss.xml is invalid XML, likely due to invalid characters. XML error: XML_ERR_NAME_REQUIRED at line 1257, column 147`

I would like to be happy if you could tell me exactly what's wrong with that URL ?
Thanks in advance.

**Comment by mblaney** [comment]
Hi @DonaldLaborde the error message is pretty helpful in this case, there's an unescaped ampersand at that location.

**Comment by DonaldLaborde** [comment]
Hi mblaney and thanks for your answer.
What did you do to know it is an unescaped ampersand and what to do now ?

**Comment by skyzyx** [comment]
If you look at the actual contents of the file, at _“line 1257, column 147”_…

> NY Open 2017 - Timeline & The Order of Fights

There's the ampersand. And it's not encoded. 👍

>  […] and what to do now?

If you own the feed, you need to encode it. If you don't own the feed, you should reach out to the owner of the website and ask them to fix it.

**Comment by DonaldLaborde** [comment]
Thanks a lot skyzyx. 
I will try to reach out the owner but how did you do to see into the file. I'm not able to download it ?

**Comment by mblaney** [comment]
@DonaldLaborde why can't you download it? You should be able to just view it in a web browser, try view source if it doesn't show you the raw format.

**Comment by DonaldLaborde** [comment]
Another idea would be to modify my php file ?

**Comment by skyzyx** [comment]
I mean, I just used curl.

**Comment by DonaldLaborde** [comment]
I think your server is on your Mac ?
Mine is hosted by a Internet Service Provider.
I use MWFeedParser in my app.
