### ISSUE TITLE
simplepie.inc fatal error in newspage plugin for Wordpress

### ISSUE THREAD

**Issue by JCHobbes** [simplepie/simplepie#579]
I have been using an old Wordpress plugin called Newspage on an existing site for years. On a new installation of Wordpress on a different site, I get the following error:

Plugin could not be activated because it triggered a fatal error.

Parse error: syntax error, unexpected 'new' (T_NEW) in /home/jchobbes/public_html/wp-content/plugins/newspage/simplepie.inc on line 720

While I am coding illiterate, I looked at the file with a text editor, but had no idea how to fix it.

Can anyone please help?

**Comment by nathanphatti** [comment]
I get the same error, using simplepie.inc from php. My hosting site migrated my. Domain to a new server .I have barely iupdated the code in 5 years , getting rusty, hoping to find a solution here.
