### ISSUE TITLE
Embed [audio/mpeg] elements in parsed feed?

### ISSUE THREAD

**Issue by orschiro** [simplepie/simplepie#581]
Dear all, 

Just discovered simeplie and love it!

I tested it by parsing and displaying this feed: http://feed.informer.com/digests/DSVW5NQPOX/feeder.rss

It contains [audio/mpeg] elements which can theoretically be displayed. 

Example: http://www.feedbucket.com/?src=http%3A%2F%2Ffeed.informer.com%2Fdigests%2FDSVW5NQPOX%2Ffeeder.rss

Could you also add support for these elements so that users can quickly access and download them?

Other than that I really appreciate the simplicity of the displayed content!

**Comment by skyzyx** [comment]
You're looking for the `get_enclosure()` method on on the `SimplePie_Item` class.
