### ISSUE TITLE
Stable version for PHP 5.5.9

### ISSUE THREAD

**Issue by george-viaud** [simplepie/simplepie#582]
We're using simplepie on a production environment but had our version set to dev which is now causing complaints regarding php version (5.5.9, requires 5.6).

What version of simplepie can we specify for now (until we're able to safely upgrade to latest PHP) in our composer.json ?

Thank you

**Comment by george-viaud** [comment]
Seems like 1.5.1 is happy to work with my version of PHP - is this latest release w/ compatibility?  Thank you

**Comment by george-viaud** [comment]
When specifying the `dev-master` version in composer.json I receive the following:

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for simplepie/simplepie dev-master -> satisfiable by simplepie/simplepie[dev-master].
    - simplepie/simplepie dev-master requires php >=5.6.0 -> your PHP version (5.5.9) does not satisfy that requirement.

**Comment by JanPetterMG** [comment]
Why do you even try to use `dev-master` in production? (sorry for asking)

Latest stable, 1.5.1 requires php>=5.3.0
[Packagist](https://packagist.org/packages/simplepie/simplepie) is a great tool for this kind of information...
