### ISSUE TITLE
No items found in https://links.danrigby.com/feed.xml

### ISSUE THREAD

**Issue by mknotzer** [simplepie/simplepie#583]
The file looks ok, all other rss files are working

```php
$feed = new SimplePie();
$feed->set_feed_url("https://links.danrigby.com/feed.xml");
$feed->enable_cache(false);
$feed->init();
foreach ($feed->get_items() as $item) {
  // no items 
}
```

**Comment by abhij89** [comment]
It works here: http://simplepie.org/demo/?feed=https%3A%2F%2Flinks.danrigby.com%2Ffeed.xml, so may be you did something wrong or missed something or configuration may have some issues.

**Comment by abhij89** [comment]
make sure curl is working

**Comment by mknotzer** [comment]
So many years I've been using Version 1.2 successfully with more than 30 feeds.
I already upgraded to the current version to make the new feed work without success. 
IMHO it can't be a configuration issue because more than 30 feeds are working.
