### ISSUE TITLE
cURL error 18: transfer closed with 44507 bytes remaining to read

### ISSUE THREAD

**Issue by sfatfarma** [simplepie/simplepie#584]
http://simplepie.org/demo/?feed=http%3A%2F%2Ffeeds.ezinearticles.com%2Fcategory%2FHome-and-Family%3APregnancy.xml

Feed is: http://feeds.ezinearticles.com/category/Home-and-Family:Pregnancy.xml

Feed is valid: https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Ffeeds.ezinearticles.com%2Fcategory%2FHome-and-Family%3APregnancy.xml

Please let me know if this can be fixed somehow. 

Thank you.

**Comment by skyzyx** [comment]
Not sure what's up with the demo machine, but it loads fine for me locally.

**Comment by sfatfarma** [comment]
Well, odd, because I also get this error on my server...
