### ISSUE TITLE
Bypass GDPR

### ISSUE THREAD

**Issue by Colir** [simplepie/simplepie#587]
HI.
I've just found a problem with Tumblr feeds and the GPDR.
When visiting rss feeds, we are redirect to

https://www.tumblr.com/privacy/consent

You can try with this feed: http://funnygamememes.tumblr.com/rss

I know that it's a restriction from Tumblr but i ask me if there are any solution like this one for Tiny Tiny RSS parser
https://github.com/GregThib/ttrss-tumblr-gdpr

Thanks you

**Comment by JanPetterMG** [comment]
Works fine in the [Demo](https://simplepie.org/demo/?feed=http%3A%2F%2Ffunnygamememes.tumblr.com%2Frss)

Just change your user-agent.
It didn't redirect me when I clicked the link in the browser, but when I changed my user-agent to something else, I was redirected to the tumblr dashboard...

**Comment by max-te** [comment]
To be clear, what do you suggest setting the UA to? Because when I clear cookies and cache in my browser (Firefox) and got to http://funnygamememes.tumblr.com/rss, I get redirected to https://www.tumblr.com/privacy/consent?redirect=http%3A%2F%2Ffunnygamememes.tumblr.com%2Frss .
