### ISSUE TITLE
Redis - Predis cache

### ISSUE THREAD

**Issue by pierrocknroll** [simplepie/simplepie#588]
Hi and thanks for your great tool,

There are 2 drivers for Redis in PHP : PhpRedis and Predis, and you use PhpRedis.
I use Predis so I have a `Class 'Redis' not found` error.

Do you think it's possible to support both ?

Thanks

**Comment by skyzyx** [comment]
We would be willing to review a PR, but SimplePie is not under _active_ development right now.

Let us know if you would like to provide some code which supports this.
