### ISSUE TITLE
Some feed url is not working [URGENT]

### ISSUE THREAD

**Issue by vishal2947** [simplepie/simplepie#594]
Hello,

We are using this library in our prod servers, however, for few URLs it is returning empty response and these URLs are working fine on other RSS feed readers.
For Ex:
http://beyondtheoffice.com/feed/

This will always return empty response. Please help me.

**Comment by JanPetterMG** [comment]
Btw, the [demo](http://simplepie.org/demo/?feed=http%3A%2F%2Fbeyondtheoffice.com%2Ffeed%2F) returns the following:
`cURL error 22: The requested URL returned error: 400 Bad Request`

**Comment by skyzyx** [comment]
@vishal2947: This has been answered many times.

https://github.com/simplepie/simplepie/issues?utf8=✓&q=user+agent
