### ISSUE TITLE
XML parsing not in chunks, parser out of memory

### ISSUE THREAD

**Issue by amanmanglik** [simplepie/simplepie#598]
This started as a wordpress issue for me but the issue roots from SimplePie so reporting here as well. SimplePie reads xml file as a single large chunk instead of multiple chunks and the parser goes out of memory because there seems to be a per chunk memory limit in the underlying php xml_parse function.

Code in question - https://github.com/simplepie/simplepie/blob/master/library/SimplePie/Parser.php#L167-L172

Potential fix and more context here - https://wordpress.org/support/topic/xml-parsing-not-in-chunks-parser-out-of-memory/

**Comment by skyzyx** [comment]
Yeah… this will probably never be fixed in this repository. It's too fundamental of a change for how SimplePie was designed 15 years ago. :(

Happy to consider a patch, if you wanted to provide one.
