### ISSUE TITLE
A feed could not be found at ... the status code is `200` and content-type is `text/html; charset=UTF-8`

### ISSUE THREAD

**Issue by AndreFabris** [simplepie/simplepie#601]
"A feed could not be found at `http://appsforce.back/mywiki/api.php?action=feedrecentchanges&feedformat=atom`; the status code is `200` and content-type is `text/html; charset=UTF-8`"

However in the browser I get this when I use the same link:

<feed xml:lang="hr"><id>http:///mywiki/api.php?action=feedrecentchanges&feedformat=atom</id><title>AppsForce  - Nedavne promjene [hr]</title><link rel="self" type="application/atom+xml" href="http:///mywiki/api.php?action=feedrecentchanges&feedformat=atom"/><link rel="alternate" type="text/html" href=""/><updated>2019-01-07T12:19:24Z</updated><subtitle>Na ovoj stranici možete pratiti nedavne promjene u wikiju.</subtitle><generator>MediaWiki 1.29.1</generator></feed>

Also 

A feed could not be found at `http://appsforce.back/myblog/?feed=atom`; the status code is `200` and content-type is `text/html; charset=UTF-8

I am getting an atom file to download which has this content

<?xml version="1.0" encoding="UTF-8"?><feed
  xmlns="http://www.w3.org/2005/Atom"
  xmlns:thr="http://purl.org/syndication/thread/1.0"
  xml:lang="en-US"
  xml:base="http://appsforce.back/myblog/wp-atom.php"
   >
	<title type="text">AppsForce</title>
	<subtitle type="text">Just another WordPress site</subtitle>

	<updated>2018-06-01T14:07:01Z</updated>

	<link rel="alternate" type="text/html" href="http://appsforce.back/myblog" />
	<id>http://appsforce.back/myblog/?feed=atom</id>
	<link rel="self" type="application/atom+xml" href="http://appsforce.back/myblog/?feed=atom" />

	<generator uri="https://wordpress.org/" version="4.8.2">WordPress</generator>
	<entry>
		<author>
			<name></name>
					</author>
		<title type="html"><![CDATA[Hello world!]]></title>
		<link rel="alternate" type="text/html" href="http://appsforce.back/myblog/?p=1" />
		<id>http://localhost/myblog/?p=1</id>
		<updated>2017-06-27T15:04:08Z</updated>
		<published>2017-06-27T15:04:08Z</published>
		<category scheme="http://appsforce.back/myblog" term="Uncategorized" />		<summary type="html"><![CDATA[Welcome to WordPress. This is your first post. Edit or delete it, then start writing!]]></summary>
		<content type="html" xml:base="http://appsforce.back/myblog/?p=1"><![CDATA[<p>Welcome to WordPress. This is your first post. Edit or delete it, then start writing!</p>
]]></content>
			<link rel="replies" type="text/html" href="http://appsforce.back/myblog/?p=1#comments" thr:count="1"/>
		<link rel="replies" type="application/atom+xml" href="http://appsforce.back/myblog/?feed=atom&#038;p=1" thr:count="1"/>
		<thr:total>1</thr:total>
		</entry>
	</feed>

I am not sure why this does not work while using external sites such as
http://appsforce.back/mywiki/api.php?action=feedrecentchanges&feedformat=atom
with the same code works fine.

**Comment by skyzyx** [comment]
It's because `text/html` indicates that this is an HTML file, and not a feed. You need to use `$simplepie->force_feed();` before calling `$simplepie->init();`.

**Comment by AndreFabris** [comment]
That is fine. I thought I did force it but on check I did not. However now that feed is forced, I get the following error
http://appsforce.back/myblog/?feed=atom is invalid XML, likely due to invalid characters. XML error: EntityRef: expecting ';' at line 26, column 126

It is funny I get the exactly same error with a different feed:
http://appsforce.back/mywiki/api.php?action=feedrecentchanges&feedformat=atom is invalid XML, likely due to invalid characters. XML error: EntityRef: expecting ';' at line 26, column 126

Should I open as a new issue? Any ideas what I can do here?

Many thanks!

**Comment by JanPetterMG** [comment]
I'm getting those invalid XML/characters on a fairly large number of feeds. Often it's one of the `<item>`s containing unencoded characters.
The error usually disappears after some time, depending on how often the feed is updated. Usually all existing `<item>`s needs to be dropped and replaced with new ones before the feed can be parsed successfuly.

Is there any library/tools available to "fix" such common errors?

About 50k of my feeds are affected by this issue on a daily basis, so I'm looking for a php library  that can somehow "fix" most of them, alternatively is capable of dropping individual `<item>`s.

**Comment by skyzyx** [comment]
I'm going to close this for now. Please add a comment to this post once you have a more narrowed-down test case.

Thanks!
