### ISSUE TITLE
Show normal download links on demo page

### ISSUE THREAD

**Issue by anewuser** [simplepie/simplepie#602]
`https://www.simplepie.org/demo` still uses the old `embed` tag to attempt to display media files with a plugin, and there's no way to download the files.

Could you make the media information at the end of each post (filetype and size) link directly to the media files, so that they can be downloaded?

Example page: `https://www.simplepie.org/demo/?feed=http%3A%2F%2Fwww.darkhorizonsradio.com%2Fpodcasts%2Fshows%2FDark_Horizons.xml`

**Comment by skyzyx** [comment]
We don't actually have access to the demo page anymore. The WordPress team took over hosting the SimplePie website back in 2010, and I haven't been able to get control back yet.

Working on it, but it probably won't happen soon.

**Comment by anewuser** [comment]
>The WordPress team took over hosting the SimplePie website back in 2010

?

https://github.com/simplepie/simplepie/issues/528

**Comment by mblaney** [comment]
Hi @skyzyx thanks for all your triaging work. I've got ftp access to simplepie.org if you want it.

**Comment by mblaney** [comment]
Hi @anewuser, it's not something that needs "fixing" since it's just a demo site that renders the content in a particular way. I think it's good enough as a demo and don't have any interest in changing it myself.

**Comment by skyzyx** [comment]
Also, we don't _currently_ have access to change it. We gave the website hosting over to WordPress back in 2009 who offered to take it over, but we haven't gotten it back yet.

**Comment by skyzyx** [comment]
Oh. @mblaney: Do you have access?

**Comment by anewuser** [comment]
It's okay if you don't want to change it. It's just that Firefox removed the built-in feed preview feature versions ago, and I've been using that demo page as a replacement for it since then.

@skyzyx see #528.

**Comment by mblaney** [comment]
@skyzyx yes just tried the credentials I have and they still work, let me know if you want them.
