### ISSUE TITLE
Windows Server 2016, PHP 7.1 - SimplePie 1.52 fails silently, displays nothing

### ISSUE THREAD

**Issue by FrankEBailey** [simplepie/simplepie#603]
SimplePie has suddenly stopped working. It displays no errors even with full error display turned on, it just does nothing. No errors appear in the PHP log file either.

I'm running Win 2016 Server and my site is on PHP 7.1.

The feed is definitely valid and working, I have tested it on other servers and in a browser on the same machine. Any help or suggestions for how to troubleshoot this issue would be much appreciated.

**Comment by JanPetterMG** [comment]
Have you tried to run Simplepie in an isolated environment?
Had a strange, similar issue a while ago, see #476

**Comment by skyzyx** [comment]
So, do you have full error reporting enabled? e.g.,

```php
error_reporting(-1);
```

**Comment by skyzyx** [comment]
Closing due to no response.
