### ISSUE TITLE
Usatoday.com feeds not seen as feeds

### ISSUE THREAD

**Issue by Fmstrat** [simplepie/simplepie#605]
The USA Today feeds aren't parseed by SimplePie, but are by most RSS readers: http://rssfeeds.usatoday.com/usatoday-newstopstories&x=1

It seems to make it into the init loop, but throws the "this is not a feed" error.

**Comment by JanPetterMG** [comment]
Works just fine in the [Demo](http://simplepie.org/demo/?feed=http%3A%2F%2Frssfeeds.usatoday.com%2Fusatoday-newstopstories%26x%3D1)...

I can't see anything wrong, but you could always try inserting `$simplepie->force_feed();`, just before calling `$simplepie->init();`
