### ISSUE TITLE
date_w3cdtf bug in Date.php

### ISSUE THREAD

**Issue by MarkDHamill** [simplepie/simplepie#606]
On line 694 of Parse/Date.php:

`			$second = round($match[6] + $match[7] / pow(10, strlen($match[7])));`

if $match[7] is a null string (not a number), i.e. a parsed date like this:

2019-01-29T12:59:41-05:00

You get this warning:

> Warning: A non-numeric value encountered in /Applications/XAMPP/xamppfiles/htdocs/wordpress/wp-includes/SimplePie/Parse/Date.php on line 694

The workaround is something like this on the lines before:
```

			if ($match[7] == '')
			{
				$match[7] = 0;
			}		
```	
I tested this with phpBB's Atom feed, which triggered the error.

https://www.phpbb.com/community/feed

I don't believe the date specification requires a precision that exceeds the second level.

**Comment by skyzyx** [comment]
A proper PR would certainly be welcome… against the _current_ version of SimplePie. 👍
