### ISSUE TITLE
cURL error 28: Operation timed out after 10000 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by JimmyOne** [simplepie/simplepie#608]
Hi SimplePie Team,

Demo not working for http://www.worldsquash.org/ws/feed
Also not working on server with same error.
Working fine with cURL.
Any idea?

Thanks

**Comment by abhij89** [comment]
Your server has a very bad response time, it's taking over 15 seconds to respond with header. Please fix the time as simplepie and other validators are failing because of timeout.

**Comment by JimmyOne** [comment]
Not mine, but I will inform the company of a possible latency problem.
Thanks.
