### ISSUE TITLE
Patch to support BusinessWire.com

### ISSUE THREAD

**Issue by escallonia** [simplepie/simplepie#609]
Our processing of BusinessWire feeds broke around 2019/02/27. 

For example:
http://feeds.businesswire.com/BW/Electronic_Design_Automation-rss

The attached patch enabled me to resume processing BusinessWire. I submitted this as pull request #610 https://github.com/simplepie/simplepie/pull/610

[patch.txt](https://github.com/simplepie/simplepie/files/2998476/patch.txt)

**Comment by mblaney** [comment]
Hi @escallonia did you try asking them to fix it?

**Comment by escallonia** [comment]
> 
> 
> Hi @escallonia did you try asking them to fix it?

Will do and update here. First I resolved the outage in my app!

**Comment by escallonia** [comment]
The is in the response headers from BusinessWire.com:
`Content-Type: application/rss+xml, text/xml; charset=UTF-8`

1. Is this header "incorrect" and something they should change? What if they don't?
2. Does it harm SimplePie to support this header?
3. Or does it improve SimplePie to support this header?

**Comment by skyzyx** [comment]
I feel like we need to draw a line somewhere, else SimplePie become more of a mess.

```http
Content-Type: application/rss+xml, text/xml; charset=UTF-8
```

This is completely invalid. We could shoe-horn it in, but what about the next set of completely broken headers? I worry about opening this door even more than it has been.

IMO, it's more appropriate for you to maintain your own patch, rather than having the development team accept + own this change upstream. I vote no.

**Comment by escallonia** [comment]
Thanks for the comment. I'll try force-feed() and update you here. Feel free to let this sit until I update you.

**Comment by escallonia** [comment]
@skyzyx and @mblaney and others, would you mind upvoting the answer [here](https://stackoverflow.com/questions/55346887/comma-separated-list-valid-in-content-type-header), or posting an answer? Or I will cite both this thread and stackoverflow when asking BusinessWire to fix it.

**Comment by escallonia** [comment]
@mblaney, @skyzyx , I have started a dialog with BusinessWire on this topic and your feedback.

**Comment by mblaney** [comment]
@escallonia thanks for reaching out to them. I agree with @skyzyx all for being flexible but this is taking things too far.
