### ISSUE TITLE
PHP errors with non-latin feeds

### ISSUE THREAD

**Issue by vadimbk** [simplepie/simplepie#612]
Hello, 
I'm using your excellent product in my last project.
Analyzing the log files, I saw a huge number of errors for all non-latin feeds and log files became huge.
Example of output:
`2019/05/25 13:15:15 [error] 1058#1058: 2074604 FFastCGI sent in stderr: "PHP message: PHP Notice: https://***** is invalid XML, likely due to invalid characters. XML error: ******* (a plenty of errors from SimplePie) in /var/www//ftr/libraries/simplepie/library/SimplePie.php on line 1496" while reading response header from upstream`
I have rolled back to version 1.3.1 - and all errors gone.
The problem lies in Parser.php, because public function parser() contains parameters which brake the process - html entities.
Some of the feeds mentioned above passed w3 test, some - no. But error appears in *all* non-latin feeds/pages.
As a temporary solution I have replaced the function with one from ver.1.3.1 and it works well without any error.

The question is: maybe algorithm of parsing contains an error? 

Thanks a lot for a fast reply.

**Comment by mblaney** [comment]
hi @vadimbk do you want to share an example feed so I can take a look?

**Comment by vadimbk** [comment]
e.g. https://www.eurointegration.com.ua/rss/

**Comment by mblaney** [comment]
I don't get any errors with that feed. I'm happy to help fix the problem you're having but might have to try and narrow it down rather than rolling all the way back to 1.3.1

**Comment by vadimbk** [comment]
SimplePie is a part of a large project (FiveFilters full text RSS). I'll launch test server later today and give you all the root credentials. Please email me: vadim.khomakha (at) me.com.

**Comment by mblaney** [comment]
sorry I just meant that if you want to have another go with the current version I'm happy to look at what you find. That would require you isolating the problem to a more repeatable test case.

**Comment by skyzyx** [comment]
I'm going to close this for now. Please add a comment to this post once you have a more narrowed-down test case.

Thanks!
