### ISSUE TITLE
[BUG] get_date() always returns 1 January 1970, 12:00 am

### ISSUE THREAD

**Issue by sfatfarma** [simplepie/simplepie#614]
#### Description

get_date() function always returns 1 January 1970, 12:00 am for this feed:
https://www.srbijadanas.com/rss.xml

I think it is because the date from the feed is in this format: 
Utorak, June 25, 2019 - 19:32

#### Steps to Reproduce

Import the date using 
$date = $item->get_date();

#### Expected Behavior

The correct date to be returned from the feed items 

#### Actual Behavior

 1 January 1970, 12:00

#### Environment

Linux, Windows - same behavior

Thank you!

**Comment by skyzyx** [comment]
Not a bug. The RSS spec specifically says that timestamps must be in RFC 822 format.
