### ISSUE TITLE
[BUG] get_categories() method only returns last category in the list

### ISSUE THREAD

**Issue by BurakBoz** [simplepie/simplepie#615]
#### Description

When XML have multiple categories like this

```
<category term="Web Design"/>
<category term="WordPress"/>
<category term="Acne Threatment"/>
```

get_categories() method returns only the last item. 
For this example it will be "Acne Threatment"

#### Steps to Reproduce

1. Go to blogspot and create a post contains multiple categories
2. https://your.blogspot.com/feeds/posts/default
3. parse this

#### Expected Behavior

All categories should be usable.

#### Actual Behavior

Only the last category returns.

#### Environment

Mac Os X, PHP 7.2.15

**Comment by skyzyx** [comment]
Have a code sample? "parse this" needs more detail.
