### ISSUE TITLE
[BUG] Redis options not set - default to expire 0

### ISSUE THREAD

**Issue by greg606** [simplepie/simplepie#616]
#### Description

When using Redis Cache there is no way to set redis cache expiry. 
Url params are not taken into account

#### Steps to Reproduce

```php
$remoteFeed = new SimplePie();
$remoteFeed->set_cache_location('redis://localhost:6379/?timeout=3600&prefix=sp_&dbIndex=0');
$remoteFeed->set_cache_duration(3601);
$remoteFeed->set_feed_url('any url');
$remoteFeed->init();
```
#### Expected Behavior

TTL of redis key not -1

#### Actual Behavior

TTL of redis key is -1

#### Possible Solutions
https://github.com/simplepie/simplepie/blob/11ddaed291ccd1b2628eef433a6bef58a1e4f920/library/SimplePie/Cache/Redis.php#L63
is always null 
also constructor has wrong phpdoc

#### Environment
dev-master
php-redis on linux mint, php 7.3

**Comment by AnTheMaker** [comment]
This still isn't fixed yet, is it? I'm running into the same bug...

**Comment by AnTheMaker** [comment]
Made a PR to fix this bug, hope it get's merged!

**Comment by Art4** [comment]
With SimplePie 1.8.0 it will be possible to set Redis as a PSR-16 cache implementation and modify there the cache expiry.
