### ISSUE TITLE
Getting feeds from a blog using Meta Tag Redirecting

### ISSUE THREAD

**Issue by mnaas** [simplepie/simplepie#618]
####  Is your feature request related to a problem?
When a blog or a website is using Meta Tag Redirect, SimplePie dos not follow with the redirect to get the feeds.

I am not an expert about dealing with such things, so I am just asking if this is something could be done!

Thanks

**Comment by skyzyx** [comment]
Won't fix. This is because SimplePie is a feed parser, and not an HTML parser. SimplePie will follow HTTP-level (301, 302) redirects, but will not parse the HTML because it is not a web browser.
