### ISSUE TITLE
[BUG] Parse error on PHP versions < 5.6

### ISSUE THREAD

**Issue by prbt2016** [simplepie/simplepie#624]
## Description 
After successful setup of SimplePie version 1.5.3(downloaded using git clone) on PHP 5.3.29, I encountered with the following Parse error i.e

Parse error: syntax error, unexpected '*' in /{{path}}/{{to}}/{{simplepie}}/library/SimplePie/Parse/Date.php on line 727

#### Steps to Reproduce

1. Try to add any valid RSS feed URL or visit any of the given RSS feed URL's .
2. After visiting you will get the above error if PHP version is less than 5.6 and RSS feed wont be loaded.

#### Environment
SimplePie version - 1.5.3
PHP version - 5.3.29
Apache version -2.2.34
O.S - Centos 6.4 Final

####Cause 
On line 127 is the following code i.e $second = round((int)$match[6] + (int)$match[7] / (10 ** strlen($match[7]))); . The symbol  '**' is supported since PHP 5.6.0 and minimum mentioned requirement here :
https://github.com/simplepie/simplepie is 5.3.0+.

Has the script requirement changed to PHP 5.6 or could you please fix this by adding a fix for PHP versions less than 5.6 by using pow() function that was used earlier ?

**Comment by mblaney** [comment]
thanks @prbt2016 SimplePie now requires PHP 5.6 or newer.
