### ISSUE TITLE
[BUG] does not show image of atom file with ebay

### ISSUE THREAD

**Issue by manuelnex** [simplepie/simplepie#629]
Hallo,
if I put an RSS feed it works fine, but if I put an atom feed it doesn't show the image.
on this page I entered the feed rss

https://www.trovacuccioli.com/-42/posts/2-cani/169-grand-anglo-francais-tricolore/

while in this the atom feed
https://www.trovacuccioli.com/-42/posts/3-gatti/245-cymric/
as you can see the image does not appear.

the two feeds are as follows:
ATOM:
https://epndeals.api.ebay.com/epndeals/v1?marketplace=it&campaignid=5338612798&categoryid=20737&toolid=100034&rotationId=724-53478-19255-0&format=atom

RSS
https://rest.ebay.com/epn/v1/find/item.rss?keyword=%28guinzaglio%2Cmangime%2Ccani%2Cgiochi%29&categoryId1=20742&sortOrder=BestMatch&programid=12&campaignid=5338612797&toolid=10039&listingType1=All&feedType=rss&lgeo=1

I tried pasting the atom feed also on the simplepie demo page but it didn't work either. (https://simplepie.org/demo/) 

> **IMPORTANT:** If you are posting code or output, please make sure you wrap it with [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) so that it is readable.

#### Possible Solutions

If you have already ideas how to solve the issue, add them here. (remove this section if not needed)

#### Environment

Relevant information about your environment.

**Comment by skyzyx** [comment]
Closing because the ticket did not follow instructions.
