### ISSUE TITLE
[BUG] Error while parsing Atom feed

### ISSUE THREAD

**Issue by ocroquette** [simplepie/simplepie#630]
#### Description

Parsing of following feed fails: https://www.lesnumeriques.com/rss.xml

#### Actual Behavior

$feed->error() returns:

A feed could not be found at `https://www.lesnumeriques.com/rss.xml`; the status code is `200` and content-type is `text/html` 

#### Possible Solutions

Ideas:

- Improve error message to give a hint about actual issue
- Is it because the content-type is wrong? In this case, add option to ignore it?

**Comment by skyzyx** [comment]
It is 100% because the content-type is wrong. Search the issues for references to `$simplepie->force_feed()` to work around it.

**Comment by ocroquette** [comment]
Thanks for the reply. It comes further with force_feed, however I don't understand the next error message:
```
https://www.lesnumeriques.com/rss.xml is invalid XML, likely due to invalid characters. XML error: Mismatched tag at line 1, column 362 
```

The XML seems valid, and the first line is not that long.

Here is the code:
```
    $url = "https://www.lesnumeriques.com/rss.xml";
    $sp = new SimplePie();
    $sp->set_feed_url($url);
    $sp->enable_cache(false);
    $sp->strip_htmltags(false);

    $sp->force_feed(true);
    $sp->init();
```

**Comment by skyzyx** [comment]
First, see if it works on the SimplePie demo page.

If it DOES work, then it’s a problem with the low level XML parser that your PHP was compiled with.

If it DOES NOT work, then it’s an issue with the feed itself. They’re publishing invalid XML.

I’m not sure if you have any control over either of these factors, but there’s a very high probability that one of those is the source of the issue.

**Comment by ocroquette** [comment]
The demo on your server does work, however my issue is not related to my parser. I added a dump of the "XML data" in case of an error, and it actually is:

```
Not Found

The requested URL /_Incapsula_Resource was not found on this server.
```

It looks like the remote host returns a HTTP redirect to "/_Incapsula_Resource", which doesn't exist on my server, hence the "Not found" error. That also explains why I need force_feed().

Incapsula is some kind of protection software, it looks like my IP is blacklisted, or a similar issue. In any case, it is nothing SimplePie can do about. The only thing would be to do the troubleshooting easier, for instance some kind of debugging option.
