### ISSUE TITLE
[BUG] Packagist not auto-updated

### ISSUE THREAD

**Issue by flack** [simplepie/simplepie#635]
#### Description

Packagist doesn't show the latest SimplePie version, but is stuck on 1.5.3:

https://packagist.org/packages/simplepie/simplepie

#### Steps to Reproduce

Run 

```
composer require simplepie/simplepie
```

#### Expected Behavior

It should install 1.5.4

#### Actual Behavior

Version 1.5.3 is installed instead, since Packagist doesn't see the latest release

#### Possible Solutions

Packagist says the package is not auto-updated, so there is probably something wrong with your Github service hook

**Comment by skyzyx** [comment]
Resolved.

https://github.com/simplepie/simplepie/pull/628#issuecomment-567625923
