### ISSUE TITLE
[BUG] Double encoding for feed item's title

### ISSUE THREAD

**Issue by mnaas** [simplepie/simplepie#637]
#### Steps to Reproduce
add this URL to the parser www.fastcompany.com
check titles and descriptions.
This website's feed has some symbols encoded in the text like for example
```XML
<item>
            <title><![CDATA[Oops! Weight Watchers&#8217; Twitter campaign gets ensnared in WWIII chatter]]></title>
            <description><![CDATA[<p>On Thursday, Weight Watchers debuted its latest social media campaign with a promoted tweet, #thisismyWW. The brand, which <a href="https://www.fastcompany.com/90241019/ww-heres-why-weight-watchers-changed-its-name" target="_blank" rel="noopener">changed its name to WW</a> in 2018, likely thought this was an uplifting message, intended to encourage its members to share their goals for the new year.</p>
<p>But after an American airstrike last night killed&#xA0;Iran&#x2019;s Maj. Gen. Qassim Suleimani&#x2014;a move that further escalated conflict between the two countries and prompted fears that it could lead to World War 3&#x2014;the campaign took on a different tone. Hashtags like #WorldWarIII started trending alongside #thisismyWW, and the Twitterati took note.</p>
<blockquote class="twitter-tweet" data-width="525" data-dnt="true">
<p lang="en" dir="ltr">Weight Watchers might want to pull this trending hashtag campaign <a href="https://t.co/pAp0WMJQJl">pic.twitter.com/pAp0WMJQJl</a></p>
<p>&#x2014; Colin Jones (@colinjones) <a href="https://twitter.com/colinjones/status/1212934126451515392?ref_src=twsrc%5Etfw">January 3, 2020</a></p></blockquote>
<p><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></p>
<blockquote class="twitter-tweet" data-width="525" data-dnt="true">
<p lang="en" dir="ltr">Weight Watchers probably regretting their promoted hashtag tonight <a href="https://t.co/9QNNYdFETh">pic.twitter.com/9QNNYdFETh</a></p>
<p>&#x2014; Chelsea Fagan (@Chelsea_Fagan) <a href="https://twitter.com/Chelsea_Fagan/status/1212939398519635971?ref_src=twsrc%5Etfw">January 3, 2020</a></p></blockquote>
<p><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></p>
<blockquote class="twitter-tweet" data-width="525" data-dnt="true">
<p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/ThisIsMyWW?src=hash&amp;ref_src=twsrc%5Etfw">#ThisIsMyWW</a> is the Iannucian social media disaster we deserve. Let it be the final nail in this website&#x2019;s coffin.</p>
<p>&#x2014; bobby finger (@bobbyfinger) <a href="https://twitter.com/bobbyfinger/status/1212941949956763648?ref_src=twsrc%5Etfw">January 3, 2020</a></p></blockquote>
<p><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></p>
<p>Some people did, indeed, <a href="https://twitter.com/alexia/status/1213112725536043008?s=20" target="_blank" rel="noopener">share their plans</a> for eating healthy in 2020.&#xA0;But others assumed the hashtag was a <a href="https://twitter.com/boringwhitedad/status/1212931102375137280" target="_blank" rel="noopener">reference to World War III</a> or pointed out that &#x201C;WW&#x201D;&#x2014;which, unlike the famous 57-year-old Weight Watchers brand, remains largely unfamiliar&#x2014;<a href="https://twitter.com/AngryBlackLady/status/1212785949957996545?s=20" target="_blank" rel="noopener">could be mistaken</a> for a number of other things. Which is to say: This ill-timed campaign may not be the only thing WW regrets right about now.</p>
]]></description>
            <link>https://www.fastcompany.com/90448607/oops-weight-watchers-twitter-campaign-gets-ensnared-in-wwiii-chatter?partner=rss&amp;utm_source=rss&amp;utm_medium=feed&amp;utm_campaign=rss+fastcompany&amp;utm_content=rss</link>
            <guid isPermaLink="false">https://www.fastcompany.com/90448607/oops-weight-watchers-twitter-campaign-gets-ensnared-in-wwiii-chatter</guid>
            <category><![CDATA[News]]></category>
            <dc:creator><![CDATA[Pavithra Mohan]]></dc:creator>
            <pubDate>Fri, 03 Jan 2020 18:00:50 GMT</pubDate>
            <media:content url="https://images.fastcompany.net/image/upload/w_1280,q_auto,f_auto,fl_lossy/wp-cms/uploads/2020/01/poster-ww-weight-watchers-drone-strike-twitter-hashtag-1.jpg" type="image/jpeg" medium="image" width="1280" height="720"/>
        </item>
```
Although both title and description does it the same way but title is extracted with SiimplePie having the encoded symbols double encoded unlike the way it is for description. you can test this in the demo and you will see that the title is displayed with these symbols encoded while in the description they are displayed decoded. Which is because title was double encoded by the package.

I investigated the issue deeper and found out that simplepie_item::get_title() returns the title double encoded while the simplepie_item::get_description() gets the description decoded and displaying all symbols naturally. I find it weird that you are treating title and description differently while both are coming from the source feed with same symbols encoded in the same way.

**Comment by skyzyx** [comment]
From the [RSS Best Practices Profile](http://www.rssboard.org/rss-profile#element-channel-item-title):

> 4.1.1.20.10 title
> 
> Requirements
> 
> An item's title element holds [character data](http://www.rssboard.org/rss-profile#data-types-characterdata) that provides the item's headline. This element is OPTIONAL if the item contains a [description](http://www.rssboard.org/rss-profile#element-channel-item-description) element.
> 
> ```xml
> <title>Joe Bob Goes to the Drive-In</title>
> ```

If we follow the definition of "character data" in this context, we see:

> 3.1 Character Data
> 
> Requirements
> 
> For all elements defined in the RSS specification that enclose character data, the text SHOULD be interpreted as plain text with the exception of an item's description element, which MUST be suitable for presentation as HTML. All of these elements MUST NOT contain child elements.
> 
> There's no limit on the length of character data that can be contained in an RSS element.
> 
> Recommendations
> 
> The specification has lacked clarity regarding whether HTML is permitted in elements other than an item's description, leading to wide variance in how aggregators treat character data in other elements. This makes it especially difficult for a publisher to determine how to encode the characters "&" and "<", which must be encoded in XML.
> 
> In elements that contain plain text, the form of encoding that works in the widest number of aggregators is using the hexadecimal character reference &#x26; to represent "&" and &#x3C; to represent "<".
> 
> […]
> 
> This form of encoding was presented successfully for all seven of the preceding examples in Apple Safari, Bloglines, Mozilla Firefox and Internet Explorer, six-of-seven in Opera and five-of-seven in FeedDemon and Google Reader. It failed three or more tests in BottomFeeder, My Yahoo and NewsGator Online.
> 
> A publisher SHOULD encode "&" and "<" in plain text using hexadecimal character references. When encoding the ">" character, a publisher SHOULD use the hexadecimal reference &#x3E;.

Generally speaking, here's how the decoding is supposed to work. "CDATA" stands for "Character Data" which essentially translates to "leave me (mostly) alone". You gain one decode for markup as compared to plain text.

| Type | Plain Text | HTML |
| ---- | ------ | ------ |
| CDATA | decode 0× | decode 1× |
| Non-CDATA | decode 1× | decode 2× |

If this were an RPG game, CDATA content with an HTML modifier is a +2 entity decode.

Since `<description>` is expected to be treated as HTML, it gets one additional decode as compared to `<title>`, which is expected to be treated as plain text — where both are CDATA or both are non-CDATA.

In this case, both elements are wrapped CDATA blocks. `<description>` is HTML, while `<title>` is plain text. Therefore, CDATA'd `<description>` gets HTML-entity-decoded ONCE, while CDATA'd `<title>` gets HTML-entity-decoded ZERO times.

As far as we can tell, and since the spec lacks clarity, we aligned more closely with the common interpretation by other vendors.

Make sense?

**Comment by mnaas** [comment]
Thanks for your detailed replay. 

> In this case, fastcompany.com has a feed that doesn't follow the best practices for RSS. You'll need to decode their titles one additional time in your userland code to work around this.

Currently I have to apply 
```
html_entity_decode(htmlspecialchars_decode($title));
```
To get data decoded correctly. Am I doing it correct this way?
