### ISSUE TITLE
[BUG]  No Demo Folder In The Download

### ISSUE THREAD

**Issue by Woolwit** [simplepie/simplepie#639]
There is no demo folder in the download.
From the README:

> 6. `demo/` - A basic feed reader demo that shows off some of SimplePie's more
   noticeable features.

**Comment by skyzyx** [comment]
What download? From where?

**Comment by Woolwit** [comment]
Apologies if I'm doing it wrong, but shouldn't there be a demo folder when downloading the master at: https://github.com/simplepie/simplepie/archive/master.zip
And likewise when downloading 1.5 at: http://simplepie.org/downloads/

**Comment by skyzyx** [comment]
If it still exists in the repository, then yes, <https://github.com/simplepie/simplepie/archive/master.zip> should have it. I can't say the same for the SimplePie.org website, however.

Either way, `composer` is the current way that PHP dependencies should be managed. I would definitely recommend that route over a manual download.

**Comment by Andrewsuares** [comment]
Hello,

I downloaded via composer and downloaded the ZIP https://github.com/simplepie/simplepie/archive/master.zip

The demo folder does NOT exist in both the methods. Can you please fix this.

**Comment by Andrewsuares** [comment]
Hello, how do I download the demo folder?

**Comment by JanPetterMG** [comment]
It's removed for a reason, you know?
Why don't you guys use `git`, or even "Github for Desktop"?

The exclusion list: https://github.com/simplepie/simplepie/blob/master/.gitattributes

FYI: https://www.pixelite.co.nz/article/using-git-attributes-exclude-files-your-release/

**Comment by Andrewsuares** [comment]
Hello Jan,

This is probably the first script I've come across where the demo is excluded. Its fast when you download the script, look at the demo, test, integrate. I used composer and that didn't work either. To install a third party tool to explore this script seems excessive. Maybe you want to reconsider your reason for removing the demo. Best.

**Comment by skyzyx** [comment]
We're talking about using Git… on GitHub. Asking you to use Git to pull the source code is well-within the bounds of reasonability.

Locking this thread.
