### ISSUE TITLE
how can we get image 

### ISSUE THREAD

**Issue by rosshhun** [simplepie/simplepie#642]
I am wondering how can I get a particular image from the feed or an image from the feed.
and one more thing is there any official forum for simplepie.org?

**Comment by skyzyx** [comment]
> I am wondering how can I get a particular image from the feed or an image from the feed.

Not enough information here. Are you talking about the `<channel><image>` element, or are you talking about some arbitrary image inside the HTML content of the `<item>`?

> and one more thing is there any official forum for simplepie.org?

Not for about 10 years now.

**Comment by sayirosshhun** [comment]
talking about both the <channel><image> element and image inside the HTML content of the <item>

**Comment by skyzyx** [comment]
Post the code to show what you've already tried, and those of us who have a few minutes might be able to help you tweak your code to get it working.

**Comment by arena94** [comment]
i solved this a while ago by extending class SimplePie_Item with a get _image() function.

Looking for code sample ?  take a look at a wordpress plugin (dashpress)

https://wordpress.org/plugins/dashpress/

the extended class is in dashpress/dbp-admin/class/DBP_SimplePie_Item.class.php

**Comment by Art4** [comment]
The `get_image()` and `get_images()` methods were build using `get_thumbnails()` and can be found here: https://plugins.trac.wordpress.org/browser/dashpress/tags/5.0/dbp-admin/class/DBP_SimplePie_Item.class.php#L46

@mblaney I think this can be closed.

**Comment by marc-farre** [comment]
I've sent this PR: https://github.com/simplepie/simplepie/pull/858
I hope it helps!
