### ISSUE TITLE
[BUG] PHP Notice: A feed could not be found

### ISSUE THREAD

**Issue by eiland-asbl** [simplepie/simplepie#651]
#### Description
When polling a (not too valid) feed: SP 1.5 returns:

```[php7:notice] PHP Notice: A feed could not be found at `https://energeia.nl/?rss`. This does not appear to be a valid RSS or Atom feed. in /include/simplepie-1.5/library/SimplePie.php on line 1456```

I admit, the feed is not great, but, why complain?

**Comment by Art4** [comment]
The url https://energeia.nl/?rss does not contain valid RSS feed. It starts with:

```xml
<Channel>
<feedType>rss_2.0</feedType>
<encoding/>
<styleSheet/>
<modules/>
<foreignMarkup/>
<title>Energeia - Home</title>
<description>De RSS feed van energeia.nl</description>
...
```

but it has to start with something like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
...
```

**Comment by Art4** [comment]
@mblaney I think this can be closed.
