### ISSUE TITLE
[BUG] Php 7.4 PHP Runtime Deprecation Notice: implode(): Passing glue string after array is deprecated. 

### ISSUE THREAD

**Issue by robertvonhackwitz** [simplepie/simplepie#666]
#### Description

After Upgrading to Php 7.4 a" PHP Runtime Deprecation Notice: implode(): Passing glue string after array is deprecated" appears.

It should be enough to reverse the parameters in file SimplePie/Parse/Date.php , lines 557 and 558

**Comment by jtojnar** [comment]
This have been fixed in SimplePie 1.5.3:

https://github.com/simplepie/simplepie/commit/38b504969ed08903cb12718e8270263a8c93080e

Please upgrade.

**Comment by robertvonhackwitz** [comment]
Ops, sorry.
Thank you for your reply

**Comment by Art4** [comment]
@mblaney This issue can be closed.
