### ISSUE TITLE
PHP 8.0: Deprecated:  Required parameter $working follows optional parameter $type

### ISSUE THREAD

**Issue by vendeeglobe** [simplepie/simplepie#668]
SimplePie 1.5.6:

PHP Deprecated:  Required parameter $working follows optional parameter $type in /lib/SimplePie/library/SimplePie/Locator.php on line 97

**Comment by vendeeglobe** [comment]
Since I ported back all new patches from master (ebba0a8) the PHP Deprecated error message disappeared from the error log of the server.

**Comment by jtojnar** [comment]
Likely fixed by https://github.com/simplepie/simplepie/commit/d18f05c9ed75e117b6680dd4e9cdd28d01392808

**Comment by vendeeglobe** [comment]
It's likely fixed, reopen it if necessary.
