### ISSUE TITLE
Declaration of WP_SimplePie_Blog_Item

### ISSUE THREAD

**Issue by hlina89** [simplepie/simplepie#679]
get_id($hash = false) must be compatible with SimplePie_Item::get_id($hash = false, $fn = 'md5')

**Comment by jrfnl** [comment]
This is an issue with the [Blogger Importer plugin for WordPress](https://wordpress.org/plugins/blogger-importer/), not an issue with SimplePie itself.

The issue has already been reported there, but looks like the maintainer hasn't fixed it yet:
* https://wordpress.org/support/topic/simplepie-error-2/
* https://core.trac.wordpress.org/ticket/52084
