### ISSUE TITLE
[BUG] Multiple valid feeds not being parsed

### ISSUE THREAD

**Issue by Poorchop** [simplepie/simplepie#687]
#### Description

Several valid feeds are not being parsed. These feeds are confirmed to be working in two other RSS clients as of today.

#### Steps to Reproduce

Attempt to fetch the following feeds:

1. `http://www.frag-net.com/rss.xml`
2. `https://gopherproxy.net/bitreich.org:70/0/news.atom.xml`
3. `https://adamsgaard.dk/atom.xml`
4. `https://blog.thimbleweedpark.com/rss`

#### Expected Behavior

The feeds are fetched successfully.

#### Actual Behavior

Fetching these feeds returns errors.

1. the status code is `200` and content-type is `application/octet-stream` in /FreshRSS/lib/SimplePie/SimplePie.php on line 1807
2. the status code is `200` and content-type is `text/plain` in...
3. the status code is `200` and content-type is `application/octet-stream` in...
4. the status code is `200` and content-type is `` in...

#### Possible Solutions

It seems that there are issues parsing these content types or feeds without a content type. In the 4th link, the feed is dead but other feed readers are still able to retrieve the old contents. I would like to import these contents into FreshRSS for posterity.

#### Environment

OpenBSD 6.9, PHP 8.0.9, FreshRSS 1.18.1, PostgreSQL 13.2, nginx 1.18.0

**Comment by skyzyx** [comment]
> Fetching these feeds returns errors.
> 
> 1. the status code is 200 and content-type is application/octet-stream in /FreshRSS/lib/SimplePie/SimplePie.php on line 1807
> 1. the status code is 200 and content-type is text/plain in...
> 1. the status code is 200 and content-type is application/octet-stream in...
> 1. the status code is 200 and content-type is `` in…

A feed is not just its contents; it is also the metadata around its contents.

Valid media types for RSS are `application/rss+xml` and `text/xml`. For Atom, they're `application/atom+xml` and `text/xml`. This is how the server says "this is a feed". By default, SimplePie looks at these headers when fetching URLs to determine whether or not they're worth looking at. If the _server_ says that this is a chunk of random binary data, SimplePie isn't going to bother. If the server says it's just plain text, that's clearly not a feed so SimplePie won't bother.

The contents of the payload _may_ be valid RSS/Atom, but only in the academic sense; not in the real-world sense.

Having said that, if you _know_ that a particular URL is a valid feed and can/should be parsed, you can force SimplePie to ignore what the server is telling it, and read the data anyway. Using the "long-form" initialization, you can set the `force_feed()` option before calling `init()`. It looks _something_ like this:

```php
$feed = new SimplePie();
$feed->set_url($url);
$feed->force_feed(); // <-- This one
$feed->init();

// …
```

**Comment by Poorchop** [comment]
I understand what you're saying but I think there's a case to be made when several other feed readers support these feeds. Moreover, all of these feeds—with the exception of number 2 in the list—are marked as valid by the [W3C Feed Validation Service](https://validator.w3.org/feed/).

I don't know if it's a good idea to depend on the MIME type when making a decision as to whether or not a feed is valid, but this at least led me to figure out that I can force FreshRSS to fetch the feed anyway by appending `#force_feed` so thanks.

**Comment by skyzyx** [comment]
This was debated very, very heavily about 15 years ago.￼￼ We spent several weeks going back-and-forth about it, and after thoroughly weighing the pros and cons, this is where we settled.

If the current maintainers choose to make that change, that's up to them.

But I've given you the explanation  and rationale for how it currently works.￼
