### ISSUE TITLE
Undefined constants throwing error in PHP 7.4

### ISSUE THREAD

**Issue by merricks** [simplepie/simplepie#703]
#### Description

When using SimplePie with PHP 7.4 and attempting to create a new file (class `SimplePie_File`), I'm running into the error `Use of undefined constant SIMPLEPIE_FILE_SOURCE_NONE - assumed 'SIMPLEPIE_FILE_SOURCE_NONE' (this will throw an Error in a future version of PHP)`. The same thing is seen with all SimplePie constants, not just related to files.

#### Steps to Reproduce

Call a function that uses a SimplePie constant (for example, `new SimplePie_File($url)`)

#### Environment

PHP 7.4

**Comment by jtojnar** [comment]
Those constants are defined in https://github.com/simplepie/simplepie/blob/master/library/SimplePie.php so you need to ensure the file is loaded before any other file.

**Comment by merricks** [comment]
Thank you! I'm not sure what changed on my end, but it's loading that file properly now. (Not an actual bug.)
