### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by jrfnl** [simplepie/simplepie#704]
Any chance of a new release in the near future ? Would be great for external projects, like WordPress which includes SimplePie as a dependency, to be able to upgrade to a new tagged release which includes the latest PHP 8.0 and 8.1 fixes.

**Comment by mblaney** [comment]
done. thanks for all your work on it this year!

**Comment by jrfnl** [comment]
@mblaney Thanks and happy to contribute when I can.

**Comment by jrfnl** [comment]
@mblaney Looks like the version number update was missed for this release ? https://github.com/simplepie/simplepie/issues/708

**Comment by jrfnl** [comment]
Closing after the release v 1.5.7 and 1.5.8. Thanks @mblaney !
