### ISSUE TITLE
[BUG] Incorrect `@version` and `SIMPLEPIE_VERSION` in the 1.5.7 release

### ISSUE THREAD

**Issue by SergeyBiryukov** [simplepie/simplepie#708]
It looks like the `@version` tag and the `SIMPLEPIE_VERSION` constant in the `SimplePie.php` file in the latest release are incorrect: they still say `1.5.6`. Would it be possible to publish a `1.5.8` release to correct that?

**Comment by mblaney** [comment]
version is fixed and released in 1.5.8
