### ISSUE TITLE
[BUG] getting  implode() error  on Date.php  file

### ISSUE THREAD

**Issue by dht20** [simplepie/simplepie#718]
when loading some feeds.
getting that error:

( ! )  Deprecated: implode(): Passing glue string after array is deprecated.  Swap the parameters in  C:\wamp64\www\rssPod\simplepie-1.5\library\SimplePie\Parse\Date.php on  line 544

and 

( ! )  Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in C:\wamp64\www\rssPod\simplepie-1.5\library\SimplePie\Parse\Date.php on line 545

**Comment by jtojnar** [comment]
This has been [fixed](https://github.com/simplepie/simplepie/commit/38b504969ed08903cb12718e8270263a8c93080e) in SimplePie 1.5.3, please make sure you have up to date version.
