### ISSUE TITLE
[BUG] Uncaught TypeError: array_slice(): Argument #3 ($length) must be of type ?int

### ISSUE THREAD

**Issue by vendeeglobe** [simplepie/simplepie#773]
Version: 1.8

#### Description

WackoWiki feed action:
`$feed->get_items($pagination['offset'], $max)`

PHP Fatal error:  Uncaught TypeError: array_slice(): Argument #3 ($length) must be of type ?int, string given in /lib/SimplePie/src/SimplePie.php:30..

#### Suggestion

`$feed->get_items($pagination['offset'], (int) $max)`

Maybe cast $end with (int) also in array_slice?

`return array_slice($items, $start, (int) $end);`

And check example code with `get_items()`.

**Comment by jtojnar** [comment]
The `get_items` function expects `int` as arguments:

https://github.com/simplepie/simplepie/blob/65b095d87bc00898d8fa7737bdbcda93a3fbcc55/src/SimplePie.php#L2989-L2990

so it is really a bug in WackoWiki.

One thing we could do is introduce typehints to the methods to make it fail sooner.
