### ISSUE TITLE
Use SPDX comments

### ISSUE THREAD

**Issue by jtojnar** [simplepie/simplepie#778]
Currently, each file starts with a long license blurb. It might be cleaner to replace it with SPDX comments, which also uniquely identify the license, while being much shorter:

```php
// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2022 Artur Weigandt
```

- https://reuse.software/tutorial/
- https://www.linuxfoundation.org/blog/blog/solving-license-compliance-at-the-source-adding-spdx-license-ids

_Originally posted by @jtojnar in https://github.com/simplepie/simplepie/pull/752#discussion_r1005729998_

**Comment by Art4** [comment]
I like the concept. 👍 

It took me a while to find a PHP repository that has implement the REUSE spec correctly. (most repos don't have the requires `LICENSES` folder)

Here one can see a good example how the licenses will be managed: https://github.com/theCalcaholic/nextcloud-secrets

For me it looks light and clean. And I like that even images or binary files will have a specific license information.
