### ISSUE TITLE
Get items by date range

### ISSUE THREAD

**Issue by rmccue** [simplepie/simplepie#8]
_Originally reported by Geoffrey Sneddon as [issue 28](http://bugs.simplepie.org/issues/show/28)_

We should be able to get items in a date range. This should, for the sake of consistency, take two parameters which are both the number of seconds since the epoch (i.e., $start, $end; or maybe $start, $duration).

**Comment by szabacsik** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  andras.szabacsik@gmail.com
    Domain szabacsik.hu has exceeded the max emails per hour (62/50 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:36106 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by hardcube.23net.hu with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dPMH4-003iKh-Vk
	for andras@szabacsik.com; Mon, 26 Jun 2017 07:09:23 +0200
Date: Sun, 25 Jun 2017 22:08:41 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1498453721;
	bh=K5kWzDy8B08F/HlZNsAJthxZPmJPLz1M8uxkzuJPT6w=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=heLdtDLV5XnzWi5h/4S60t90VVx5L6SkMliuc7lV6pDIbW/RennlebUQz40INtImA
	 cvX0kRsqNOy5u2Ii6DzVs6mC90Jezq5RL4sr2JQWp8ukJuf6b8030Koi1vBBLEjckg
	 PWPxKXKY74Qu+6b/ECWQh8y/qAVDPyPB3c2Gdkz4=
