### ISSUE TITLE
[BUG] Cache constantly updating

### ISSUE THREAD

**Issue by Sir-Will** [simplepie/simplepie#830]
#### Description

It doesn't seem like the cache is working correctly for me. Every time I reload the page, I see the timestamps of the cache files update.
This shouldn't be the case, or?

#### Steps to Reproduce

```php
        $infoFeed = new SimplePie();
        $infoFeed->set_feed_url($infoFeeds);
        $infoFeed->set_cache_duration(600);
        $infoFeed->init();
        $infoFeed->handle_content_type();
```

#### Expected Behavior

Cache not updating every run.

#### Actual Behavior

Cache is updating on every run.

#### Possible Solutions

If you have already ideas how to solve the issue, add them here. (remove this section if not needed)

#### Environment

PHP 8.1
SimplePie 1.8.0

**Comment by bart-v** [comment]
Same problem here.

This is caused by these 4 occurrences of `cache_expiration_time`
https://github.com/simplepie/simplepie/blob/master/src/SimplePie.php#L1676
https://github.com/simplepie/simplepie/blob/master/src/SimplePie.php#L1769
https://github.com/simplepie/simplepie/blob/master/src/SimplePie.php#L1920

`cache_expiration_time` => should be => `__cache_expiration_time`

Or at least the array index should be consistent everywhere...

**Comment by Art4** [comment]
The default file cache is deprecated an will be removed in the next major release. Instead you should use a PSR-16](https://www.php-fig.org/psr/psr-16/) cache implementation like [Symfony Cache](https://symfony.com/doc/current/components/cache.html) or [every other implementation](https://packagist.org/providers/psr/simple-cache-implementation).

```php
$simplepie = new \SimplePie\SimplePie();
$simplepie->set_cache(
    new \Symfony\Component\Cache\Psr16Cache(
        new \Symfony\Component\Cache\Adapter\FilesystemAdapter()
    ),
);
```

**Comment by bart-v** [comment]
Then, a simple example on how to then set the cache type (i.e. file), location and duration would be nice.
The current documentation only mentions a deprecated example and does not say anything about PSR-16 ...

**Comment by bart-v** [comment]
At least it's clear that the PSR-16 changes in https://github.com/simplepie/simplepie/pull/752 broke the legacy cache.
I think reverting https://github.com/simplepie/simplepie/pull/752/commits/3ba7c912d470f5bf9ddf2e414430e52d2f6a9823 will fix this bug
Would you consider this, please?

**Comment by Art4** [comment]
> Then, a simple example on how to then set the cache type (i.e. file), location and duration would be nice. The current documentation only mentions a deprecated example and does not say anything about PSR-16 ...

The code example is in #777. Setting cache type and location is part of the PSR-16 implementation. The cache duration is still configured using `$simplepie->set_cache_duration($seconds);`.

**Comment by bart-v** [comment]
I still don't see an example that one can easily copy/past and just fill in 2 or 3 parameters.
Not everyone can read the whole PSR-16 spec to write a few lines of code...

**Comment by Art4** [comment]
> I still don't see an example that one can easily copy/past and just fill in 2 or 3 parameters.

Please take a look again at [my comment above](https://github.com/simplepie/simplepie/issues/830#issuecomment-1683866172). It already shows you a working example using [Symfony Cache](https://symfony.com/doc/current/components/cache.html) using the [FilesystemAdapter](https://symfony.com/doc/current/components/cache/adapters/filesystem_adapter.html). But you are free to choose another adapter or even [every other implementation](https://packagist.org/providers/psr/simple-cache-implementation).

> Not everyone can read the whole PSR-16 spec to write a few lines of code...

You don't have to read the PSR-16 spec. You have to look at the [more than 100 implementations](https://packagist.org/providers/psr/simple-cache-implementation) (and the PSR-16 spec allows you to try and use them all). Choose the one that works best for you. No one knows your project and use case better than you do.

**Comment by bart-v** [comment]
The example above does not show how to define the (custom) cache file location.
Which PSR-16 is really not so important, so any will do, that is why people needs a simple example

**Comment by Art4** [comment]
> The example above does not show how to define the (custom) cache file location. Which PSR-16 is really not so important, so any will do, that is why people needs a simple example

The file location in the [FilesytemAdapter](https://symfony.com/doc/current/components/cache/adapters/filesystem_adapter.html) is not required, it uses [`sys_get_temp_dir()`](https://www.php.net/manual/en/function.sys-get-temp-dir.php) by default. If needed [please read the docs](https://symfony.com/doc/current/components/cache/adapters/filesystem_adapter.html) for more customization.

I would like to avoid more complex examples for a specific library. Mentioning the Symfony cache implementation alone is already very opinionated. If you would like to have a more customized example for this library you are welcome to open a PR.

**Comment by Art4** [comment]
I've found the reason for this issue and opened #846. 

@bart-v Could you please confirm that this PR will fix your issue?

**Comment by bart-v** [comment]
Looks good, please go ahead
