### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by benni1516** [simplepie/simplepie#855]
iff -> if
[     * @var ?string Original feed URL, or new feed URL iff HTTP 301 Moved Permanently](https://github.com/simplepie/simplepie/blob/290e930c21bdfa513c11119507767d5c72258ab5/src/SimplePie.php#L428)

[     * iff it is a 301 redirection](https://github.com/simplepie/simplepie/blob/290e930c21bdfa513c11119507767d5c72258ab5/src/SimplePie.php#L2280C12-L2280C12)

**Comment by jtojnar** [comment]
“iff” is short for “if and only if”

**Comment by Art4** [comment]
@benni1516 I´ve had the [same thoughts](https://github.com/simplepie/simplepie/pull/734#discussion_r876672128) last year. 😊 

See also Wikipedia: https://en.wikipedia.org/wiki/If_and_only_if

**Comment by Rachad-Alabi-ADEKAMBI** [comment]
> iff -> if [ * @var ?string Original feed URL, or new feed URL iff HTTP 301 Moved Permanently](https://github.com/simplepie/simplepie/blob/290e930c21bdfa513c11119507767d5c72258ab5/src/SimplePie.php#L428)
> 
> [ * iff it is a 301 redirection](https://github.com/simplepie/simplepie/blob/290e930c21bdfa513c11119507767d5c72258ab5/src/SimplePie.php#L2280C12-L2280C12)

should i fix it ?
