### ISSUE TITLE
Simultaneous Requests with cURL

### ISSUE THREAD

**Issue by rmccue** [simplepie/simplepie#9]
_Originally reported by Joseph Crawford as [issue 33](http://bugs.simplepie.org/issues/show/33)_

http://www.phpied.com/simultaneuos-http-requests-in-php-with-curl/

I'd like to see this integrated into 1.1 or the 2.x version.

**Comment by szabacsik** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  andras.szabacsik@gmail.com
    Domain szabacsik.hu has exceeded the max emails per hour (61/50 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:36551 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by hardcube.23net.hu with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dPMH0-003iJa-He
	for andras@szabacsik.com; Mon, 26 Jun 2017 07:09:18 +0200
Date: Sun, 25 Jun 2017 22:08:37 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1498453717;
	bh=dtcuvfL3bjTplMsJZ4h9AaJWP89xfjLHyDq4HzUMu0M=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=XZsmpmyJier07eIJ+Xr1dTmk1fHDb7JrJ4CogCqyzfPWcIOqVTapM3IVdiwprDIxp
	 tTl57s5fIdFUkZY9ZzCYz3jyN+UQDIX0MXcjj48f6K6+cpFui5qLTjTqz7oqP7CnzS
	 0yydUBZ8pYt7W7UwW67eU9lRdkE1/ZtoUx+rnvuM=
